// Shorthand / abbreviation -> canonical term. Matching is case-insensitive
// and applied after normalization, so keys and values should already be
// lowercase and normalized (see normalize() in matching.ts).
export const SYNONYMS: Record<string, string> = {
  'glute med': 'gluteus medius',
  'glute max': 'gluteus maximus',
  'glutes': 'gluteus maximus',
  'ta': 'transverse abdominis',
  'tva': 'transverse abdominis',
  'tfl': 'tensor fascia latae',
  'scm': 'sternocleidomastoid',
  'lats': 'latissimus dorsi',
  'lat': 'latissimus dorsi',
  'vmo': 'vastus medialis oblique',
  'peroneals': 'fibularis',
  'peroneus': 'fibularis',
  'hip flexors': 'hip flexor complex',
  'calves': 'gastrocnemius',
  'calf': 'gastrocnemius',
  'pecs': 'pectoralis major',
  'pec major': 'pectoralis major',
  'pec minor': 'pectoralis minor',
  'delts': 'deltoid',
  'anterior tib': 'anterior tibialis',
  'posterior tib': 'posterior tibialis',
  'erectors': 'erector spinae',
  'rhomboid': 'rhomboids',
  'traps': 'trapezius',
  'upper traps': 'upper trapezius',
  'mid traps': 'mid trapezius',
  'lower traps': 'lower trapezius',
  'qf': 'quadratus femoris',
  'qls': 'quadratus lumborum',
  'ql': 'quadratus lumborum',
  'hr': 'heart rate',
  'hrmax': 'maximum heart rate',
  'hrrest': 'resting heart rate',
  'rpe': 'rate of perceived exertion',
  'vt1': 'first ventilatory threshold',
  'vt2': 'second ventilatory threshold',
  'gto': 'golgi tendon organ',
  'cns': 'central nervous system',
  'pns': 'peripheral nervous system',
  'ans': 'autonomic nervous system',
  '1rm': 'one rep max',
  'epoc': 'excess post-exercise oxygen consumption',
  'atp': 'adenosine triphosphate',
  'sa node': 'sinoatrial node',
  'rt': 'resistance training',
  'opt': 'optimum performance training',
}
