import type { Module } from '../../types/content'

export const acuteVariables: Module = {
  id: 'd3-acute-variables',
  domainId: 'd3',
  title: 'Acute Variables',
  estMinutes: 30,
  lessons: [
    {
      id: 'av-l1',
      title: 'The 5 knobs you turn every phase',
      plain: `Every workout has 5 dials: **reps** (how many times), **sets** (how many rounds), **intensity** (how heavy, as % of your one-rep max), **tempo** (how slow or fast each rep is), and **rest** (how long you recover between sets). Change these 5 dials together and you get a completely different training effect from the exact same exercise.`,
      nasm: `The acute variables — repetitions, sets, training intensity, repetition tempo, and rest interval — are the most fundamental components of a resistance training program design, and their manipulation determines the specific adaptation elicited.`,
      mustMemorise: ['The 5 acute variables: reps, sets, intensity, tempo, rest'],
    },
    {
      id: 'av-l2',
      title: 'Reading tempo notation',
      plain: `Tempo looks like "4/2/1" and it always reads in the same order: how long you lower the weight, how long you pause, how long you lift it. So "4/2/1" means lower for 4 seconds, pause 2 seconds at the bottom, lift in 1 second. "X/X/X" means "as fast as possible" — that's what you see in Phase 4 and 5 where the goal is force or speed, not control.`,
      nasm: `Repetition tempo is expressed in the order: eccentric / isometric / concentric. An "X" denotes an explosive or as-fast-as-possible tempo, used in Maximal Strength and Power phases.`,
      mustMemorise: ['Tempo order = eccentric / isometric / concentric', 'X/X/X = as fast as possible (Phases 4–5)'],
    },
    {
      id: 'av-l3',
      title: 'Phase 1 vs Phase 4: opposite ends of the spectrum',
      plain: `Phase 1 (Stabilization Endurance) is light weight, lots of reps (12–20), short-to-no rest, and a slow controlled tempo — you're teaching the body control. Phase 4 (Maximal Strength) is the opposite: very heavy (85–100% 1RM), very few reps (1–5), long rest (3–5 min) so you can recover enough to lift near-maximal loads again, and explosive/controlled tempo on the lift.`,
      nasm: `Phase 1 utilizes light loads (50–70% 1RM), high volume (12–20 reps), and minimal rest (0–90 s) to develop stabilization and muscular endurance. Phase 4 utilizes very heavy loads (85–100% 1RM), low volume (1–5 reps), and long rest periods (3–5 min) to maximize motor unit recruitment and neural adaptations for maximal strength.`,
      mustMemorise: [
        'Phase 1: 12–20 reps, 1–3 sets, 50–70% 1RM, 4/2/1 tempo, 0–90s rest',
        'Phase 4: 1–5 reps, 4–6 sets, 85–100% 1RM, X/X/X tempo, 3–5 min rest',
      ],
    },
  ],
  items: [
    {
      kind: 'typein', id: 'av-t1', tags: ['acute-variables', 'phase1'],
      prompt: 'Phase 1 rep range?',
      accept: ['12-20', '12 to 20'],
      hints: ['A wide, high range for endurance.', '1_-2_'],
      explanation: 'Phase 1 (Stabilization Endurance) uses 12–20 reps.',
    },
    {
      kind: 'typein', id: 'av-t2', tags: ['acute-variables', 'phase4'],
      prompt: 'Phase 4 (Maximal Strength) rep range?',
      accept: ['1-5'],
      hints: ['Very low, for near-maximal loads.', '_-_'],
      explanation: 'Phase 4 uses 1–5 reps at 85–100% 1RM.',
    },
    {
      kind: 'typein', id: 'av-t3', tags: ['acute-variables', 'phase1'],
      prompt: 'Phase 1 rest interval?',
      accept: ['0-90 sec', '0-90 seconds', '0-90s', '0 to 90 seconds'],
      hints: ['Short to none — keeps the heart rate up.', '_-__ seconds'],
      explanation: 'Phase 1 rest is 0–90 seconds.',
    },
    {
      kind: 'typein', id: 'av-t4', tags: ['acute-variables', 'phase4'],
      prompt: 'Phase 4 rest interval?',
      accept: ['3-5 min', '3-5 minutes', '3 to 5 minutes'],
      hints: ['Long enough to recover for a near-max lift.', '_-_ minutes'],
      explanation: 'Phase 4 rest is 3–5 minutes to allow full recovery for maximal loads.',
    },
    {
      kind: 'typein', id: 'av-t5', tags: ['acute-variables', 'tempo'],
      prompt: 'What tempo notation is used for Phases 4 and 5 (explosive/as-fast-as-possible)?',
      accept: ['x/x/x', 'xxx'],
      hints: ['Same letter repeated 3 times.', 'X/_/_'],
      explanation: 'X/X/X denotes an explosive, as-fast-as-possible tempo.',
    },
    {
      kind: 'typein', id: 'av-t6', tags: ['acute-variables', 'phase3'],
      prompt: 'Phase 3 (Muscular Development) intensity range as % of 1RM?',
      accept: ['75-85%', '75 to 85 percent', '75-85 percent'],
      hints: ['Between strength-endurance and maximal-strength intensities.', '__-__%'],
      explanation: 'Phase 3 uses 75–85% 1RM.',
    },
    {
      kind: 'table-fill', id: 'av-tf1', tags: ['acute-variables', 'grid'],
      title: 'Fill in the resistance training acute variables for each phase',
      headers: ['Phase', 'Reps', 'Sets', 'Intensity', 'Rest'],
      rows: [
        { cells: ['1 – Stabilization Endurance', { blank: true, accept: ['12-20'] }, { blank: true, accept: ['1-3'] }, { blank: true, accept: ['50-70%', '50-70'] }, { blank: true, accept: ['0-90 sec', '0-90s', '0-90 seconds'] }] },
        { cells: ['2 – Strength Endurance', { blank: true, accept: ['8-12'] }, { blank: true, accept: ['2-4'] }, { blank: true, accept: ['70-80%', '70-80'] }, { blank: true, accept: ['0-60 sec', '0-60s', '0-60 seconds'] }] },
        { cells: ['3 – Muscular Development', { blank: true, accept: ['6-12'] }, { blank: true, accept: ['3-5'] }, { blank: true, accept: ['75-85%', '75-85'] }, { blank: true, accept: ['0-60 sec', '0-60s', '0-60 seconds'] }] },
        { cells: ['4 – Maximal Strength', { blank: true, accept: ['1-5'] }, { blank: true, accept: ['4-6'] }, { blank: true, accept: ['85-100%', '85-100'] }, { blank: true, accept: ['3-5 min', '3-5 minutes'] }] },
      ],
    },
    {
      kind: 'mcq', id: 'av-m1', tags: ['acute-variables'], source: 'original',
      prompt: 'A client training for Maximal Strength (Phase 4) rests 45 seconds between sets. What is the issue?',
      options: [
        'Rest is far too short to recover for near-maximal loads; should be 3–5 minutes',
        'Rest is correct for this phase',
        'Rest should be 0 seconds for true strength gains',
        'Rest only matters in Phase 1',
      ],
      answer: 0,
      explanation: 'Phase 4 loads are 85–100% 1RM and require 3–5 minutes of rest to allow adequate recovery of the phosphagen system between near-maximal efforts.',
      whyWrong: ['', '45 seconds matches Phase 1–3 rest, not Phase 4.', 'Zero rest would prevent any recovery and increase injury risk at these loads.', 'Rest interval is programmed in every phase, just at different durations.'],
    },
    { kind: 'typein', id: 'av-t7', tags: ['acute-variables', 'phase2'], prompt: 'Phase 2 (Strength Endurance) rep range?', accept: ['8-12'], hints: ['Same as Phase 3\'s upper portion.', '_-__'], explanation: 'Phase 2 uses 8–12 reps.' },
    { kind: 'typein', id: 'av-t8', tags: ['acute-variables', 'phase2'], prompt: 'Phase 2 intensity as % of 1RM?', accept: ['70-80%', '70-80'], hints: ['Between Phase 1 and Phase 3.', '__-__%'], explanation: 'Phase 2 uses 70–80% 1RM.' },
    { kind: 'typein', id: 'av-t9', tags: ['acute-variables', 'phase5'], prompt: 'Phase 5 (Power) rest interval between paired exercises?', accept: ['3-5 min', '3-5 minutes'], hints: ['Same as Phase 4.', '_-_ minutes'], explanation: 'Phase 5 rests 3–5 minutes between supersetted pairs.' },
    { kind: 'typein', id: 'av-t10', tags: ['acute-variables', 'phase5'], prompt: 'Phase 5 power-exercise load as % of 1RM (the light/explosive half of the superset)?', accept: ['30-45%', '30-45'], hints: ['Light enough to move fast.', '__-__%'], explanation: 'Phase 5 power movements use 30–45% 1RM (or ~10% bodyweight for medicine ball work).' },
    { kind: 'typein', id: 'av-t11', tags: ['acute-variables', 'phase3'], prompt: 'Phase 3 (Muscular Development) set range?', accept: ['3-5'], hints: ['Higher than Phase 1.', '_-_'], explanation: 'Phase 3 uses 3–5 sets.' },
    { kind: 'typein', id: 'av-t12', tags: ['acute-variables', 'phase4'], prompt: 'Phase 4 set range?', accept: ['4-6'], hints: ['The highest set range in the OPT model.', '_-_'], explanation: 'Phase 4 uses 4–6 sets.' },
    { kind: 'typein', id: 'av-t13', tags: ['acute-variables', 'tempo'], prompt: 'Phase 1 tempo notation?', accept: ['4/2/1', '421'], hints: ['Slow eccentric, pause, controlled lift.', '_/_/_'], explanation: 'Phase 1 uses a 4/2/1 tempo — 4s eccentric, 2s isometric, 1s concentric.' },
    { kind: 'typein', id: 'av-t14', tags: ['acute-variables', 'tempo'], prompt: 'Phase 3 tempo notation?', accept: ['2/0/2', '202'], hints: ['No pause at the bottom.', '_/_/_'], explanation: 'Phase 3 uses 2/0/2 — a moderate, controlled tempo with no isometric hold.' },
    { kind: 'typein', id: 'av-t15', tags: ['acute-variables', 'tempo'], prompt: 'In tempo notation, which phase of the rep does the FIRST number represent?', accept: ['eccentric'], hints: ['The lowering portion.', 'E_________'], explanation: 'Tempo reads eccentric / isometric / concentric, so the first number is the eccentric (lowering) phase.' },
    {
      kind: 'scenario', id: 'av-s1', tags: ['acute-variables', 'phase2'],
      story: 'A client in Phase 2 (Strength Endurance) performs a barbell bench press immediately followed by a stability ball push-up, with no rest between the two.',
      question: 'What is this programming structure called, and is it correct for this phase?',
      options: [
        'A superset — and yes, it is the defining structure of Phase 2',
        'A drop set — and no, this belongs in Phase 3',
        'Peripheral heart action — and no, this belongs in Phase 1',
        'A circuit — and no, this belongs in Phase 5',
      ],
      answer: 0,
      explanation: 'Phase 2 is defined by supersetting a traditional strength exercise with a stabilization exercise for the same muscle group, back to back with no rest.',
      whyWrong: ['', 'A drop set reduces load within a set; that is not what is described here.', 'Peripheral heart action alternates upper and lower body across a circuit, not a strength/stabilization pair.', 'A circuit moves through many exercises in sequence, not a two-exercise pairing.'],
    },
    {
      kind: 'scenario', id: 'av-s2', tags: ['acute-variables', 'phase1'],
      story: 'A deconditioned client is in Phase 1. The trainer programs 10 reps at 80% of 1RM with 2 minutes rest.',
      question: 'Which acute variables are incorrect for Phase 1?',
      options: [
        'Only the intensity is wrong',
        'Only the rest is wrong',
        'Reps, intensity, and rest are all outside Phase 1 ranges',
        'Everything is correct for Phase 1',
      ],
      answer: 2,
      explanation: 'Phase 1 calls for 12–20 reps at 50–70% 1RM with 0–90 seconds rest. Ten reps is too few, 80% is too heavy, and 2 minutes is too long.',
      whyWrong: ['Intensity is wrong, but so are reps and rest.', 'Rest is wrong, but so are reps and intensity.', '', 'All three of these variables fall outside the Phase 1 prescription.'],
    },
    {
      kind: 'mcq', id: 'av-m2', tags: ['acute-variables', 'tempo'], source: 'original',
      prompt: 'A tempo of 4/2/1 means which of the following?',
      options: [
        '4s concentric, 2s isometric, 1s eccentric',
        '4s eccentric, 2s isometric, 1s concentric',
        '4s isometric, 2s eccentric, 1s concentric',
        '4 reps, 2 sets, 1 minute rest',
      ],
      answer: 1,
      explanation: 'Tempo is always written eccentric / isometric / concentric, so 4/2/1 is a 4-second lowering, 2-second pause, 1-second lift.',
      whyWrong: ['This reverses the order — eccentric comes first, not concentric.', '', 'Isometric is the middle number, not the first.', 'Tempo notation describes rep speed, not reps/sets/rest.'],
    },
    {
      kind: 'mcq', id: 'av-m3', tags: ['acute-variables', 'phase5'], source: 'original',
      prompt: 'Which best describes the Phase 5 (Power) superset structure?',
      options: [
        'A heavy strength exercise paired with an explosive exercise of similar joint mechanics',
        'Two stabilization exercises performed back to back',
        'A strength exercise paired with a stabilization exercise',
        'Three exercises for the same muscle with no rest',
      ],
      answer: 0,
      explanation: 'Phase 5 pairs a heavy strength lift (85–100% 1RM) with a biomechanically similar explosive movement (30–45% 1RM or ~10% BW).',
      whyWrong: ['', 'Stabilization pairing is not the Phase 5 structure.', 'Strength-plus-stabilization pairing describes Phase 2, not Phase 5.', 'That describes a tri-set or giant set, not the Phase 5 structure.'],
    },
    {
      kind: 'mcq', id: 'av-m4', tags: ['acute-variables'], source: 'original',
      prompt: 'Which acute variable is manipulated to primarily drive a hypertrophy (Muscular Development) adaptation?',
      options: [
        'Very long rest with 1–5 reps',
        'Moderate-to-heavy load (75–85%) with 6–12 reps and 3–5 sets',
        'Light load with 20+ reps and no rest',
        'Explosive tempo at 30% 1RM',
      ],
      answer: 1,
      explanation: 'Phase 3 (Muscular Development) uses 75–85% 1RM for 6–12 reps across 3–5 sets with 0–60s rest — the classic hypertrophy prescription.',
      whyWrong: ['That describes Phase 4 maximal strength, not hypertrophy.', '', 'That is closer to Phase 1 endurance work than hypertrophy.', 'That describes Phase 5 power work, not hypertrophy.'],
    },
    {
      kind: 'order', id: 'av-o1', tags: ['acute-variables'],
      prompt: 'Order these phases from LIGHTEST to HEAVIEST training intensity (% 1RM).',
      correctOrder: ['Phase 1 (50–70%)', 'Phase 2 (70–80%)', 'Phase 3 (75–85%)', 'Phase 4 (85–100%)'],
      explanation: 'Intensity climbs steadily: Phase 1 (50–70%) → Phase 2 (70–80%) → Phase 3 (75–85%) → Phase 4 (85–100%).',
    },
    {
      kind: 'match', id: 'av-match1', tags: ['acute-variables', 'rest'],
      prompt: 'Match each phase to its rest interval.',
      pairs: [
        ['Phase 1 – Stabilization Endurance', '0–90 seconds'],
        ['Phase 2 – Strength Endurance', '0–60 seconds'],
        ['Phase 4 – Maximal Strength', '3–5 minutes'],
      ],
      explanation: 'Rest lengthens as load increases: 0–90s in Phase 1, 0–60s in Phases 2–3, and 3–5 minutes in Phases 4–5.',
    },
    {
      kind: 'match', id: 'av-match2', tags: ['acute-variables', 'reps'],
      prompt: 'Match each phase to its repetition range.',
      pairs: [
        ['Phase 1', '12–20 reps'],
        ['Phase 2', '8–12 reps'],
        ['Phase 3', '6–12 reps'],
        ['Phase 4', '1–5 reps'],
      ],
      explanation: 'Reps fall as intensity rises: 12–20 → 8–12 → 6–12 → 1–5.',
    },
  ],
}
