import type { Module } from '../../types/content'

export const behaviorChange: Module = {
  id: 'd5-behavior-change',
  domainId: 'd5',
  title: 'Stages of Change & Communication',
  estMinutes: 25,
  lessons: [
    {
      id: 'bc-l1',
      title: 'The Transtheoretical Model (Stages of Change)',
      plain: `People don't just flip a switch from "couch potato" to "gym regular" — they move through predictable stages. Someone who's never thought about exercising is in a totally different headspace than someone who's already been going for 3 months. Your job as a trainer is to meet them exactly where they are, not where you wish they were.`,
      nasm: `The Transtheoretical Model of Behavior Change identifies five stages a client moves through when adopting a new behavior: Precontemplation, Contemplation, Preparation, Action, and Maintenance. Trainers should tailor communication strategies to the client's current stage to maximize adherence.`,
      memoryHook: `"Pre-Con-Prep-Act-Maintain" — say it like a chant. Each stage is defined by a timeframe: 6 months away, within 6 months, within 30 days, doing it <6 months, doing it >6 months.`,
      mustMemorise: [
        'Precontemplation = no intent to change in the next 6 months',
        'Contemplation = intends to change within 6 months',
        'Preparation = intends to act within 30 days, small steps possible',
        'Action = changed behavior for less than 6 months',
        'Maintenance = sustained behavior for more than 6 months',
      ],
    },
    {
      id: 'bc-l2',
      title: 'OARS: the toolkit of motivational interviewing',
      plain: `OARS is a simple toolkit for talking to clients in a way that gets them to convince *themselves* to change, instead of you lecturing them. Open-ended questions get people talking. Affirmations point out real strengths. Reflective listening shows you actually heard them. Summaries tie it all together.`,
      nasm: `OARS represents the four core communication techniques of Motivational Interviewing: Open-ended questions, Affirmations, Reflective listening, and Summaries. These techniques help elicit "change talk" from the client and build self-efficacy.`,
      mustMemorise: ['OARS = Open-ended questions, Affirmations, Reflective listening, Summaries'],
    },
  ],
  items: [
    {
      kind: 'typein', id: 'bc-t1', tags: ['behavior-change', 'stages'],
      prompt: 'Which stage of change involves no intention to change in the next 6 months?',
      accept: ['precontemplation'],
      hints: ['"Pre" means before even thinking about it.', 'P____________'],
      explanation: 'Precontemplation: the client has no intention of changing within 6 months.',
    },
    {
      kind: 'typein', id: 'bc-t2', tags: ['behavior-change', 'stages'],
      prompt: 'Which stage of change involves intending to act within 30 days?',
      accept: ['preparation'],
      hints: ['They are getting ready.', 'P___________'],
      explanation: 'Preparation: intends to take action within 30 days.',
    },
    {
      kind: 'typein', id: 'bc-t3', tags: ['behavior-change', 'stages'],
      prompt: 'Which stage of change means the client has sustained the new behavior for more than 6 months?',
      accept: ['maintenance'],
      hints: ['They are keeping it going.', 'M___________'],
      explanation: 'Maintenance: behavior sustained for more than 6 months.',
    },
    {
      kind: 'typein', id: 'bc-t4', tags: ['behavior-change', 'communication'],
      prompt: 'What does the "O" in OARS stand for?',
      accept: ['open-ended questions', 'open ended questions'],
      hints: ['Questions that can\'t be answered with yes/no.', 'O___ E_____ Q_________'],
      explanation: 'O = Open-ended questions.',
    },
    {
      kind: 'typein', id: 'bc-t5', tags: ['behavior-change', 'communication'],
      prompt: 'What does the "R" in OARS stand for?',
      accept: ['reflective listening'],
      hints: ['Mirroring back what the client said/felt.', 'R_________ L________'],
      explanation: 'R = Reflective listening.',
    },
    {
      kind: 'mcq', id: 'bc-m1', tags: ['behavior-change', 'stages'], source: 'original',
      prompt: 'A client says: "I bought running shoes last week and I\'m starting a couch-to-5K plan this Monday." What stage of change are they in?',
      options: ['Precontemplation', 'Contemplation', 'Preparation', 'Maintenance'],
      answer: 2,
      explanation: 'Buying equipment and planning to start within days/weeks is classic Preparation-stage behavior.',
      whyWrong: ['Precontemplation clients show no intent to change.', 'Contemplation clients are still weighing whether to change, not yet taking concrete steps.', '', 'Maintenance requires more than 6 months of sustained behavior.'],
    },
    {
      kind: 'match', id: 'bc-match1', tags: ['behavior-change', 'oars'],
      prompt: 'Match each OARS technique to its example.',
      pairs: [
        ['Open-ended question', '"What motivates you to keep coming back each week?"'],
        ['Affirmation', '"You showed real discipline sticking to your plan this week."'],
        ['Reflective listening', '"It sounds like you\'re proud of the progress, even if the scale hasn\'t moved."'],
        ['Summary', '"So this month you worked out 3x/week and improved your sleep — great progress."'],
      ],
      explanation: 'OARS = Open-ended questions, Affirmations, Reflective listening, Summaries.',
    },
    { kind: 'typein', id: 'bc-t6', tags: ['behavior-change', 'stages'], prompt: 'Which stage of change involves intending to change within the next 6 months (but not yet acting)?', accept: ['contemplation'], hints: ['Thinking about it.', 'C____________'], explanation: 'Contemplation: intends to change within 6 months but has not yet taken action.' },
    { kind: 'typein', id: 'bc-t7', tags: ['behavior-change', 'stages'], prompt: 'Which stage of change describes someone who has been exercising for under 6 months?', accept: ['action'], hints: ['They are doing it now.', 'A_____'], explanation: 'Action: the behavior has been changed for less than 6 months.' },
    { kind: 'typein', id: 'bc-t8', tags: ['behavior-change', 'communication'], prompt: 'What does the "A" in OARS stand for?', accept: ['affirmations', 'affirmation'], hints: ['Recognizing genuine strengths.', 'A___________'], explanation: 'A = Affirmations — statements recognizing the client\'s genuine strengths and efforts.' },
    { kind: 'typein', id: 'bc-t9', tags: ['behavior-change', 'communication'], prompt: 'What does the "S" in OARS stand for?', accept: ['summaries', 'summary'], hints: ['Tying it all together.', 'S________'], explanation: 'S = Summaries — pulling together what the client has said.' },
    { kind: 'typein', id: 'bc-t10', tags: ['behavior-change', 'goals'], prompt: 'A goal describing a behavior to repeat (e.g. "run 3x per week") is what kind of goal?', accept: ['process goal', 'process'], hints: ['About the doing, not the result.', 'P______ goal'], explanation: 'A process goal describes the behavior itself; an outcome goal describes a specific result.' },
    { kind: 'typein', id: 'bc-t11', tags: ['behavior-change', 'goals'], prompt: 'What does the "M" in SMART goals stand for?', accept: ['measurable'], hints: ['You can quantify it.', 'M_________'], explanation: 'SMART = Specific, Measurable, Attainable, Realistic, Timely.' },
    { kind: 'typein', id: 'bc-t12', tags: ['behavior-change', 'support'], prompt: 'Which type of social support provides knowledge, advice, or information?', accept: ['informational support', 'informational'], hints: ['About information.', 'I____________ support'], explanation: 'Informational support provides advice, knowledge, or guidance.' },
    { kind: 'typein', id: 'bc-t13', tags: ['behavior-change', 'support'], prompt: 'Which type of social support provides tangible/practical help such as equipment or a ride?', accept: ['instrumental support', 'instrumental'], hints: ['Practical, concrete help.', 'I___________ support'], explanation: 'Instrumental support provides tangible, practical assistance.' },
    { kind: 'typein', id: 'bc-t14', tags: ['behavior-change'], prompt: 'What term describes a person\'s belief in their own ability to succeed at a behavior?', accept: ['self-efficacy', 'self efficacy'], hints: ['Hyphenated, starts with "self".', 'S___-E_______'], explanation: 'Self-efficacy is the belief in one\'s own capability to perform a behavior successfully.' },
    { kind: 'typein', id: 'bc-t15', tags: ['behavior-change'], prompt: 'Motivation that comes from internal enjoyment rather than external reward is called what?', accept: ['intrinsic motivation', 'intrinsic'], hints: ['From within.', 'I________ motivation'], explanation: 'Intrinsic motivation comes from internal satisfaction; extrinsic motivation comes from external rewards.' },
    {
      kind: 'scenario', id: 'bc-s1', tags: ['behavior-change', 'stages'],
      story: 'A client says: "Honestly, I think my weight is fine and I don\'t really see the point of a gym membership. My wife booked this session."',
      question: 'Which stage of change are they in, and what is the best approach?',
      options: [
        'Precontemplation — build rapport and gently raise awareness without pressuring commitment',
        'Contemplation — help them weigh pros and cons of starting',
        'Preparation — help them set a SMART goal for next week',
        'Action — reinforce their progress and prevent relapse',
      ],
      answer: 0,
      explanation: 'No intent to change and attending only due to someone else indicates precontemplation. The approach is rapport and gentle awareness-building, not pushing for commitment.',
      whyWrong: ['', 'Contemplation clients recognize a reason to change; this client does not yet.', 'Preparation clients intend to act within 30 days; this client has no intent.', 'Action requires the client to already be exercising.'],
    },
    {
      kind: 'scenario', id: 'bc-s2', tags: ['behavior-change', 'stages'],
      story: 'A client says: "I\'ve been going to the gym consistently for about 14 months now. It\'s just part of my routine at this point."',
      question: 'Which stage of change are they in?',
      options: ['Action', 'Preparation', 'Maintenance', 'Contemplation'],
      answer: 2,
      explanation: 'Sustaining the behavior for more than 6 months places the client in maintenance.',
      whyWrong: ['Action applies to behavior change sustained for less than 6 months.', 'Preparation is the stage before starting.', '', 'Contemplation is thinking about changing, not doing it for over a year.'],
    },
    {
      kind: 'scenario', id: 'bc-s3', tags: ['behavior-change', 'support'],
      story: 'A client who has trained consistently for a year asks the trainer for ideas about more efficient ways to work out at home.',
      question: 'What type of social support are they seeking?',
      options: ['Emotional support', 'Informational support', 'Companionship support', 'Instrumental support'],
      answer: 1,
      explanation: 'They are asking for knowledge and advice, which is informational support.',
      whyWrong: ['Emotional support is encouragement and empathy, not advice.', '', 'Companionship support is shared activity or company.', 'Instrumental support is tangible help such as equipment or transport.'],
    },
    {
      kind: 'mcq', id: 'bc-m2', tags: ['behavior-change', 'goals'], source: 'original',
      prompt: 'Which of the following is a PROCESS goal rather than an outcome goal?',
      options: ['Lose 10 pounds', 'Squat 100 kg', 'Strength train 3 times per week', 'Run a sub-25-minute 5K'],
      answer: 2,
      explanation: 'A process goal describes the behavior to be repeated; the others describe specific measurable results (outcome goals).',
      whyWrong: ['This is a specific result — an outcome goal.', 'This is a specific performance result — an outcome goal.', '', 'This is a specific performance result — an outcome goal.'],
    },
    {
      kind: 'mcq', id: 'bc-m3', tags: ['behavior-change'], source: 'original',
      prompt: 'Intentions predict behavior, but what has been shown to actually help translate intention into action?',
      options: ['Subjective norms', 'Outcome expectations', 'Planning (implementation intentions)', 'Higher outcome goals'],
      answer: 2,
      explanation: 'Concrete planning — deciding specifically when, where, and how — bridges the gap between intending to act and actually acting.',
      whyWrong: ['Subjective norms influence whether an intention forms, not whether it converts to action.', 'Outcome expectations shape motivation to intend, not the intention-action gap.', '', 'Setting bigger goals does not itself close the intention-action gap.'],
    },
    {
      kind: 'match', id: 'bc-match2', tags: ['behavior-change', 'stages'],
      prompt: 'Match each stage of change to its defining timeframe.',
      pairs: [
        ['Precontemplation', 'No intent to change within 6 months'],
        ['Contemplation', 'Intends to change within 6 months'],
        ['Preparation', 'Intends to act within 30 days'],
        ['Action', 'Has changed behavior for less than 6 months'],
        ['Maintenance', 'Has sustained the change for more than 6 months'],
      ],
      explanation: 'Each stage is defined by a specific timeframe — the most reliable way to identify the stage from a client quote.',
    },
    {
      kind: 'match', id: 'bc-match3', tags: ['behavior-change', 'support'],
      prompt: 'Match each social support type to its description.',
      pairs: [
        ['Informational', 'Advice, knowledge, guidance'],
        ['Emotional', 'Encouragement and empathy'],
        ['Instrumental', 'Tangible help (equipment, transport)'],
        ['Companionship', 'Shared activity and company'],
      ],
      explanation: 'Social support questions are usually scenario-based — identify what the client is actually asking for.',
    },
    { kind: 'typein', id: 'bc-t16', tags: ['behavior-change'], prompt: 'Motivation driven by external rewards (money, praise, trophies) is called what?', accept: ['extrinsic motivation', 'extrinsic'], hints: ['From outside.', 'E________ motivation'], explanation: 'Extrinsic motivation comes from external rewards, unlike intrinsic motivation.' },
    { kind: 'typein', id: 'bc-t17', tags: ['behavior-change'], prompt: 'What is the name of the model containing the five stages of change?', accept: ['transtheoretical model', 'transtheoretical'], hints: ['Long word starting with "trans".', 'T______________ Model'], explanation: 'The Transtheoretical Model of Behavior Change contains the five stages.' },
  ],
}
