import type { Module } from '../../types/content'

export const endocrineCardiorespBioenergetics: Module = {
  id: 'd1-endocrine-cardioresp-bioenergetics',
  domainId: 'd1',
  title: 'Endocrine, Cardiorespiratory & Bioenergetics',
  estMinutes: 40,
  lessons: [
    {
      id: 'ecb-l1',
      title: 'Key hormones a trainer should recognize',
      plain: `A handful of hormones matter most for training. **Insulin** lowers blood sugar by moving glucose into cells; **glucagon** does the opposite, raising blood sugar. **Cortisol** is the stress hormone — a little is normal, but if it stays chronically elevated (baseline, not just during a hard workout), that's a red flag for overtraining. **Testosterone** builds muscle and declines with age, and overall health affects how fast it declines. **Growth hormone** also supports tissue repair and growth. **Catecholamines** (adrenaline/noradrenaline) drive the fight-or-flight energy surge. One useful fact: eccentric-focused training tends to boost anabolic (muscle-building) hormone response more than pure concentric work.`,
      nasm: `Insulin decreases blood glucose by facilitating cellular uptake; glucagon increases blood glucose by stimulating glycogen breakdown. Cortisol is a catabolic stress hormone; chronically elevated baseline cortisol is associated with overtraining syndrome. Testosterone is an anabolic hormone that declines with age, the rate of which may be influenced by overall health status. Growth hormone supports tissue growth and repair. Catecholamines (epinephrine and norepinephrine) mediate the sympathetic fight-or-flight response. Eccentric-emphasis resistance training has been shown to increase anabolic hormone stimulation.`,
      mustMemorise: [
        'Insulin lowers blood glucose; glucagon raises blood glucose',
        'Chronically elevated baseline cortisol may indicate overtraining',
        'Testosterone declines with age; overall health affects the rate',
        'Eccentric-focused training increases anabolic hormone stimulation',
      ],
    },
    {
      id: 'ecb-l2',
      title: 'The heart and blood flow',
      plain: `Blood takes a loop: the **right atrium** receives used (deoxygenated) blood coming back from the body, sends it to the right ventricle, out to the lungs to pick up oxygen, then the **left atrium** receives that freshly oxygenated blood from the lungs, passes it to the left ventricle, which pumps it out to the whole body. The heart's natural pacemaker is the **SA node**. Two key numbers: **stroke volume** (blood pumped per single beat = end-diastolic volume minus end-systolic volume) and **cardiac output** (blood pumped per minute = heart rate × stroke volume). The heart itself sits in a central chest cavity called the **mediastinum**.`,
      nasm: `The right atrium receives deoxygenated blood from the body via the venae cavae; the left atrium receives oxygenated blood from the lungs via the pulmonary veins. The sinoatrial (SA) node is the heart's primary pacemaker, initiating each heartbeat. Stroke volume is the volume of blood ejected per heartbeat (end-diastolic volume minus end-systolic volume). Cardiac output is the volume of blood pumped per minute, calculated as heart rate multiplied by stroke volume. The heart resides within the mediastinum, the central compartment of the thoracic cavity.`,
      mustMemorise: [
        'Right atrium receives deoxygenated blood from the body',
        'Left atrium receives oxygenated blood from the lungs',
        'SA node = the heart\'s natural pacemaker',
        'Stroke volume = end-diastolic volume − end-systolic volume',
        'Cardiac output = heart rate × stroke volume',
        'Mediastinum = the central chest cavity containing the heart',
      ],
    },
    {
      id: 'ecb-l3',
      title: 'Breathing mechanics — normal vs. abnormal',
      plain: `Healthy breathing is slow, diaphragmatic (the belly expands), and uses the diaphragm as the main mover. Dysfunctional breathing looks the opposite: shallow, rapid breaths from the upper chest, over-recruiting neck muscles like the sternocleidomastoid and scalenes that are only supposed to help during heavy exertion, not every resting breath. Over time this pattern contributes to neck/shoulder tightness and posture issues.`,
      nasm: `Optimal breathing mechanics involve diaphragmatic, slow, controlled breaths with abdominal expansion. Dysfunctional breathing patterns are characterized by shallow, rapid chest breathing with compensatory overuse of accessory muscles such as the sternocleidomastoid and scalenes, which can contribute to upper-body postural dysfunction over time.`,
      mustMemorise: ['Abnormal breathing = shallow, rapid, chest-dominant, overusing SCM/scalenes'],
    },
    {
      id: 'ecb-l4',
      title: 'The three energy systems',
      plain: `Your body makes fuel (ATP) three different ways depending on how long and how hard you're working. **ATP-PC system**: your fastest, most powerful, but shortest-lasting fuel tank — good for about 0-10 seconds (think: a 1-rep max lift or a short sprint). **Glycolysis**: kicks in next, using carbs, lasting roughly 30 seconds to 2 minutes (think: a hard 400m run). **Oxidative system**: your slow-and-steady, long-lasting system using oxygen to burn carbs and fat, kicking in for anything over about 2 minutes (think: a long run). More mitochondria (the cell's energy factories) means better fat-burning capacity. After hard exercise, your body keeps burning extra calories to recover — this is called **EPOC** (excess post-exercise oxygen consumption).`,
      nasm: `The ATP-PC system predominates during high-intensity efforts lasting approximately 0–10 seconds. The glycolytic system predominates during efforts lasting roughly 30 seconds to 2 minutes. The oxidative system predominates during efforts lasting longer than approximately 2 minutes, utilizing both carbohydrate and fat as fuel. A greater mitochondrial density improves the capacity to oxidize fat. Excess post-exercise oxygen consumption (EPOC) refers to the elevated oxygen consumption, and associated caloric expenditure, that persists after exercise as the body returns to a resting state.`,
      mustMemorise: [
        'ATP-PC system: ~0–10 seconds, highest power',
        'Glycolysis: ~30 seconds–2 minutes',
        'Oxidative system: >2 minutes, uses fat + carbohydrate',
        'More mitochondria = better fat oxidation',
        'EPOC = excess post-exercise oxygen consumption',
      ],
    },
    {
      id: 'ecb-l5',
      title: 'From food to fuel: acetyl CoA and the citric acid cycle',
      plain: `No matter whether you eat carbs, fat, or protein, your body has to convert all of them into the same universal "entry ticket" molecule — **acetyl CoA** — before they can be burned for energy in the citric acid cycle (also called the Krebs cycle). This happens inside the mitochondria.`,
      nasm: `Carbohydrates, fats, and proteins must each be converted to acetyl coenzyme A (acetyl CoA) before entering the citric acid cycle (Krebs cycle) within the mitochondria, where the bulk of ATP is produced via oxidative phosphorylation.`,
      mustMemorise: ['Carbs, fat, and protein all convert to acetyl CoA before entering the citric acid cycle'],
    },
    {
      id: 'ecb-l6',
      title: 'Total energy expenditure: what actually burns the most calories',
      plain: `Total daily calorie burn has three pieces. The biggest piece by far — for almost everyone — is **resting metabolic rate (RMR)**: the calories your body burns just existing (breathing, pumping blood, keeping organs running). Next is the **thermic effect of activity** (exercise plus everyday movement like fidgeting or walking around, aka NEAT). Smallest piece is the **thermic effect of food (TEF)** — the calories spent digesting what you eat.`,
      nasm: `Total daily energy expenditure comprises resting metabolic rate (RMR), the largest contributor for most individuals; the thermic effect of activity (exercise and non-exercise activity thermogenesis); and the thermic effect of food (TEF), the smallest contributor.`,
      mustMemorise: ['RMR is the largest component of total daily energy expenditure', 'TEF (thermic effect of food) is the smallest component'],
    },
  ],
  items: [
    { kind: 'typein', id: 'ecb-t1', tags: ['endocrine'], prompt: 'Which hormone lowers blood glucose by moving it into cells?', accept: ['insulin'], hints: ['Diabetics may inject this.', 'I______'], explanation: 'Insulin lowers blood glucose by facilitating cellular glucose uptake.' },
    { kind: 'typein', id: 'ecb-t2', tags: ['endocrine'], prompt: 'Which hormone raises blood glucose?', accept: ['glucagon'], hints: ['Opposite of insulin.', 'G_______'], explanation: 'Glucagon raises blood glucose by stimulating glycogen breakdown.' },
    { kind: 'typein', id: 'ecb-t3', tags: ['endocrine'], prompt: 'Which hormone, if chronically elevated at baseline, may indicate overtraining?', accept: ['cortisol'], hints: ['The stress hormone.', 'C________'], explanation: 'Chronically elevated baseline cortisol is a marker of overtraining.' },
    { kind: 'typein', id: 'ecb-t4', tags: ['cardio'], prompt: 'Which heart chamber receives oxygenated blood from the lungs?', accept: ['left atrium'], hints: ['Left side, top chamber.', 'L___ A_____'], explanation: 'The left atrium receives oxygenated blood from the lungs via the pulmonary veins.' },
    { kind: 'typein', id: 'ecb-t5', tags: ['cardio'], prompt: 'What is the heart\'s natural pacemaker called?', accept: ['sa node', 'sinoatrial node'], hints: ['Two letters.', 'SA N___'], explanation: 'The SA (sinoatrial) node is the heart\'s natural pacemaker.' },
    { kind: 'typein', id: 'ecb-t6', tags: ['cardio'], prompt: 'What is the formula for cardiac output?', accept: ['heart rate x stroke volume', 'hr x sv', 'heart rate times stroke volume'], hints: ['Two variables multiplied.', 'H_ × S_'], explanation: 'Cardiac output = heart rate × stroke volume.' },
    { kind: 'typein', id: 'ecb-t7', tags: ['cardio'], prompt: 'What central chest cavity contains the heart?', accept: ['mediastinum'], hints: ['Not "ventricle" or "atrium."', 'M__________'], explanation: 'The mediastinum is the chest cavity containing the heart.' },
    { kind: 'typein', id: 'ecb-t8', tags: ['bioenergetics'], prompt: 'Which energy system dominates for the first 0-10 seconds of an all-out effort?', accept: ['atp-pc', 'atp pc system', 'phosphagen system'], hints: ['Shortest, most powerful system.', 'ATP-__'], explanation: 'The ATP-PC system dominates for about 0-10 seconds of maximal effort.' },
    { kind: 'typein', id: 'ecb-t9', tags: ['bioenergetics'], prompt: 'Which energy system dominates roughly 30 seconds to 2 minutes into an effort?', accept: ['glycolysis', 'glycolytic system'], hints: ['Uses carbohydrate.', 'G_________'], explanation: 'Glycolysis dominates for efforts of roughly 30 seconds to 2 minutes.' },
    { kind: 'typein', id: 'ecb-t10', tags: ['bioenergetics'], prompt: 'Which energy system dominates for efforts longer than about 2 minutes?', accept: ['oxidative', 'oxidative system'], hints: ['Uses oxygen, fat and carbs.', 'O________'], explanation: 'The oxidative system dominates for efforts longer than about 2 minutes.' },
    { kind: 'typein', id: 'ecb-t11', tags: ['bioenergetics'], prompt: 'What is the name for extra calories burned after exercise as the body recovers?', accept: ['epoc', 'excess post-exercise oxygen consumption'], hints: ['An acronym.', 'E____'], explanation: 'EPOC = excess post-exercise oxygen consumption.' },
    { kind: 'typein', id: 'ecb-t12', tags: ['bioenergetics'], prompt: 'What common molecule must carbohydrate, fat, and protein all convert into before entering the citric acid cycle?', accept: ['acetyl coa', 'acetyl-coa'], hints: ['Two words, hyphenated.', 'A_____ CoA'], explanation: 'Acetyl CoA is the shared entry molecule into the citric acid cycle.' },
    { kind: 'typein', id: 'ecb-t13', tags: ['bioenergetics'], prompt: 'Which component of total daily energy expenditure is the largest for most people?', accept: ['resting metabolic rate', 'rmr', 'resting metabolism'], hints: ['Calories burned just existing.', 'R_____ M________ R___'], explanation: 'Resting metabolic rate (RMR) is the largest component of total daily energy expenditure.' },
    { kind: 'typein', id: 'ecb-t14', tags: ['breathing'], prompt: 'Name one accessory neck muscle overused during dysfunctional, shallow breathing.', accept: ['sternocleidomastoid', 'scm', 'scalenes'], hints: ['Runs along the side of the neck.', 'S_____________'], explanation: 'The sternocleidomastoid and scalenes are overused during shallow, chest-dominant breathing.' },
    {
      kind: 'mcq', id: 'ecb-m1', tags: ['cardio'], source: 'original',
      prompt: 'What is stroke volume?',
      options: ['Heart rate × cardiac output', 'End-diastolic volume minus end-systolic volume', 'The volume of blood pumped per minute', 'The resting heart rate'],
      answer: 1,
      explanation: 'Stroke volume is the amount of blood ejected per beat: end-diastolic volume minus end-systolic volume.',
      whyWrong: ['This formula does not define stroke volume.', '', 'This describes cardiac output, not stroke volume.', 'Resting heart rate is a rate, not a volume.'],
    },
    {
      kind: 'mcq', id: 'ecb-m2', tags: ['bioenergetics'], source: 'original',
      prompt: 'A client is doing a 1-minute all-out row sprint. Which energy system is primarily fueling this effort?',
      options: ['ATP-PC system', 'Glycolytic system', 'Oxidative system', 'None — muscles use only stored ATP'],
      answer: 1,
      explanation: 'A 1-minute maximal effort falls in the glycolytic system\'s dominant window (roughly 30 seconds to 2 minutes).',
      whyWrong: ['ATP-PC dominates only the first ~10 seconds, not a full minute.', '', 'The oxidative system dominates efforts longer than ~2 minutes, not 1 minute at high intensity.', 'All 3 systems contribute some ATP throughout, but glycolysis dominates at this duration/intensity.'],
    },
    {
      kind: 'match', id: 'ecb-match1', tags: ['bioenergetics'],
      prompt: 'Match each energy system to its dominant duration window.',
      pairs: [
        ['ATP-PC system', '~0–10 seconds'],
        ['Glycolytic system', '~30 seconds–2 minutes'],
        ['Oxidative system', '>2 minutes'],
      ],
      explanation: 'ATP-PC (0-10s) → Glycolysis (30s-2min) → Oxidative (>2min), roughly in order of how long the effort lasts.',
    },
    { kind: 'typein', id: 'ecb-t15', tags: ['cardio'], prompt: 'Which heart chamber receives DEOXYGENATED blood returning from the body?', accept: ['right atrium'], hints: ['Right side, top chamber.', 'R____ A_____'], explanation: 'The right atrium receives deoxygenated blood from the body via the venae cavae.' },
    { kind: 'typein', id: 'ecb-t16', tags: ['cardio'], prompt: 'What is stroke volume the difference between?', accept: ['end-diastolic and end-systolic volume', 'edv and esv', 'end diastolic volume and end systolic volume'], hints: ['Two ventricular volumes.', 'E__-D________ and E__-S______ volume'], explanation: 'Stroke volume = end-diastolic volume − end-systolic volume.' },
    { kind: 'typein', id: 'ecb-t17', tags: ['endocrine'], prompt: 'Which hormone declines with age in men, with the rate influenced by overall health?', accept: ['testosterone'], hints: ['The primary male anabolic hormone.', 'T___________'], explanation: 'Testosterone declines with age; overall health affects the degree of that change.' },
    { kind: 'typein', id: 'ecb-t18', tags: ['endocrine'], prompt: 'Which type of muscle action, when appropriately loaded, increases anabolic hormone stimulation?', accept: ['eccentric'], hints: ['The lowering portion.', 'E_________'], explanation: 'Appropriately loaded eccentric training increases anabolic hormone stimulation.' },
    { kind: 'typein', id: 'ecb-t19', tags: ['bioenergetics'], prompt: 'Which cellular structure is responsible for producing energy from nutrients?', accept: ['mitochondria', 'mitochondrion'], hints: ['The cell\'s powerhouse.', 'M___________'], explanation: 'Mitochondria convert nutrients into usable cellular energy (ATP).' },
    { kind: 'typein', id: 'ecb-t20', tags: ['endocrine'], prompt: 'Which hormones (adrenaline/noradrenaline) drive the fight-or-flight energy surge?', accept: ['catecholamines', 'epinephrine and norepinephrine'], hints: ['A category name.', 'C_____________'], explanation: 'Catecholamines (epinephrine and norepinephrine) mediate the sympathetic fight-or-flight response.' },
    {
      kind: 'scenario', id: 'ecb-s1', tags: ['endocrine', 'overtraining'],
      story: 'A client has been training twice daily for 10 weeks with minimal rest days. Bloodwork ordered by their physician shows chronically elevated baseline levels of one hormone.',
      question: 'Which hormone being elevated at baseline would most suggest overtraining?',
      options: ['Testosterone', 'Cortisol', 'Insulin', 'Growth hormone'],
      answer: 1,
      explanation: 'Chronically elevated baseline cortisol — a catabolic stress hormone — is a recognized marker of overtraining syndrome.',
      whyWrong: ['Testosterone (anabolic) is typically suppressed, not elevated, with overtraining.', '', 'Insulin relates to blood glucose regulation, not overtraining status.', 'Growth hormone is not the flagged overtraining marker in this context.'],
    },
    {
      kind: 'scenario', id: 'ecb-s2', tags: ['bioenergetics'],
      story: 'Two clients perform the same 45-minute steady-state jog. Client A has trained aerobically for years; Client B is new to exercise. Client A burns proportionally more fat during the session.',
      question: 'What best explains Client A\'s greater fat oxidation?',
      options: [
        'Client A has more stored body fat available',
        'Client A has greater mitochondrial density in their muscle',
        'Client A has more muscle glycogen stored',
        'Client A delivers less oxygen to the muscle',
      ],
      answer: 1,
      explanation: 'Fat oxidation occurs in the mitochondria, so a trained client with greater mitochondrial density has a higher capacity to oxidize fat.',
      whyWrong: ['Having more stored fat does not improve the ability to oxidize it.', '', 'Greater glycogen storage relates to carbohydrate fuel availability, not fat-oxidizing capacity.', 'Fat oxidation is aerobic; less oxygen delivery would impair it.'],
    },
    {
      kind: 'scenario', id: 'ecb-s3', tags: ['bioenergetics'],
      story: 'An athlete performs a single maximal-effort 8-second sprint from a standing start.',
      question: 'Which energy system predominantly fuels this effort?',
      options: ['Oxidative system', 'Glycolytic system', 'ATP-PC (phosphagen) system', 'All three equally'],
      answer: 2,
      explanation: 'The ATP-PC system dominates maximal efforts lasting roughly 0–10 seconds.',
      whyWrong: ['The oxidative system dominates efforts beyond ~2 minutes.', 'Glycolysis dominates roughly 30 seconds to 2 minutes.', '', 'All systems contribute somewhat, but ATP-PC clearly predominates at this duration and intensity.'],
    },
    {
      kind: 'mcq', id: 'ecb-m3', tags: ['breathing'], source: 'original',
      prompt: 'Which pattern indicates dysfunctional (abnormal) breathing?',
      options: [
        'Slow inhalation with expansion of the abdomen',
        'Deep breaths driven by the diaphragm',
        'Shallow rapid breaths using the sternocleidomastoid',
        'Slow nasal inhalation with limited chest movement',
      ],
      answer: 2,
      explanation: 'Shallow, rapid, chest-dominant breathing that recruits accessory neck muscles (SCM, scalenes) is the hallmark of dysfunctional breathing.',
      whyWrong: ['Abdominal expansion on inhalation is healthy diaphragmatic breathing.', 'Diaphragm-driven deep breathing is the normal, healthy pattern.', '', 'This describes controlled, healthy nasal breathing.'],
    },
    {
      kind: 'mcq', id: 'ecb-m4', tags: ['cardio'], source: 'original',
      prompt: 'Cardiac output is best defined as:',
      options: [
        'Blood ejected per single heartbeat',
        'Blood pumped by the heart per minute',
        'Blood remaining in the ventricle after contraction',
        'The pressure exerted against arterial walls',
      ],
      answer: 1,
      explanation: 'Cardiac output is the volume of blood pumped per minute, calculated as heart rate × stroke volume.',
      whyWrong: ['That is stroke volume, the per-beat measure.', '', 'That is end-systolic volume.', 'That describes blood pressure.'],
    },
    {
      kind: 'mcq', id: 'ecb-m5', tags: ['bioenergetics'], source: 'original',
      prompt: 'Which component contributes MOST to total daily energy expenditure for a typical person?',
      options: ['Exercise', 'Thermic effect of food', 'Resting metabolic rate', 'Non-exercise activity thermogenesis'],
      answer: 2,
      explanation: 'Resting metabolic rate — the energy used simply keeping the body alive at rest — is the largest single component for most people.',
      whyWrong: ['Exercise is typically a smaller share than RMR for most people.', 'TEF is the smallest component.', '', 'NEAT contributes meaningfully but is generally smaller than RMR.'],
    },
    {
      kind: 'match', id: 'ecb-match2', tags: ['endocrine'],
      prompt: 'Match each hormone to its primary role.',
      pairs: [
        ['Insulin', 'Lowers blood glucose by driving it into cells'],
        ['Glucagon', 'Raises blood glucose'],
        ['Cortisol', 'Catabolic stress hormone; elevated baseline suggests overtraining'],
        ['Testosterone', 'Anabolic hormone that declines with age'],
      ],
      explanation: 'These four hormones are the most commonly tested endocrine concepts for the CPT exam.',
    },
    {
      kind: 'match', id: 'ecb-match3', tags: ['cardio'],
      prompt: 'Match each cardiac term to its definition.',
      pairs: [
        ['Stroke volume', 'Blood ejected per beat (EDV − ESV)'],
        ['Cardiac output', 'Blood pumped per minute (HR × SV)'],
        ['SA node', 'The heart\'s natural pacemaker'],
        ['Mediastinum', 'The chest cavity containing the heart'],
      ],
      explanation: 'These cardiac definitions are frequently swapped as distractors on the exam — especially stroke volume vs cardiac output.',
    },
  ],
}
