import type { Module } from '../../types/content'

export const nervousSkeletalMuscular: Module = {
  id: 'd1-nervous-skeletal-muscular',
  domainId: 'd1',
  title: 'Nervous, Skeletal & Muscular Systems',
  estMinutes: 40,
  lessons: [
    {
      id: 'nsm-l1',
      title: 'The nervous system: your body\'s wiring',
      plain: `Think of the nervous system as two teams. The **central nervous system (CNS)** is HQ — just the brain and spinal cord. The **peripheral nervous system (PNS)** is every wire running out from HQ to the rest of the body. Inside the PNS there's a split: the **somatic** system controls muscles you consciously move, and the **autonomic** system runs on autopilot (heart rate, digestion) and splits again into **sympathetic** ("fight or flight" — speeds things up) and **parasympathetic** ("rest and digest" — calms things down).

Messages travel two directions: **afferent (sensory)** nerves carry information TO the brain ("ouch, that's hot"), **efferent (motor)** nerves carry commands FROM the brain to the muscles ("pull your hand back").`,
      nasm: `The nervous system is divided into the central nervous system (CNS: brain and spinal cord) and the peripheral nervous system (PNS). The PNS is further divided into the somatic nervous system (voluntary movement) and the autonomic nervous system (involuntary functions), which itself divides into the sympathetic (fight-or-flight) and parasympathetic (rest-and-digest) branches. Afferent (sensory) neurons carry information toward the CNS; efferent (motor) neurons carry commands away from the CNS to effector sites.`,
      memoryHook: `"A" for Afferent = "Arriving" at the brain. Efferent = Exiting the brain.`,
      mustMemorise: [
        'CNS = brain and spinal cord',
        'PNS splits into somatic (voluntary) and autonomic (involuntary)',
        'Autonomic splits into sympathetic (fight-or-flight) and parasympathetic (rest-and-digest)',
        'Afferent (sensory) neurons carry signals toward the CNS',
        'Efferent (motor) neurons carry signals away from the CNS',
      ],
    },
    {
      id: 'nsm-l2',
      title: 'Proprioception: sensors that protect your joints',
      plain: `Your body has built-in sensors that constantly report back on position, stretch, and tension — this sense is called proprioception. Two key sensors: the **muscle spindle** lives inside the muscle belly and senses how fast and how far a muscle is being stretched (it triggers a protective contraction if stretched too quickly — that's the stretch reflex). The **Golgi tendon organ (GTO)** sits where muscle meets tendon and senses tension/force — when tension gets too high, it tells the muscle to relax (protecting the tendon from tearing).`,
      nasm: `Proprioception refers to the cumulative sensory input to the CNS from mechanoreceptors that sense tension, movement, and position. The muscle spindle is sensitive to change in length of the muscle and the rate of that change, initiating the stretch reflex. The Golgi tendon organ (GTO) is sensitive to change in muscle-tendon tension and the rate of that tension change, and can inhibit muscle force production (autogenic inhibition) when tension is excessive. Joint receptors located within and around a joint capsule respond to pressure, acceleration, and deceleration of the joint.`,
      mustMemorise: [
        'Muscle spindle senses change in muscle length and speed of that change → triggers stretch reflex',
        'GTO senses change in muscle-tendon tension and speed of tension change → can trigger relaxation (autogenic inhibition)',
      ],
    },
    {
      id: 'nsm-l3',
      title: 'The skeletal system and Wolff\'s law',
      plain: `Skeleton splits into two: **axial** (skull, spine, ribs — the central core) and **appendicular** (arms, legs, shoulders, hips — everything hanging off the core). Bones aren't just structural — they're dynamic tissue. **Wolff's law** says bone rebuilds itself stronger along the lines of stress it's regularly put under — this is why resistance training increases bone density, while a sedentary lifestyle lets it decline. Resistance training strengthens bones, ligaments, and tendons — it does not directly strengthen nerves.`,
      nasm: `The axial skeleton consists of the skull, spine, and rib cage; the appendicular skeleton consists of the upper and lower extremities including the shoulder and pelvic girdles. Wolff's law states that bone tissue will adapt to the mechanical demands (loads) placed upon it, increasing bone mineral density (calcium, phosphorus content) in response to progressive loading such as resistance training. Resistance training increases the tensile strength of bone, ligament, and tendon tissue.`,
      mustMemorise: [
        'Axial skeleton = skull, spine, ribs',
        'Appendicular skeleton = arms, legs, shoulder/pelvic girdles',
        'Wolff\'s law: bone adapts and strengthens in response to the mechanical load placed on it',
        'Resistance training strengthens bone, ligament, and tendon — not nerve tissue',
      ],
    },
    {
      id: 'nsm-l4',
      title: 'How a muscle actually contracts',
      plain: `Zoom into a muscle fiber and you find a repeating unit called a **sarcomere**, built from two proteins: thin **actin** filaments and thick **myosin** filaments. When a nerve signal arrives (released as the chemical **acetylcholine** at the neuromuscular junction), myosin heads grab actin and ratchet it inward — this is the **sliding filament theory**. A single nerve plus every muscle fiber it controls is called a **motor unit**, and it fires **all-or-none** — either the whole unit contracts or none of it does; there's no "partial" firing of one motor unit.`,
      nasm: `The sarcomere is the functional unit of the muscle fiber, composed of thin actin filaments and thick myosin filaments. Acetylcholine, released at the neuromuscular junction, triggers depolarization and the sliding filament theory of contraction, in which myosin cross-bridges pull actin filaments toward the center of the sarcomere. A motor unit consists of a single motor neuron and all the muscle fibers it innervates, and obeys the all-or-none principle: a stimulus either produces a full contraction of the motor unit or no contraction at all.`,
      memoryHook: `Actin = thin (think "a" for "a-thin-line"). Myosin = thick.`,
      mustMemorise: [
        'Sarcomere = functional contractile unit, made of actin (thin) and myosin (thick) filaments',
        'Acetylcholine is released at the neuromuscular junction to trigger contraction',
        'Motor unit = one motor neuron + all fibers it innervates',
        'All-or-none principle: a motor unit fully contracts or does not contract at all',
      ],
    },
    {
      id: 'nsm-l5',
      title: 'Fiber types, roles, and force relationships',
      plain: `Muscle fibers come in flavors: **Type I** (slow-twitch — built for endurance, fatigue-resistant), **Type IIa** (a hybrid — decent at both endurance and power), and **Type IIx** (fast-twitch — explosive but fatigues fast). In any movement, muscles play different roles: the **agonist** is the prime mover doing the work, the **antagonist** is on the opposite side and lengthens to allow the movement, **synergists** assist the agonist, and **stabilizers** hold everything steady so the prime mover can do its job. Two useful relationships: **length-tension** (a muscle produces the most force at its ideal resting length — too short or too stretched, and force drops), and **force-velocity** (the faster you try to move a load, the less force you can produce — a heavy deadlift is slow, a punch is fast but lower force).`,
      nasm: `Type I fibers are slow-twitch, high fatigue-resistant, and oxidative. Type IIx fibers are fast-twitch, low fatigue-resistant, and glycolytic. Type IIa fibers exhibit intermediate characteristics of both. Muscles function with specific roles: agonists (prime movers), antagonists (oppose the agonist), synergists (assist the agonist), and stabilizers (support/stabilize the body while the agonist and synergists perform the movement). The length-tension relationship describes the resting length of a muscle and the tension it can produce at that length; the force-velocity curve describes the inverse relationship between the force a muscle produces and the speed of muscle shortening.`,
      mustMemorise: [
        'Type I = slow-twitch, endurance, fatigue-resistant',
        'Type IIx = fast-twitch, explosive, fatigues quickly',
        'Type IIa = intermediate between Type I and IIx',
        'Muscle roles: agonist (prime mover), antagonist (opposes), synergist (assists), stabilizer (holds steady)',
      ],
    },
    {
      id: 'nsm-l6',
      title: 'The core subsystems',
      plain: `The core isn't just abs — NASM breaks it into 4 subsystems that work together to keep the spine and pelvis stable during movement. **Deep longitudinal** runs from foot to back: erector spinae, thoracolumbar fascia, sacrotuberous ligament, biceps femoris (hamstrings), and peroneals. **Posterior oblique** crosses diagonally across the back: latissimus dorsi and contralateral (opposite-side) gluteus maximus, connected through the thoracolumbar fascia. **Anterior oblique** crosses diagonally across the front: internal/external obliques, adductors, and hip rotators. **Lateral** stabilizes side-to-side: gluteus medius, adductors, and quadratus lumborum.`,
      nasm: `The deep longitudinal subsystem includes the erector spinae, thoracolumbar fascia, sacrotuberous ligament, biceps femoris, and peroneus longus. The posterior oblique subsystem includes the latissimus dorsi, contralateral gluteus maximus, and the thoracolumbar fascia connecting them. The anterior oblique subsystem includes the internal/external obliques, adductor complex, and hip rotators. The lateral subsystem includes the gluteus medius, adductor complex, and quadratus lumborum, controlling frontal-plane stability of the lumbo-pelvic-hip complex.`,
      mustMemorise: [
        'Deep longitudinal subsystem: erector spinae, thoracolumbar fascia, sacrotuberous ligament, biceps femoris, peroneals',
        'Posterior oblique subsystem: latissimus dorsi + contralateral gluteus maximus via thoracolumbar fascia',
        'Anterior oblique subsystem: obliques, adductors, hip rotators',
        'Lateral subsystem: gluteus medius, adductor complex, quadratus lumborum',
      ],
    },
  ],
  items: [
    { kind: 'typein', id: 'nsm-t1', tags: ['nervous-system'], prompt: 'Which two structures make up the central nervous system?', accept: ['brain and spinal cord', 'brain, spinal cord'], hints: ['One is inside your skull, one runs down your back.', 'B____ and S_____ C___'], explanation: 'The CNS consists of the brain and spinal cord.' },
    { kind: 'typein', id: 'nsm-t2', tags: ['nervous-system'], prompt: 'Which branch of the autonomic nervous system is known as "fight or flight"?', accept: ['sympathetic'], hints: ['Gets your heart racing.', 'S__________'], explanation: 'The sympathetic nervous system triggers the fight-or-flight response.' },
    { kind: 'typein', id: 'nsm-t3', tags: ['nervous-system'], prompt: 'Which branch of the autonomic nervous system is known as "rest and digest"?', accept: ['parasympathetic'], hints: ['Calms the body down.', 'P___________'], explanation: 'The parasympathetic nervous system produces the rest-and-digest response.' },
    { kind: 'typein', id: 'nsm-t4', tags: ['nervous-system'], prompt: 'Neurons that carry signals TOWARD the brain (sensory) are called what?', accept: ['afferent'], hints: ['"A" for arriving at the brain.', 'A_______'], explanation: 'Afferent (sensory) neurons carry signals toward the CNS.' },
    { kind: 'typein', id: 'nsm-t5', tags: ['nervous-system'], prompt: 'Neurons that carry commands AWAY from the brain to the muscles are called what?', accept: ['efferent'], hints: ['"E" for exiting the brain.', 'E_______'], explanation: 'Efferent (motor) neurons carry signals away from the CNS.' },
    { kind: 'typein', id: 'nsm-t6', tags: ['nervous-system', 'proprioception'], prompt: 'Which sensor lives in the muscle belly and senses change in muscle length and speed of stretch?', accept: ['muscle spindle'], hints: ['Triggers the stretch reflex.', 'M_____ S______'], explanation: 'The muscle spindle senses length change and speed, triggering the stretch reflex.' },
    { kind: 'typein', id: 'nsm-t7', tags: ['nervous-system', 'proprioception'], prompt: 'Which sensor sits at the muscle-tendon junction and senses tension, inhibiting force if tension is too high?', accept: ['golgi tendon organ', 'gto'], hints: ['Abbreviated GTO.', 'G____ T_____ O_____'], explanation: 'The Golgi tendon organ senses tension change and can inhibit contraction (autogenic inhibition) if tension is excessive.' },
    { kind: 'typein', id: 'nsm-t8', tags: ['skeletal-system'], prompt: 'What is the name of the principle stating bone strengthens in response to the mechanical load placed on it?', accept: ['wolffs law', 'wolff\'s law'], hints: ['Named after a person.', 'W_____\'s L__'], explanation: 'Wolff\'s law: bone remodels and strengthens according to the stress placed upon it.' },
    { kind: 'typein', id: 'nsm-t9', tags: ['skeletal-system'], prompt: 'Which part of the skeleton includes the skull, spine, and rib cage?', accept: ['axial', 'axial skeleton'], hints: ['The central core.', 'A____ skeleton'], explanation: 'The axial skeleton is the skull, spine, and rib cage.' },
    { kind: 'typein', id: 'nsm-t10', tags: ['skeletal-system'], prompt: 'Which part of the skeleton includes the arms and legs?', accept: ['appendicular', 'appendicular skeleton'], hints: ['Like an "appendage."', 'A___________ skeleton'], explanation: 'The appendicular skeleton is the arms, legs, and shoulder/pelvic girdles.' },
    { kind: 'typein', id: 'nsm-t11', tags: ['muscular-system'], prompt: 'What is the functional contractile unit of a muscle fiber, made of actin and myosin?', accept: ['sarcomere'], hints: ['Repeats along the length of a myofibril.', 'S_______'], explanation: 'The sarcomere is the basic contractile unit, made of actin and myosin filaments.' },
    { kind: 'typein', id: 'nsm-t12', tags: ['muscular-system'], prompt: 'Which filament is thin: actin or myosin?', accept: ['actin'], hints: ['Starts with A, like "thin."', 'A____'], explanation: 'Actin is the thin filament; myosin is the thick filament.' },
    { kind: 'typein', id: 'nsm-t13', tags: ['muscular-system'], prompt: 'What chemical is released at the neuromuscular junction to trigger a muscle contraction?', accept: ['acetylcholine'], hints: ['A neurotransmitter.', 'A__________'], explanation: 'Acetylcholine is released at the neuromuscular junction to trigger contraction.' },
    { kind: 'typein', id: 'nsm-t14', tags: ['muscular-system'], prompt: 'A single motor neuron plus every muscle fiber it innervates is called what?', accept: ['motor unit'], hints: ['Fires all-or-none.', 'M____ U___'], explanation: 'A motor unit is one motor neuron plus all the fibers it innervates.' },
    { kind: 'typein', id: 'nsm-t15', tags: ['muscular-system'], prompt: 'Which muscle fiber type is slow-twitch and fatigue-resistant, built for endurance?', accept: ['type 1', 'type i'], hints: ['The lowest number.', 'Type _'], explanation: 'Type I fibers are slow-twitch and highly fatigue-resistant.' },
    { kind: 'typein', id: 'nsm-t16', tags: ['muscular-system'], prompt: 'Which muscle fiber type is fast-twitch, explosive, and fatigues quickly?', accept: ['type 2x', 'type iix', 'type 2 x'], hints: ['The "x" fiber.', 'Type II_'], explanation: 'Type IIx fibers are fast-twitch, explosive, and fatigue quickly.' },
    { kind: 'typein', id: 'nsm-t17', tags: ['muscular-system', 'roles'], prompt: 'In a bicep curl, biceps brachii is the prime mover. What term describes this role?', accept: ['agonist'], hints: ['The main muscle doing the work.', 'A______'], explanation: 'The agonist is the prime mover producing the movement.' },
    { kind: 'typein', id: 'nsm-t18', tags: ['muscular-system', 'roles'], prompt: 'What term describes a muscle that assists the prime mover in a movement?', accept: ['synergist'], hints: ['Works "in synergy" with the agonist.', 'S________'], explanation: 'A synergist assists the agonist in producing the movement.' },
    { kind: 'typein', id: 'nsm-t19', tags: ['core-subsystems'], prompt: 'Which core subsystem includes the erector spinae, thoracolumbar fascia, and hamstrings?', accept: ['deep longitudinal', 'deep longitudinal subsystem'], hints: ['Runs foot to back.', 'D___ L__________ subsystem'], explanation: 'The deep longitudinal subsystem includes erector spinae, thoracolumbar fascia, sacrotuberous ligament, biceps femoris, and peroneals.' },
    { kind: 'typein', id: 'nsm-t20', tags: ['core-subsystems'], prompt: 'Which core subsystem includes latissimus dorsi and the contralateral gluteus maximus?', accept: ['posterior oblique', 'posterior oblique subsystem'], hints: ['Crosses diagonally across the back.', 'P________ O______ subsystem'], explanation: 'The posterior oblique subsystem connects lat and contralateral glute max via the thoracolumbar fascia.' },
    {
      kind: 'mcq', id: 'nsm-m1', tags: ['nervous-system'], source: 'original',
      prompt: 'A client\'s heart rate spikes and they feel anxious before a heavy squat attempt. Which branch of the nervous system is primarily responsible?',
      options: ['Parasympathetic', 'Sympathetic', 'Somatic', 'Central'],
      answer: 1,
      explanation: 'The sympathetic nervous system triggers the fight-or-flight response, raising heart rate and arousal.',
      whyWrong: ['Parasympathetic would calm the client down, not spike arousal.', '', 'The somatic system controls voluntary muscle movement, not this involuntary arousal response.', 'The central nervous system is the brain/spinal cord itself, not a specific arousal-response branch.'],
    },
    {
      kind: 'mcq', id: 'nsm-m2', tags: ['muscular-system'], source: 'original',
      prompt: 'A client stretches a muscle too quickly and feels an involuntary contraction kick in to protect the muscle. Which structure caused this?',
      options: ['Golgi tendon organ', 'Muscle spindle', 'Sarcomere', 'Motor unit'],
      answer: 1,
      explanation: 'The muscle spindle senses rapid stretch and triggers a protective reflexive contraction (the stretch reflex).',
      whyWrong: ['The GTO responds to excessive tension, not rapid stretch, and produces relaxation, not contraction.', '', 'The sarcomere is the contractile unit itself, not the sensor that triggers the reflex.', 'A motor unit is the neuron-plus-fibers structure that contracts, not the sensor triggering the reflex.'],
    },
    {
      kind: 'match', id: 'nsm-match1', tags: ['muscular-system', 'roles'],
      prompt: 'Match each muscle role to its description.',
      pairs: [
        ['Agonist', 'The prime mover producing the movement'],
        ['Antagonist', 'Opposes the agonist and lengthens to allow movement'],
        ['Synergist', 'Assists the agonist in producing the movement'],
        ['Stabilizer', 'Holds a body segment steady so the movement can occur'],
      ],
      explanation: 'Agonist = prime mover, antagonist = opposes, synergist = assists, stabilizer = holds steady.',
    },
    {
      kind: 'multi-typein', id: 'nsm-mt1', tags: ['core-subsystems'],
      prompt: 'Name the muscles/structures of the deep longitudinal subsystem (4 answers).',
      expected: [
        { canonical: 'erector spinae', accept: ['erector spinae'] },
        { canonical: 'thoracolumbar fascia', accept: ['thoracolumbar fascia'] },
        { canonical: 'sacrotuberous ligament', accept: ['sacrotuberous ligament'] },
        { canonical: 'biceps femoris', accept: ['biceps femoris', 'hamstrings'] },
      ],
      minToPass: 3,
      explanation: 'The deep longitudinal subsystem: erector spinae, thoracolumbar fascia, sacrotuberous ligament, biceps femoris (hamstrings), and peroneals.',
    },
    { kind: 'typein', id: 'nsm-t21', tags: ['muscular-system'], prompt: 'Which muscle fiber type is intermediate between slow-twitch and fast-twitch?', accept: ['type 2a', 'type iia'], hints: ['The "a" fiber.', 'Type II_'], explanation: 'Type IIa fibers show intermediate characteristics of both Type I and Type IIx.' },
    { kind: 'typein', id: 'nsm-t22', tags: ['muscular-system', 'roles'], prompt: 'What term describes the muscle on the OPPOSITE side that lengthens to allow a movement?', accept: ['antagonist'], hints: ['Opposes the agonist.', 'A_________'], explanation: 'The antagonist opposes the agonist and lengthens to permit the movement.' },
    { kind: 'typein', id: 'nsm-t23', tags: ['muscular-system', 'roles'], prompt: 'What term describes a muscle that holds a body segment steady so the prime mover can work?', accept: ['stabilizer'], hints: ['Provides a stable base.', 'S_________'], explanation: 'Stabilizers support and stabilize while the agonist and synergists produce the movement.' },
    { kind: 'typein', id: 'nsm-t24', tags: ['muscular-system'], prompt: 'What theory describes myosin pulling actin toward the center of the sarcomere?', accept: ['sliding filament theory', 'sliding filament'], hints: ['Named for what the filaments do.', 'S______ F______ theory'], explanation: 'The sliding filament theory explains muscle contraction at the sarcomere level.' },
    { kind: 'typein', id: 'nsm-t25', tags: ['muscular-system'], prompt: 'What relationship describes a muscle producing the most force at its optimal resting length?', accept: ['length-tension relationship', 'length tension'], hints: ['Two properties, hyphenated.', 'L_____-T______ relationship'], explanation: 'The length-tension relationship describes force output relative to muscle resting length.' },
    { kind: 'typein', id: 'nsm-t26', tags: ['muscular-system'], prompt: 'What curve describes the inverse relationship between force produced and speed of shortening?', accept: ['force-velocity curve', 'force velocity'], hints: ['Two properties, hyphenated.', 'F____-V______ curve'], explanation: 'The force-velocity curve: the faster a muscle shortens, the less force it can produce.' },
    { kind: 'typein', id: 'nsm-t27', tags: ['nervous-system'], prompt: 'Which branch of the PNS controls voluntary movement?', accept: ['somatic', 'somatic nervous system'], hints: ['Conscious control.', 'S_______'], explanation: 'The somatic nervous system controls voluntary skeletal muscle movement.' },
    { kind: 'typein', id: 'nsm-t28', tags: ['core-subsystems'], prompt: 'Which core subsystem includes the gluteus medius, adductor complex, and quadratus lumborum?', accept: ['lateral', 'lateral subsystem'], hints: ['Controls side-to-side stability.', 'L______ subsystem'], explanation: 'The lateral subsystem controls frontal-plane stability of the lumbo-pelvic-hip complex.' },
    { kind: 'typein', id: 'nsm-t29', tags: ['core-subsystems'], prompt: 'Which core subsystem includes the internal/external obliques, adductors, and hip rotators?', accept: ['anterior oblique', 'anterior oblique subsystem'], hints: ['Crosses the front of the body.', 'A________ O______ subsystem'], explanation: 'The anterior oblique subsystem crosses diagonally across the front of the torso.' },
    {
      kind: 'scenario', id: 'nsm-s1', tags: ['proprioception'],
      story: 'A client performs a heavy deadlift. Near their limit, they feel the muscles suddenly "give" slightly and their grip on the effort loosens, as if a protective brake engaged.',
      question: 'Which receptor most likely produced this response?',
      options: ['Muscle spindle', 'Golgi tendon organ', 'Joint receptor', 'Neuromuscular junction'],
      answer: 1,
      explanation: 'The GTO senses excessive muscle-tendon tension and can inhibit contraction (autogenic inhibition) to protect the tendon from injury.',
      whyWrong: ['The muscle spindle responds to rapid stretch by causing contraction, not by inhibiting it.', '', 'Joint receptors respond to joint pressure and position, not tension-driven inhibition.', 'The neuromuscular junction is the signal transmission site, not a protective sensor.'],
    },
    {
      kind: 'scenario', id: 'nsm-s2', tags: ['muscular-system'],
      story: 'A client wants to improve their performance in a marathon, which requires sustained submaximal effort over several hours.',
      question: 'Which muscle fiber type is most relevant to this goal?',
      options: ['Type I (slow-twitch)', 'Type IIx (fast-twitch)', 'Type IIa only', 'Fiber type is irrelevant to endurance'],
      answer: 0,
      explanation: 'Type I fibers are slow-twitch, highly fatigue-resistant, and oxidative — exactly what sustained endurance performance relies on.',
      whyWrong: ['', 'Type IIx fibers are explosive but fatigue rapidly, unsuited to hours of sustained effort.', 'Type IIa contributes, but Type I is the dominant endurance fiber.', 'Fiber type composition is highly relevant to endurance performance.'],
    },
    {
      kind: 'mcq', id: 'nsm-m3', tags: ['skeletal-system'], source: 'original',
      prompt: 'Which of the following is NOT subject to increased density through resistance training?',
      options: ['Bone', 'Tendons and ligaments', 'Nerves', 'Muscle tissue'],
      answer: 2,
      explanation: 'Resistance training increases the density/tensile strength of bone and connective tissue and the size of muscle, but nerve tissue does not increase in density this way.',
      whyWrong: ['Bone density increases with loading per Wolff\'s law.', 'Tendons and ligaments gain tensile strength with resistance training.', '', 'Muscle tissue hypertrophies in response to resistance training.'],
    },
    {
      kind: 'mcq', id: 'nsm-m4', tags: ['muscular-system'], source: 'original',
      prompt: 'What does the all-or-none principle state about a motor unit?',
      options: [
        'A motor unit contracts partially in proportion to stimulus strength',
        'A motor unit either fully contracts or does not contract at all',
        'All motor units in a muscle fire simultaneously',
        'Motor units fire only during eccentric contractions',
      ],
      answer: 1,
      explanation: 'The all-or-none principle: a stimulus either produces a complete contraction of that motor unit or no contraction at all — there is no partial firing of a single unit.',
      whyWrong: ['Partial contraction of a single motor unit is precisely what the principle rules out.', '', 'Force is graded by recruiting more or fewer units, not by all firing at once.', 'Motor units fire during all contraction types.'],
    },
    {
      kind: 'mcq', id: 'nsm-m5', tags: ['core-subsystems'], source: 'original',
      prompt: 'The posterior oblique subsystem pairs the latissimus dorsi with which muscle?',
      options: [
        'The ipsilateral (same-side) gluteus maximus',
        'The contralateral (opposite-side) gluteus maximus',
        'The ipsilateral quadratus lumborum',
        'The contralateral adductor complex',
      ],
      answer: 1,
      explanation: 'The posterior oblique subsystem connects the latissimus dorsi to the CONTRALATERAL gluteus maximus through the thoracolumbar fascia — a diagonal sling across the back.',
      whyWrong: ['The pairing is contralateral (opposite side), not same side.', '', 'QL pairing describes the lateral subsystem.', 'The adductor complex features in the anterior oblique and lateral subsystems.'],
    },
    {
      kind: 'match', id: 'nsm-match2', tags: ['core-subsystems'],
      prompt: 'Match each core subsystem to a defining muscle pairing.',
      pairs: [
        ['Deep longitudinal', 'Erector spinae + biceps femoris via thoracolumbar fascia'],
        ['Posterior oblique', 'Latissimus dorsi + contralateral gluteus maximus'],
        ['Anterior oblique', 'Obliques + adductors + hip rotators'],
        ['Lateral', 'Gluteus medius + adductors + quadratus lumborum'],
      ],
      explanation: 'The four subsystems each describe a functional sling that stabilizes the body during movement.',
    },
    {
      kind: 'match', id: 'nsm-match3', tags: ['muscular-system'],
      prompt: 'Match each fiber type to its characteristics.',
      pairs: [
        ['Type I', 'Slow-twitch, fatigue-resistant, oxidative'],
        ['Type IIa', 'Intermediate characteristics of both'],
        ['Type IIx', 'Fast-twitch, explosive, fatigues quickly'],
      ],
      explanation: 'Fiber types run on a spectrum from endurance-oriented Type I to explosive Type IIx, with IIa in between.',
    },
  ],
}
