import type { Module } from '../../types/content'

export const performanceTesting: Module = {
  id: 'd2-performance-testing',
  domainId: 'd2',
  title: 'Performance Testing & Assessment Sequencing',
  estMinutes: 30,
  lessons: [
    {
      id: 'pt-l1',
      title: 'Cardio fitness tests: picking the right one',
      plain: `Different cardio tests fit different clients. The **YMCA 3-minute step test** and **Rockport 1-mile walk test** are lower-intensity, sub-maximal tests good for general or deconditioned populations. The **1.5-mile (2.4km) run test** is much more demanding — appropriate for already-fit, athletic clients (like a college athlete), not beginners. The **talk test** is a simple, subjective intensity check (can they hold a conversation?) rather than a fitness-level measurement tool.`,
      nasm: `The YMCA 3-minute step test and Rockport 1-mile walk test are sub-maximal cardiorespiratory assessments appropriate for general or lower-fitness populations. The 1.5-mile (2.4 km) run test is a higher-intensity assessment better suited to already-fit, athletic clients. The talk test is a subjective method of gauging exercise intensity based on the ability to hold a conversation, not a standalone fitness-level assessment.`,
      mustMemorise: ['YMCA step test and Rockport walk test = sub-maximal, general population', '1.5-mile run test = for already-fit, athletic clients'],
    },
    {
      id: 'pt-l2',
      title: 'Performance tests: push-up, Davies, shark skill',
      plain: `The **push-up test** is timed at 60 seconds and counts max reps with good form. The **Davies test** measures upper-body agility/stability — the client touches tape marks 36 inches apart as fast as possible in 15 seconds. The **shark skill test** measures lower-body agility/coordination on a grid, with a small time penalty (0.10 sec) for stepping on lines. These, along with vertical jump, 40-yard dash, and pro shuttle, are performance-level assessments — meaning they're physically demanding and always come last in the assessment sequence, after intake, vitals, and movement screens.`,
      nasm: `The push-up test is administered over 60 seconds, counting the maximum number of repetitions performed with proper form. The Davies test assesses upper-extremity plyometric stability using markers placed 36 inches apart, performed over a 15-second interval. The shark skill test assesses lower-body agility and coordination, applying a 0.10-second time penalty for each line touched. Performance assessments, being the most physically demanding, are administered last in the overall assessment sequence.`,
      mustMemorise: [
        'Push-up test: 60 seconds, max reps',
        'Davies test: markers 36 in. apart, 15 seconds',
        'Shark skill test: 0.10 sec penalty per line touch',
        'Performance assessments are always performed last in the assessment sequence',
      ],
    },
    {
      id: 'pt-l3',
      title: 'Sequencing the full assessment',
      plain: `Order matters. General flow: health history/intake first, then resting vitals (heart rate, blood pressure — measured at rest, not after exercise), then body composition, then static posture, then movement assessments (like the overhead squat), and performance assessments (the most demanding) come last. One exception: flexibility is actually better measured after some activity/warm-up rather than cold, since muscles are more pliable once warmed up.`,
      nasm: `The standard assessment sequence progresses from health-history intake, to resting vitals, to body composition, to static posture, to movement assessments, and finally to performance assessments (the most physically demanding, performed last). Flexibility assessments are an exception to a strictly "before activity" sequence, as tissue pliability improves following a brief warm-up, producing more representative results.`,
      mustMemorise: ['Assessment order: intake → vitals → body composition → posture → movement → performance (last)', 'Flexibility assessments are better measured after some activity, not cold'],
    },
  ],
  items: [
    { kind: 'typein', id: 'pt-t1', tags: ['cardio-tests'], prompt: 'Which cardio test is most appropriate for an already-fit, athletic client (e.g. a college athlete)?', accept: ['1.5-mile run test', '1.5 mile run test', '1.5-mile run', 'the 1.5-mile run test'], hints: ['A timed distance run.', '_._-mile run test'], explanation: 'The 1.5-mile run test suits already-fit, athletic populations.' },
    { kind: 'typein', id: 'pt-t2', tags: ['cardio-tests'], prompt: 'Which two cardio tests are sub-maximal and better suited to general/deconditioned populations?', accept: ['ymca step test and rockport walk test', 'ymca 3-minute step test and rockport 1-mile walk test'], hints: ['One is a step test, one is a walk test.', 'YMCA ____ test, R_______ ____ test'], explanation: 'The YMCA 3-minute step test and Rockport 1-mile walk test are sub-maximal, general-population tests.' },
    { kind: 'typein', id: 'pt-t3', tags: ['performance-tests'], prompt: 'How long is the push-up test?', accept: ['60 seconds', '60 sec', '1 minute'], hints: ['One minute.', '__ seconds'], explanation: 'The push-up test is timed at 60 seconds.' },
    { kind: 'typein', id: 'pt-t4', tags: ['performance-tests'], prompt: 'How far apart are the markers in the Davies test?', accept: ['36 inches', '36 in', '36 in.'], hints: ['A distance in inches.', '__ inches'], explanation: 'The Davies test uses markers 36 inches apart.' },
    { kind: 'typein', id: 'pt-t5', tags: ['performance-tests'], prompt: 'What time penalty is applied per line touched in the shark skill test?', accept: ['0.10 seconds', '0.10 sec', '0.1 seconds'], hints: ['A tenth of a second.', '0.__ sec'], explanation: 'The shark skill test applies a 0.10-second penalty per line touched.' },
    { kind: 'typein', id: 'pt-t6', tags: ['sequencing'], prompt: 'Which type of assessment should always be performed last in the overall sequence?', accept: ['performance assessments', 'performance'], hints: ['The most physically demanding.', 'P___________ assessments'], explanation: 'Performance assessments, being most demanding, are performed last.' },
    { kind: 'typein', id: 'pt-t7', tags: ['sequencing'], prompt: 'Which assessment type is better measured after some activity rather than cold?', accept: ['flexibility'], hints: ['Muscles are more pliable warmed up.', 'F___________'], explanation: 'Flexibility is better assessed after some activity, since tissue is more pliable.' },
    {
      kind: 'mcq', id: 'pt-m1', tags: ['sequencing'], source: 'original',
      prompt: 'Which of the following would produce a better result if measured immediately after some activity rather than before?',
      options: ['Resting heart rate', 'Blood pressure', 'Body composition', 'Flexibility'],
      answer: 3,
      explanation: 'Flexibility assessments are more accurate and representative when muscles are warmed up, unlike resting-state measurements.',
      whyWrong: ['Resting heart rate must be measured at rest, by definition.', 'Blood pressure should be measured at rest for a baseline reading.', 'Body composition should be measured under consistent, resting conditions.', ''],
    },
    {
      kind: 'mcq', id: 'pt-m2', tags: ['performance-tests'], source: 'original',
      prompt: 'A trainer wants to measure the overall fitness of a fit, college-aged rugby athlete. Which test is most appropriate?',
      options: ['YMCA 3-minute step test', 'The talk test', 'Rockport 1-mile walk test', '1.5-mile (2.4 km) run test'],
      answer: 3,
      explanation: 'The 1.5-mile run test is a higher-intensity assessment appropriate for an already-fit, competitive athlete.',
      whyWrong: ['The YMCA step test is sub-maximal, better suited to general/deconditioned populations.', 'The talk test is a subjective intensity check, not a standalone fitness measurement.', 'The Rockport walk test is designed for lower-fitness populations, not competitive athletes.', ''],
    },
    { kind: 'typein', id: 'pt-t8', tags: ['movement-assessment'], prompt: 'Which movement assessment uses weighted cables/pulleys to observe a PUSHING pattern?', accept: ['standing push assessment', 'pushing assessment'], hints: ['Named for the motion.', 'Standing P___ assessment'], explanation: 'The standing push assessment uses a cable/pulley setup to observe compensations during pushing.' },
    { kind: 'typein', id: 'pt-t9', tags: ['movement-assessment'], prompt: 'Which dynamic assessment is the primary full-body movement screen in the NASM system?', accept: ['overhead squat assessment', 'overhead squat', 'ohsa'], hints: ['Arms up, squat down.', 'O_______ S____ assessment'], explanation: 'The overhead squat assessment (OHSA) is the primary dynamic movement screen.' },
    { kind: 'typein', id: 'pt-t10', tags: ['movement-assessment'], prompt: 'From which three views is the overhead squat assessment observed?', accept: ['anterior lateral posterior', 'anterior, lateral, posterior', 'front side back'], hints: ['Front, side, back.', 'A________, L______, P________'], explanation: 'The OHSA is observed from anterior, lateral, and posterior views.' },
    { kind: 'typein', id: 'pt-t11', tags: ['performance-tests'], prompt: 'Which performance test measures lower-body agility using a grid with a time penalty for line touches?', accept: ['shark skill test', 'shark skill'], hints: ['Named after an animal.', 'S____ skill test'], explanation: 'The shark skill test assesses lower-body agility with a 0.10s penalty per line touched.' },
    { kind: 'typein', id: 'pt-t12', tags: ['performance-tests'], prompt: 'Which performance test measures upper-extremity agility/stability with markers 36 inches apart?', accept: ['davies test', 'davies'], hints: ['A surname.', 'D_____ test'], explanation: 'The Davies test uses markers 36 inches apart over a 15-second interval.' },
    { kind: 'typein', id: 'pt-t13', tags: ['posture'], prompt: 'Which static postural distortion pattern involves a flattened arch of the foot?', accept: ['pes planus', 'pes planus distortion syndrome'], hints: ['Latin for flat foot.', 'P__ P_____'], explanation: 'Pes planus distortion syndrome involves flat feet, knee adduction, and internal rotation.' },
    { kind: 'typein', id: 'pt-t14', tags: ['posture'], prompt: 'Which postural distortion pattern involves anterior pelvic tilt and an arched low back?', accept: ['lower crossed syndrome', 'lower crossed'], hints: ['Named for its crossing pattern, lower body.', 'L____ C______ syndrome'], explanation: 'Lower crossed syndrome: tight hip flexors/erector spinae with weak glutes/abdominals, producing anterior pelvic tilt.' },
    { kind: 'typein', id: 'pt-t15', tags: ['posture'], prompt: 'Which postural distortion pattern involves rounded shoulders and a forward head?', accept: ['upper crossed syndrome', 'upper crossed'], hints: ['Named for its crossing pattern, upper body.', 'U____ C______ syndrome'], explanation: 'Upper crossed syndrome: tight chest/upper traps/levator with weak deep cervical flexors and mid/lower traps.' },
    {
      kind: 'scenario', id: 'pt-s1', tags: ['sequencing'],
      story: 'A trainer plans a first-session assessment: PAR-Q+, resting heart rate and blood pressure, body composition, overhead squat, and a push-up test.',
      question: 'In what order should these be performed?',
      options: [
        'Push-up test → PAR-Q+ → vitals → body composition → overhead squat',
        'PAR-Q+ → vitals → body composition → overhead squat → push-up test',
        'PAR-Q+ → overhead squat → push-up test → vitals → body composition',
        'Vitals → PAR-Q+ → push-up test → overhead squat → body composition',
      ],
      answer: 1,
      explanation: 'Sequence: health screening first, then resting vitals, then body composition, then movement assessment, with the most demanding performance test last.',
      whyWrong: ['A maximal performance test can never precede health screening.', '', 'Performance tests must come last, not before resting measurements.', 'Health screening (PAR-Q+) must come first, before any measurement or test.'],
    },
    {
      kind: 'scenario', id: 'pt-s2', tags: ['cardio-tests'],
      story: 'A 58-year-old client with a sedentary history and controlled hypertension needs a cardiorespiratory assessment.',
      question: 'Which test is most appropriate?',
      options: [
        '1.5-mile run test',
        '40-yard dash',
        'Rockport 1-mile walk test',
        'Maximal treadmill test to exhaustion',
      ],
      answer: 2,
      explanation: 'The Rockport walk test is a sub-maximal assessment appropriate for older, deconditioned, or higher-risk clients.',
      whyWrong: ['The 1.5-mile run is a high-intensity test suited to already-fit athletic clients.', 'A 40-yard dash is a sprint performance test, inappropriate for this population.', '', 'A maximal test to exhaustion is inappropriate and unsafe for this client profile.'],
    },
    {
      kind: 'mcq', id: 'pt-m3', tags: ['sequencing'], source: 'original',
      prompt: 'Why are performance assessments always scheduled last?',
      options: [
        'They take the longest to administer',
        'They are the most physically demanding and would fatigue the client, skewing other results',
        'They require the most equipment',
        'They are optional',
      ],
      answer: 1,
      explanation: 'Performance tests are maximal or near-maximal efforts. Performing them first would fatigue the client and invalidate resting vitals and movement quality observations.',
      whyWrong: ['Duration is not the sequencing rationale.', '', 'Equipment needs do not drive the assessment sequence.', 'Performance assessments are a standard part of the assessment flow when appropriate.'],
    },
    {
      kind: 'mcq', id: 'pt-m4', tags: ['posture'], source: 'original',
      prompt: 'Posture is assessed relative to which anatomical landmark?',
      options: ['The ankles', 'The shoulders', 'The spine', 'The knees'],
      answer: 2,
      explanation: 'Posture is evaluated relative to the position of the spine, with other segments compared against it.',
      whyWrong: ['Ankles are one kinetic chain checkpoint, not the central reference.', 'Shoulders are one checkpoint, not the central reference.', '', 'Knees are one checkpoint, not the central reference.'],
    },
    {
      kind: 'mcq', id: 'pt-m5', tags: ['performance-tests'], source: 'original',
      prompt: 'Which statement about the shark skill test is correct?',
      options: [
        'It assesses upper-body power with a 15-second limit',
        'It assesses lower-body agility with a 0.10-second penalty per line touched',
        'It measures cardiorespiratory endurance over 1.5 miles',
        'It measures maximal squat strength',
      ],
      answer: 1,
      explanation: 'The shark skill test assesses lower-body agility and coordination on a grid, applying a 0.10-second penalty for each line touched.',
      whyWrong: ['That more closely describes the Davies test (upper extremity, 15 seconds).', '', 'That describes the 1.5-mile run test.', 'That describes a 1RM squat assessment.'],
    },
    {
      kind: 'match', id: 'pt-match1', tags: ['performance-tests'],
      prompt: 'Match each performance test to its defining detail.',
      pairs: [
        ['Push-up test', '60 seconds, max reps'],
        ['Davies test', 'Markers 36 inches apart, 15 seconds'],
        ['Shark skill test', '0.10-second penalty per line touched'],
      ],
      explanation: 'Each performance test has a specific protocol number that the exam likes to test directly.',
    },
    {
      kind: 'match', id: 'pt-match2', tags: ['cardio-tests'],
      prompt: 'Match each cardio test to its appropriate population.',
      pairs: [
        ['YMCA 3-minute step test', 'General / lower-fitness population (sub-maximal)'],
        ['Rockport 1-mile walk test', 'Deconditioned or older clients (sub-maximal)'],
        ['1.5-mile run test', 'Already-fit, athletic clients'],
      ],
      explanation: 'Match test intensity to client fitness — sub-maximal tests for general populations, the 1.5-mile run only for fit athletes.',
    },
    {
      kind: 'match', id: 'pt-match3', tags: ['posture'],
      prompt: 'Match each postural distortion syndrome to its description.',
      pairs: [
        ['Pes planus distortion syndrome', 'Flat feet, knee adduction and internal rotation'],
        ['Lower crossed syndrome', 'Anterior pelvic tilt with an arched low back'],
        ['Upper crossed syndrome', 'Rounded shoulders and forward head'],
      ],
      explanation: 'The three static postural distortion patterns commonly appear as scenario setups on the exam.',
    },
  ],
}
