import type { Module } from '../../types/content'

export const specialPopulations: Module = {
  id: 'd3-special-populations',
  domainId: 'd3',
  title: 'Special Populations & Chronic Disease',
  estMinutes: 35,
  lessons: [
    {
      id: 'sp-l1',
      title: 'Why chronic disease matters to a personal trainer',
      plain: `Chronic diseases and conditions (heart disease, diabetes, obesity, etc.) are the leading cause of death worldwide — far more than acute illnesses like the flu, which resolve. This is why NASM frames the personal trainer's role on the **healthcare continuum** as **preventive care**: helping otherwise-healthy clients avoid these long-term conditions through exercise, before they need medical treatment.`,
      nasm: `Chronic diseases and conditions represent the leading cause of death globally, distinguished from acute diseases (short-term, resolvable illnesses such as influenza). On the healthcare continuum, the Certified Personal Trainer's role is classified as preventive care, working with generally healthy populations to reduce the risk of chronic disease.`,
      mustMemorise: ['Chronic diseases/conditions = leading cause of death worldwide', 'A personal trainer\'s role on the healthcare continuum = preventive care'],
    },
    {
      id: 'sp-l2',
      title: 'Older adults',
      plain: `Older adults must complete the PAR-Q+ before starting any program with a trainer — this population carries higher baseline risk. Resistance training is especially valuable here because it directly combats **sarcopenia** (age-related loss of muscle mass, strength, and power) in a way that pure cardio doesn't. Bone health matters too: after roughly 10% bone density loss, hip fracture risk increases by about 2.5 times — another reason resistance training (which strengthens bone via Wolff's law) matters for aging clients.`,
      nasm: `Older adults must complete the PAR-Q+ prior to beginning an exercise program with a Certified Personal Trainer. Resistance training is a particularly effective intervention against sarcopenia — the age-related loss of muscle mass, strength, and power. A bone density loss of approximately 10% is associated with an approximately 2.5-fold increase in hip fracture risk, underscoring the value of resistance training for skeletal health in aging populations.`,
      mustMemorise: [
        'Older adults must complete PAR-Q+ before starting a program',
        'Resistance training is the key intervention against sarcopenia',
        '10% bone density loss → ~2.5x increase in hip fracture risk',
      ],
    },
    {
      id: 'sp-l3',
      title: 'Obesity',
      plain: `Obese clients need thoughtful exercise selection. Avoid supine (lying flat on the back) or prone (face-down) core positions early on — these can cause discomfort and blood-pressure swings (hypotensive/hypertensive reactions). Favor positions like the **incline plank** instead. A commonly cited minimum weekly energy-expenditure goal (combined activity + exercise) for obese clients is around 1,200 kcal.`,
      nasm: `For obese clients, core exercises should avoid supine or prone positions initially, favoring options such as the incline plank to maximize comfort and reduce risk of hypotensive or hypertensive reactions. A minimum weekly energy expenditure goal of approximately 1,200 kcal, from combined physical activity and exercise, is a commonly cited target for obese clients.`,
      mustMemorise: ['Avoid supine/prone core positions for obese clients early on; use incline plank instead', 'Minimum weekly energy-expenditure goal for obese clients: ~1,200 kcal'],
    },
    {
      id: 'sp-l4',
      title: 'Diabetes, hypertension, and other chronic conditions',
      plain: `**Type 1 diabetes**: the pancreas produces little or no insulin (often diagnosed young, requires insulin therapy). **Type 2 diabetes**: the body becomes resistant to insulin (often lifestyle-related, more common in adults, but not classified as "acute"). Trainers should be aware of medications and blood-sugar management around workouts but never prescribe treatment. Other conditions requiring awareness and appropriate program modification include hypertension, coronary heart disease, osteoporosis, arthritis, cancer, lung disease, and intermittent claudication (leg pain from reduced blood flow, often triggered by walking).`,
      nasm: `Type 1 diabetes results from insufficient insulin production by the pancreas. Type 2 diabetes results from insulin resistance and/or relative insulin deficiency, and is classified as a chronic condition. Certified Personal Trainers must be aware of, but not prescribe treatment for, chronic conditions including hypertension, coronary heart disease, osteoporosis, arthritis, cancer, lung disease, and intermittent claudication, adjusting program design appropriately and referring out as needed.`,
      mustMemorise: ['Type 1 diabetes = pancreas does not produce enough insulin', 'Both type 1 and type 2 diabetes are chronic (not acute) conditions'],
    },
    {
      id: 'sp-l5',
      title: 'Pregnancy and youth training',
      plain: `Pregnant clients and youth clients both need program modifications specific to their population — but the core principle for both is the same as any special population: screen appropriately, follow population-specific guidelines, and never exceed your scope of practice. For youth specifically, appropriate volume/rest guidelines differ from adult norms (e.g., SAQ training for young athletes is generally programmed at 1-4 sets per drill, versus other set ranges used for adult goals like weight loss).`,
      nasm: `Pregnant and youth clients each require population-specific modifications to standard program design, informed by current guidelines and appropriate screening. For SAQ (speed, agility, quickness) training specifically, young athletes are generally programmed for 1–4 sets per drill, which differs from set ranges used for other populations and goals.`,
      mustMemorise: ['SAQ training for young athletes: 1–4 sets per drill'],
    },
  ],
  items: [
    { kind: 'typein', id: 'sp-t1', tags: ['chronic-disease'], prompt: 'What type of health concern is the leading cause of death worldwide?', accept: ['chronic diseases and conditions', 'chronic disease', 'chronic diseases'], hints: ['Not "acute."', 'C_______ diseases and conditions'], explanation: 'Chronic diseases and conditions are the leading cause of death worldwide.' },
    { kind: 'typein', id: 'sp-t2', tags: ['chronic-disease'], prompt: 'On the healthcare continuum, how is a personal trainer\'s role classified?', accept: ['preventive care'], hints: ['Helping before problems start.', 'P_________ care'], explanation: 'A personal trainer\'s role is classified as preventive care.' },
    { kind: 'typein', id: 'sp-t3', tags: ['older-adults'], prompt: 'What must older adults complete before starting an exercise program with a trainer?', accept: ['par-q+', 'parq+'], hints: ['Same questionnaire as everyone, but non-negotiable here.', 'PAR-Q_'], explanation: 'Older adults must complete the PAR-Q+ before starting.' },
    { kind: 'typein', id: 'sp-t4', tags: ['older-adults'], prompt: 'What is the age-related loss of muscle mass, strength, and power called?', accept: ['sarcopenia'], hints: ['Opposite of "hypertrophy."', 'S________'], explanation: 'Sarcopenia is age-related loss of muscle mass, strength, and power; resistance training is the key countermeasure.' },
    { kind: 'typein', id: 'sp-t5', tags: ['older-adults'], prompt: 'A 10% loss of bone density increases hip fracture risk by roughly how many times?', accept: ['2.5', '2.5x', '2.5 times'], hints: ['A decimal number.', '_.5'], explanation: '10% bone density loss increases hip fracture risk by roughly 2.5x.' },
    { kind: 'typein', id: 'sp-t6', tags: ['obesity'], prompt: 'What core exercise position is best for obese clients to maximize comfort and avoid BP swings?', accept: ['incline plank'], hints: ['Not flat on the floor.', 'I______ plank'], explanation: 'The incline plank avoids the supine/prone positions that can cause discomfort and BP reactions in obese clients.' },
    { kind: 'typein', id: 'sp-t7', tags: ['obesity'], prompt: 'Minimum weekly energy expenditure goal (combined activity + exercise) commonly cited for obese clients?', accept: ['1200 kcal', '1,200 kcal', '1200'], hints: ['A 4-digit number.', '_,___ kcal'], explanation: 'A commonly cited minimum weekly target is ~1,200 kcal.' },
    { kind: 'typein', id: 'sp-t8', tags: ['diabetes'], prompt: 'In type 1 diabetes, what does the pancreas fail to produce enough of?', accept: ['insulin'], hints: ['Regulates blood sugar.', 'I______'], explanation: 'Type 1 diabetes results from insufficient insulin production.' },
    { kind: 'typein', id: 'sp-t9', tags: ['youth'], prompt: 'How many sets per SAQ drill are recommended for young athletes?', accept: ['1-4', '1 to 4 sets', '1-4 sets'], hints: ['A small range.', '_-_ sets'], explanation: 'Young athletes: 1–4 sets per SAQ drill.' },
    {
      kind: 'mcq', id: 'sp-m1', tags: ['diabetes'], source: 'original',
      prompt: 'Which individual is suffering from an acute (not chronic) disease?',
      options: ['Roger, who has type 2 diabetes', 'Jorge, who is sick with the flu', 'Tricia, who has type 1 diabetes', 'Perry, who has a congenital heart condition'],
      answer: 1,
      explanation: 'The flu is a short-term, acute illness, unlike the other three chronic, ongoing conditions.',
      whyWrong: ['Type 2 diabetes is chronic, not acute.', '', 'Type 1 diabetes is chronic, not acute.', 'A congenital heart condition is chronic/lifelong, not acute.'],
    },
    {
      kind: 'mcq', id: 'sp-m2', tags: ['older-adults'], source: 'original',
      prompt: 'Which activity is most effective for combating age-related loss of muscle mass, power, and strength?',
      options: ['Walking', 'General cardio', 'Resistance training', 'Aerobics'],
      answer: 2,
      explanation: 'Resistance training is the specific intervention shown to counter sarcopenia.',
      whyWrong: ['Walking is low-intensity cardio, not the primary countermeasure for strength/power loss.', 'General cardio does not specifically target muscle mass and strength preservation.', '', 'Aerobics primarily targets cardiorespiratory fitness, not muscle/strength preservation.'],
    },
    { kind: 'typein', id: 'sp-t10', tags: ['diabetes'], prompt: 'Which type of diabetes results from insulin RESISTANCE rather than insufficient production?', accept: ['type 2', 'type 2 diabetes'], hints: ['The more common, often lifestyle-related type.', 'Type _'], explanation: 'Type 2 diabetes results from insulin resistance and/or relative insulin deficiency.' },
    { kind: 'typein', id: 'sp-t11', tags: ['chronic-disease'], prompt: 'What term describes a short-term, resolvable illness such as the flu?', accept: ['acute', 'acute disease'], hints: ['Opposite of chronic.', 'A____'], explanation: 'Acute diseases are short-term and resolvable, unlike ongoing chronic conditions.' },
    { kind: 'typein', id: 'sp-t12', tags: ['special-populations'], prompt: 'What condition involves leg pain during walking caused by reduced blood flow?', accept: ['intermittent claudication', 'claudication'], hints: ['Two words, first means "on and off".', 'I___________ C___________'], explanation: 'Intermittent claudication is exercise-induced leg pain from impaired circulation.' },
    { kind: 'typein', id: 'sp-t13', tags: ['obesity'], prompt: 'Which two body positions should generally be avoided in early core work for obese clients?', accept: ['supine and prone', 'supine, prone'], hints: ['Lying on the back and on the front.', 'S_____ and P____'], explanation: 'Supine (on back) and prone (face down) positions can cause discomfort and blood-pressure reactions for obese clients.' },
    { kind: 'typein', id: 'sp-t14', tags: ['older-adults'], prompt: 'Which condition involves reduced bone mineral density severe enough to significantly raise fracture risk?', accept: ['osteoporosis'], hints: ['Porous bone.', 'O___________'], explanation: 'Osteoporosis is a condition of significantly reduced bone mineral density and elevated fracture risk.' },
    {
      kind: 'scenario', id: 'sp-s1', tags: ['obesity'],
      story: 'A trainer is programming core work for a client with obesity who reports dizziness when lying flat on their back.',
      question: 'Which exercise is most appropriate?',
      options: ['Supine floor crunches', 'Incline plank', 'Supine reverse crunches', 'Prone superman holds'],
      answer: 1,
      explanation: 'An incline position avoids the hypotensive/hypertensive reactions and discomfort that supine and prone positions can cause in obese clients.',
      whyWrong: ['Supine position is exactly what is causing the reported dizziness.', '', 'This is another supine position, carrying the same risk.', 'Prone positions also cause discomfort and pressure issues for this population.'],
    },
    {
      kind: 'scenario', id: 'sp-s2', tags: ['older-adults'],
      story: 'A 72-year-old client with diagnosed osteoporosis wants to begin training to reduce fracture risk.',
      question: 'What is the most appropriate primary training emphasis?',
      options: [
        'Exclusively seated machine cardio to avoid all impact',
        'Resistance training, which stimulates bone remodeling per Wolff\'s law',
        'Maximal-load powerlifting to maximize bone stress',
        'Static stretching only',
      ],
      answer: 1,
      explanation: 'Resistance training applies mechanical load that stimulates bone adaptation (Wolff\'s law) and counters both sarcopenia and bone density loss — with appropriate loads and screening.',
      whyWrong: ['Avoiding all loading forfeits the bone-building stimulus this client needs.', '', 'Maximal loads are inappropriate and unsafe for a client with osteoporosis.', 'Stretching alone provides no bone-loading stimulus.'],
    },
    {
      kind: 'scenario', id: 'sp-s3', tags: ['diabetes'],
      story: 'A client with type 1 diabetes arrives for a session and mentions they feel shaky, sweaty, and confused.',
      question: 'What is the trainer\'s most appropriate immediate action?',
      options: [
        'Begin the session to raise their blood glucose through exercise',
        'Stop, do not begin exercise, and follow emergency protocol — these are signs of hypoglycemia',
        'Have them perform maximal-effort intervals',
        'Ignore it, since these are normal pre-workout nerves',
      ],
      answer: 1,
      explanation: 'Shakiness, sweating, and confusion are classic hypoglycemia signs. Exercise would lower blood glucose further. Stop and follow emergency/medical protocol.',
      whyWrong: ['Exercise lowers blood glucose further, worsening hypoglycemia.', '', 'High-intensity exercise would be dangerous in this state.', 'These are recognized medical warning signs, not nerves.'],
    },
    {
      kind: 'mcq', id: 'sp-m3', tags: ['chronic-disease'], source: 'original',
      prompt: 'On the healthcare continuum, how is training with a fitness professional classified?',
      options: ['Physical therapy', 'Preventive care', 'Behavioral health', 'Alternative medicine'],
      answer: 1,
      explanation: 'A personal trainer works in preventive care — helping generally healthy clients reduce the risk of developing chronic disease.',
      whyWrong: ['Physical therapy is a licensed rehabilitative service outside a trainer\'s scope.', '', 'Behavioral health is a separate licensed mental-health field.', 'Personal training is not classified as alternative medicine.'],
    },
    {
      kind: 'mcq', id: 'sp-m4', tags: ['special-populations'], source: 'original',
      prompt: 'What must an older adult complete before beginning an exercise program with a CPT?',
      options: ['A dietary assessment', 'The PAR-Q+', 'An overhead squat assessment', 'A 1RM strength test'],
      answer: 1,
      explanation: 'The PAR-Q+ health screening must be completed before beginning a program — non-negotiable for older adults given elevated baseline risk.',
      whyWrong: ['Dietary assessment is not the required pre-exercise health screen.', '', 'Movement assessment follows health screening, not before.', 'A maximal strength test would be inappropriate before screening.'],
    },
    {
      kind: 'match', id: 'sp-match1', tags: ['special-populations'],
      prompt: 'Match each population to its key programming consideration.',
      pairs: [
        ['Older adults', 'PAR-Q+ required; resistance training combats sarcopenia'],
        ['Obese clients', 'Avoid supine/prone core positions; ~1,200 kcal/week expenditure goal'],
        ['Type 1 diabetes', 'Pancreas produces insufficient insulin; monitor for hypoglycemia'],
        ['Youth athletes', '1–4 sets per SAQ drill'],
      ],
      explanation: 'Each special population has signature considerations the exam tests through scenarios.',
    },
    {
      kind: 'match', id: 'sp-match2', tags: ['chronic-disease'],
      prompt: 'Classify each condition as acute or chronic.',
      pairs: [
        ['Influenza (the flu)', 'Acute'],
        ['Type 2 diabetes', 'Chronic'],
        ['Congenital heart condition', 'Chronic'],
      ],
      explanation: 'Acute conditions are short-term and resolvable; chronic conditions are ongoing and are the leading cause of death worldwide.',
    },
    { kind: 'typein', id: 'sp-t15', tags: ['special-populations'], prompt: 'Which population requires avoiding supine positions later in pregnancy?', accept: ['pregnant', 'pregnancy', 'pregnant clients'], hints: ['A temporary condition.', 'P________ clients'], explanation: 'Pregnant clients generally avoid prolonged supine positions, particularly in later stages.' },
    { kind: 'typein', id: 'sp-t16', tags: ['chronic-disease'], prompt: 'Chronic conditions are the leading cause of what, worldwide?', accept: ['death'], hints: ['The most serious outcome.', 'D____'], explanation: 'Chronic diseases and conditions are the leading cause of death worldwide.' },
    { kind: 'typein', id: 'sp-t17', tags: ['older-adults'], prompt: 'Which training modality best addresses both sarcopenia AND bone density in older adults?', accept: ['resistance training'], hints: ['Loading the body.', 'R________ training'], explanation: 'Resistance training simultaneously counters sarcopenia and stimulates bone adaptation.' },
  ],
}
