import type { Module } from '../../types/content'

export const modalities: Module = {
  id: 'd4-modalities',
  domainId: 'd4',
  title: 'Training Modalities & Equipment',
  estMinutes: 30,
  lessons: [
    {
      id: 'mod-l1',
      title: 'Battle ropes',
      plain: `Rope thickness changes the training effect. **2-inch ropes** are heavier and best for strength, power, and anaerobic work in short bouts (≤30 seconds). **1.5-inch ropes** are lighter, suited to longer, more endurance-oriented sets. Thicker = heavier = more strength/power demand; thinner = lighter = more endurance-friendly.`,
      nasm: `Battle rope diameter influences training adaptation: 2-inch diameter ropes are appropriate for strength, power, and anaerobic adaptations in bouts of 30 seconds or less, due to their greater mass and resistance. 1.5-inch diameter ropes are better suited to longer-duration, endurance-oriented work.`,
      mustMemorise: ['2 in. battle rope = strength/power/anaerobic, ≤30 sec bouts', '1.5 in. battle rope = longer, endurance-oriented work'],
    },
    {
      id: 'mod-l2',
      title: 'ViPR, medicine balls, and other loaded/explosive tools',
      plain: `**ViPR** (a weighted cylindrical tube) is specifically designed for "loaded movement training" — combining external load with dynamic, functional, multi-planar movement patterns, unlike a fixed-path machine. **Medicine balls** are ideal for pure explosive power work because they're thrown/released — no eccentric deceleration needed, unlike a dumbbell or barbell you have to control and re-rack. **Kettlebells** still require eccentric control (you have to catch/lower them), so they don't offer the same "no deceleration" benefit as a thrown medicine ball.`,
      nasm: `ViPR (Vitality, Performance, Reconditioning) tools are purpose-built for loaded movement training, combining external resistance with dynamic, functional, multiplanar movement. Medicine balls allow for maximally explosive movement without the need for eccentric deceleration, since the implement is released rather than caught or racked, distinguishing them from kettlebells or dumbbells which require eccentric control.`,
      mustMemorise: ['ViPR = purpose-built tool for loaded movement training', 'Medicine balls allow fully explosive movement with no eccentric deceleration needed'],
    },
    {
      id: 'mod-l3',
      title: 'Suspension trainers and other modalities',
      plain: `Suspended bodyweight training (like a TRX) uses the body's own weight anchored to a strap, challenging stability through an unstable, moving anchor point — but it still requires eccentric control as the body lowers, unlike a thrown medicine ball. Other common modalities: sandbags (shifting, unstable load), sleds (pure horizontal-force training, no eccentric component on the push), BOSU and stability balls (instability training), resistance bands (variable resistance, increasing tension through the range of motion), and wrist-worn heart rate monitors — which can give inaccurate readings during exercises with rapid, repetitive wrist motion (like catching and passing a medicine ball), since that motion disrupts the sensor.`,
      nasm: `Suspended bodyweight training utilizes an anchored strap system to challenge stability using the body's own mass, requiring eccentric control unlike a released implement. Additional modalities include sandbags (shifting/unstable load), sleds (horizontal force production), BOSU and stability balls (instability training), and resistance bands (variable/accommodating resistance). Wrist-worn heart rate monitors are prone to inaccurate readings during exercises involving rapid, repetitive wrist motion, such as catching and passing a medicine ball, due to sensor disruption.`,
      mustMemorise: ['Wrist-worn HR monitors are inaccurate during exercises with rapid wrist motion (e.g. medicine ball catch and pass)'],
    },
  ],
  items: [
    { kind: 'typein', id: 'mod-t1', tags: ['battle-ropes'], prompt: 'Which battle rope diameter is best for strength/power/anaerobic work in bouts of 30 seconds or less?', accept: ['2 in', '2 inches', '2 in.'], hints: ['The thicker rope.', '_ in.'], explanation: '2-inch ropes suit strength/power/anaerobic work in short bouts.' },
    { kind: 'typein', id: 'mod-t2', tags: ['battle-ropes'], prompt: 'Which battle rope diameter suits longer, endurance-oriented work?', accept: ['1.5 in', '1.5 inches', '1.5 in.'], hints: ['The thinner rope.', '_._ in.'], explanation: '1.5-inch ropes suit longer, endurance-oriented work.' },
    { kind: 'typein', id: 'mod-t3', tags: ['modalities'], prompt: 'Which training tool is purpose-built for "loaded movement training"?', accept: ['vipr'], hints: ['A weighted cylindrical tube.', 'V___'], explanation: 'ViPR is purpose-built for loaded movement training.' },
    { kind: 'typein', id: 'mod-t4', tags: ['modalities'], prompt: 'Which modality allows movement to be as explosive as possible without needing eccentric deceleration?', accept: ['medicine ball'], hints: ['Thrown, not caught and controlled.', 'M_______ B___'], explanation: 'Medicine balls allow fully explosive movement since there\'s no need to decelerate them eccentrically.' },
    { kind: 'typein', id: 'mod-t5', tags: ['modalities'], prompt: 'What exercise/motion may cause inaccurate readings on a wrist-worn heart rate monitor?', accept: ['medicine ball catch and pass', 'rapid wrist motion', 'catching and passing a medicine ball'], hints: ['Involves rapid, repetitive wrist movement.', 'M_______ ball catch and pass'], explanation: 'Rapid, repetitive wrist motion like medicine ball catch-and-pass disrupts wrist-worn HR monitor accuracy.' },
    {
      kind: 'mcq', id: 'mod-m1', tags: ['modalities'], source: 'original',
      prompt: 'Which of the following modality/exercise combinations provides the most demand on explosive power?',
      options: ['Barbell squat', 'Sandbag step-up', 'Medicine ball chest pass', 'Suspended bodyweight push-up'],
      answer: 2,
      explanation: 'A medicine ball chest pass is thrown explosively with no eccentric deceleration required, maximizing explosive power demand.',
      whyWrong: ['A controlled barbell squat is a strength movement, not a maximally explosive throw.', 'A sandbag step-up is a strength/stability exercise, not primarily explosive.', '', 'A suspended push-up is a stability-challenge exercise, not primarily an explosive-power one.'],
    },
    {
      kind: 'mcq', id: 'mod-m2', tags: ['battle-ropes'], source: 'original',
      prompt: 'When using battle ropes for strength/power/anaerobic adaptations in sets of 30 seconds or less, what rope diameter is best?',
      options: ['0.5 in.', '1 in.', '1.5 in.', '2 in.'],
      answer: 3,
      explanation: 'The thicker 2-inch rope is heavier and better suited to short, high-intensity strength/power work.',
      whyWrong: ['This is far too thin for strength/power work.', 'This is thinner than recommended for short, high-intensity sets.', 'This thickness suits longer, endurance-oriented sets, not short strength/power sets.', ''],
    },
    { kind: 'typein', id: 'mod-t6', tags: ['modalities'], prompt: 'Which modality uses an anchored strap system and the client\'s own bodyweight to challenge stability?', accept: ['suspended bodyweight training', 'suspension trainer', 'suspension training'], hints: ['TRX is the best-known brand.', 'S________ bodyweight training'], explanation: 'Suspended bodyweight training uses an anchored strap and bodyweight resistance.' },
    { kind: 'typein', id: 'mod-t7', tags: ['modalities'], prompt: 'Which modality provides variable resistance that increases as it is stretched further?', accept: ['resistance band', 'bands', 'resistance bands'], hints: ['Elastic.', 'R________ band'], explanation: 'Resistance bands provide variable (accommodating) resistance that increases through the range.' },
    { kind: 'typein', id: 'mod-t8', tags: ['modalities'], prompt: 'Which modality provides an unstable, shifting external load?', accept: ['sandbag', 'sandbags'], hints: ['Filled with a shifting material.', 'S______'], explanation: 'Sandbags provide a shifting, unstable external load.' },
    { kind: 'typein', id: 'mod-t9', tags: ['modalities'], prompt: 'What term describes the type of training ViPR is specifically designed for?', accept: ['loaded movement training'], hints: ['Three words.', 'L_____ M________ T_______'], explanation: 'ViPR is purpose-built for loaded movement training — load combined with dynamic, multiplanar movement.' },
    {
      kind: 'scenario', id: 'mod-s1', tags: ['modalities'],
      story: 'A trainer wants a client to perform maximally explosive upper-body power work with no need to decelerate the implement at the end of the movement.',
      question: 'Which modality best fits?',
      options: ['Kettlebell', 'Medicine ball', 'Resistance band', 'Suspension trainer'],
      answer: 1,
      explanation: 'A medicine ball is released/thrown, removing the eccentric deceleration requirement and allowing full acceleration throughout.',
      whyWrong: ['A kettlebell must be caught or decelerated, requiring eccentric control.', '', 'A band pulls the limb back, requiring eccentric control on the return.', 'Suspension training requires eccentric control of bodyweight throughout.'],
    },
    {
      kind: 'scenario', id: 'mod-s2', tags: ['modalities', 'monitoring'],
      story: 'A client wearing a wrist-based heart rate monitor performs a medicine ball catch-and-pass circuit. The trainer notices the heart rate readings look erratic and implausible.',
      question: 'What is the most likely explanation?',
      options: [
        'The client\'s heart rate genuinely spiked and crashed repeatedly',
        'Rapid, repetitive wrist motion disrupts the optical sensor, causing inaccurate readings',
        'Medicine balls interfere with Bluetooth signals',
        'Wrist monitors do not work during any resistance training',
      ],
      answer: 1,
      explanation: 'Wrist-worn optical HR monitors lose accuracy during exercises with rapid, repetitive wrist movement, which disrupts sensor contact and signal quality.',
      whyWrong: ['Physiological heart rate does not oscillate that erratically during steady circuit work.', '', 'There is no meaningful signal interference from a medicine ball.', 'Wrist monitors work adequately during many exercises; the issue is specifically rapid wrist motion.'],
    },
    {
      kind: 'scenario', id: 'mod-s3', tags: ['battle-ropes'],
      story: 'A trainer programs battle rope waves in 20-second all-out bursts to develop anaerobic power.',
      question: 'Which rope should be selected?',
      options: ['1 in. diameter', '1.5 in. diameter', '2 in. diameter', 'Rope diameter is irrelevant'],
      answer: 2,
      explanation: 'The heavier 2-inch rope is appropriate for strength, power, and anaerobic adaptations in bouts of 30 seconds or less.',
      whyWrong: ['Too thin to provide the resistance needed for power/anaerobic adaptation.', 'This thickness suits longer, endurance-oriented work.', '', 'Diameter directly determines the load and therefore the adaptation.'],
    },
    {
      kind: 'mcq', id: 'mod-m3', tags: ['modalities'], source: 'original',
      prompt: 'Loaded movement training is best achieved with which modality?',
      options: ['Speed ladder', 'Strength machines', 'ViPR', 'Foam roller'],
      answer: 2,
      explanation: 'ViPR is designed specifically for loaded movement training — combining external load with dynamic, functional, multiplanar movement.',
      whyWrong: ['Speed ladders train footwork and agility with no external load.', 'Machines fix the movement path, the opposite of free multiplanar movement.', '', 'A foam roller is an SMR tool, not a loading modality.'],
    },
    {
      kind: 'mcq', id: 'mod-m4', tags: ['modalities'], source: 'original',
      prompt: 'Which modality would be the LEAST appropriate choice for training explosive power?',
      options: ['Medicine ball', 'Strength machine with a fixed path', 'Kettlebell', 'Free weights performed explosively'],
      answer: 1,
      explanation: 'A fixed-path strength machine restricts movement velocity and natural mechanics, making it the least suitable for developing explosive power.',
      whyWrong: ['Medicine balls are among the best power tools.', '', 'Kettlebells can be used for explosive movements like swings and cleans.', 'Free weights can be moved explosively for power work.'],
    },
    {
      kind: 'mcq', id: 'mod-m5', tags: ['modalities'], source: 'original',
      prompt: 'Which tool is primarily used for instability training rather than external loading?',
      options: ['Barbell', 'Sled', 'BOSU / stability ball', 'Battle rope'],
      answer: 2,
      explanation: 'BOSU trainers and stability balls create an unstable surface to challenge balance and neuromuscular control rather than adding external load.',
      whyWrong: ['A barbell provides external load on a stable base.', 'A sled provides horizontal external loading.', '', 'Battle ropes provide external load and metabolic demand, not surface instability.'],
    },
    {
      kind: 'mcq', id: 'mod-m6', tags: ['modalities'], source: 'original',
      prompt: 'Which modality provides horizontal force production training with essentially no eccentric component on the pushing phase?',
      options: ['Sled push', 'Stability ball', 'Suspension trainer', 'Foam roller'],
      answer: 0,
      explanation: 'A sled push is pure concentric horizontal force production — there is no eccentric lowering phase in the push.',
      whyWrong: ['', 'A stability ball is an instability tool, not a horizontal loading tool.', 'Suspension training involves substantial eccentric control.', 'A foam roller is an SMR tool.'],
    },
    {
      kind: 'match', id: 'mod-match1', tags: ['modalities'],
      prompt: 'Match each modality to its defining training purpose.',
      pairs: [
        ['ViPR', 'Loaded movement training'],
        ['Medicine ball', 'Explosive power with no eccentric deceleration'],
        ['BOSU / stability ball', 'Instability and balance training'],
        ['Sled', 'Horizontal force production'],
      ],
      explanation: 'Each modality has a distinct primary purpose that the exam frequently tests by scenario.',
    },
    {
      kind: 'match', id: 'mod-match2', tags: ['battle-ropes'],
      prompt: 'Match each battle rope diameter to its intended use.',
      pairs: [
        ['2 in. diameter', 'Strength, power, anaerobic — bouts of 30s or less'],
        ['1.5 in. diameter', 'Longer, endurance-oriented work'],
      ],
      explanation: 'Thicker equals heavier, which suits short high-intensity work; thinner suits longer endurance sets.',
    },
    { kind: 'typein', id: 'mod-t10', tags: ['modalities'], prompt: 'Which modality provides horizontal loading with essentially no eccentric phase on the push?', accept: ['sled', 'sled push'], hints: ['You push it along the ground.', 'S___'], explanation: 'A sled push is pure concentric horizontal force production.' },
    { kind: 'typein', id: 'mod-t11', tags: ['modalities'], prompt: 'Which modality uses a half-dome unstable surface for balance training?', accept: ['bosu', 'bosu ball'], hints: ['Four letters.', 'B___'], explanation: 'A BOSU trainer provides an unstable surface for balance and stabilization work.' },
    { kind: 'typein', id: 'mod-t12', tags: ['modalities'], prompt: 'Which modality is a cast-iron weight with a handle, commonly used for swings?', accept: ['kettlebell'], hints: ['Has a handle on top.', 'K_________'], explanation: 'Kettlebells are used for swings, cleans, and other ballistic movements requiring eccentric control.' },
    { kind: 'typein', id: 'mod-t13', tags: ['modalities'], prompt: 'Which tool is used for self-myofascial release?', accept: ['foam roller', 'roller'], hints: ['You roll on it.', 'F___ R_____'], explanation: 'A foam roller is the standard SMR tool.' },
    { kind: 'typein', id: 'mod-t14', tags: ['modalities'], prompt: 'Which modality trains footwork and agility patterns without external load?', accept: ['speed ladder', 'agility ladder', 'ladder'], hints: ['Laid flat on the floor.', 'S____ L_____'], explanation: 'Speed/agility ladders train footwork and quickness patterns.' },
  ],
}
