import type { Module } from '../../types/content'

export const resistanceTechnique: Module = {
  id: 'd4-resistance-technique',
  domainId: 'd4',
  title: 'Resistance Training Technique & Exercise Selection',
  estMinutes: 40,
  lessons: [
    {
      id: 'rt-l1',
      title: 'Matching exercises to OPT phase',
      plain: `Every exercise fits somewhere on the stabilization-to-power spectrum. Phase 1 exercises emphasize control on unstable/challenging surfaces (e.g. a stability ball push-up). Phase 3-4 exercises emphasize heavy, stable, well-grooved compound lifts (e.g. a barbell squat, shoulder/military press). Phase 5 exercises emphasize speed and explosiveness with lighter loads (e.g. a squat jump, medicine ball throw). Picking the right exercise for a phase is a common exam trap — e.g. a shoulder/military press fits Phase 4 (Maximal Strength) far better than a stability-ball push-up (which is a Phase 1 stabilization exercise) or a squat jump (Phase 5 power).`,
      nasm: `Exercise selection should align with the acute variables and training goal of the current OPT phase. Phase 1 exercises typically incorporate unstable or destabilizing elements (e.g., stability ball push-up) to build stabilization capacity. Phases 3–4 emphasize stable, heavily loadable compound movements (e.g., barbell squat, shoulder/military press) for hypertrophy and maximal strength. Phase 5 emphasizes lighter-load, high-velocity movements (e.g., squat jump, medicine ball throw) to develop power.`,
      mustMemorise: ['Phase 1 exercises emphasize instability/control; Phase 4 emphasizes heavy stable compound lifts; Phase 5 emphasizes light, fast, explosive movements'],
    },
    {
      id: 'rt-l2',
      title: 'Common power-focused exercises',
      plain: `Power exercises move a lighter load as fast/explosively as possible. Classic examples: medicine ball soccer throw, medicine ball chest pass, squat jump. These contrast with strength-focused exercises like a bench press or barbell squat performed at a controlled tempo, which build maximal force rather than speed. Among power options, a *thrown* implement like a medicine ball demands the most pure explosive power, since there's no need to decelerate it eccentrically the way you would a barbell — it's released rather than caught and controlled.`,
      nasm: `Power-focused resistance training exercises, such as the medicine ball soccer throw, chest pass, or squat jump, emphasize maximal velocity movement with lighter loads. Thrown implements such as medicine balls place the greatest demand on pure explosive power output, as they require no eccentric deceleration of the load, unlike a caught or racked implement.`,
      mustMemorise: ['Medicine ball throws demand the most explosive power since no eccentric deceleration is needed'],
    },
    {
      id: 'rt-l3',
      title: 'Local vs. global core, and floor bridge technique',
      plain: `(Cross-reference with the Core/Balance/Plyo/SAQ module.) One frequently tested detail: on a floor bridge, don't raise the hips too far off the floor — doing so hyperextends (arches) the lumbar spine, placing excessive stress on the low back. The correct cue is to keep the body in a straight line from shoulders to knees, not arched.`,
      nasm: `During the floor bridge exercise, excessive hip elevation places the lumbar spine into hyperextension, creating undue stress. Proper technique maintains a neutral spine with a straight line from shoulders through knees at the top of the movement.`,
      mustMemorise: ['Floor bridge: don\'t raise hips too high — risks lumbar hyperextension, not hyperflexion'],
    },
    {
      id: 'rt-l4',
      title: 'Global core exercise extensibility: the medicine ball pullover throw',
      plain: `Some exercises require adequate flexibility in a specific muscle before they can be performed safely. The medicine ball pullover throw moves the arms from overhead down and back — this requires good extensibility (length) in the **latissimus dorsi**, a global core/shoulder muscle. If the lats are too tight, this throw can strain the shoulder or force compensation elsewhere.`,
      nasm: `Proper extensibility of the latissimus dorsi is a prerequisite for safely performing the medicine ball pullover throw, given the muscle's role in controlling the overhead-to-extended shoulder pattern the exercise requires.`,
      mustMemorise: ['Medicine ball pullover throw requires good latissimus dorsi extensibility'],
    },
  ],
  items: [
    { kind: 'typein', id: 'rt-t1', tags: ['exercise-selection'], prompt: 'Which OPT phase is a stability ball push-up most appropriate for?', accept: ['phase 1', '1'], hints: ['The stabilization phase.', 'Phase _'], explanation: 'A stability ball push-up is a Phase 1 stabilization-emphasis exercise.' },
    { kind: 'typein', id: 'rt-t2', tags: ['exercise-selection'], prompt: 'Which OPT phase is a squat jump most appropriate for?', accept: ['phase 5', '5'], hints: ['The power phase.', 'Phase _'], explanation: 'A squat jump is a Phase 5 power exercise.' },
    { kind: 'typein', id: 'rt-t3', tags: ['exercise-selection'], prompt: 'Name a common power-focused resistance exercise using a thrown implement.', accept: ['medicine ball soccer throw', 'medicine ball chest pass', 'medicine ball throw'], hints: ['Involves a medicine ball.', 'M_______ B___ throw'], explanation: 'Medicine ball throws (soccer throw, chest pass) are classic power-focused exercises.' },
    { kind: 'typein', id: 'rt-t4', tags: ['technique'], prompt: 'On a floor bridge, raising the hips too high risks what spinal issue?', accept: ['lumbar hyperextension', 'hyperextension of the lumbar spine'], hints: ['Arching, not rounding.', 'L_____ H____________'], explanation: 'Excessive hip elevation on a floor bridge risks lumbar hyperextension.' },
    { kind: 'typein', id: 'rt-t5', tags: ['technique'], prompt: 'Good extensibility of which muscle is needed before a medicine ball pullover throw?', accept: ['latissimus dorsi', 'lats'], hints: ['A large back muscle.', 'L_________ D____'], explanation: 'The latissimus dorsi needs good extensibility for a safe medicine ball pullover throw.' },
    {
      kind: 'mcq', id: 'rt-m1', tags: ['exercise-selection'], source: 'original',
      prompt: 'Which exercise is most appropriate for a maximal strength movement in Phase 4?',
      options: ['Single-leg dumbbell curl to shoulder press', 'Stability ball push-up', 'Shoulder/military press', 'Squat jump'],
      answer: 2,
      explanation: 'A straightforward, heavily-loadable compound lift like the shoulder/military press fits Phase 4\'s heavy, low-rep focus.',
      whyWrong: ['This multi-step, stabilization-focused exercise fits Phase 1–2, not heavy Phase 4 loading.', 'A stability ball push-up is a Phase 1 stabilization exercise, not a max-strength loadable movement.', '', 'A squat jump is a Phase 5 power exercise, not a maximal-strength one.'],
    },
    {
      kind: 'mcq', id: 'rt-m2', tags: ['technique'], source: 'original',
      prompt: 'Why should you avoid raising the hips too far off the floor during a floor bridge?',
      options: [
        'It may place too much stress on the lumbar spine through hyperflexion.',
        'It may place too much stress on the cervical spine.',
        'It may place excessive stress on the thoracic spine.',
        'It may place excessive stress on the lumbar spine through hyperextension.',
      ],
      answer: 3,
      explanation: 'Raising the hips too high arches (hyperextends) the lower back.',
      whyWrong: ['The risk is hyperextension, not hyperflexion.', 'The cervical spine is not the primary concern here.', 'The thoracic spine is not the primary concern here.', ''],
    },
    { kind: 'typein', id: 'rt-t6', tags: ['systems'], prompt: 'Which resistance training system uses a progressive or regressive step approach, changing weight with each set?', accept: ['pyramid system', 'pyramid'], hints: ['Named after a shape.', 'P______ system'], explanation: 'The pyramid system steps load up (or down) across successive sets.' },
    { kind: 'typein', id: 'rt-t7', tags: ['systems'], prompt: 'Which resistance training system pairs two exercises performed back-to-back with no rest?', accept: ['superset', 'superset system'], hints: ['Defines Phase 2 programming.', 'S________'], explanation: 'A superset pairs two exercises back-to-back with no rest between them.' },
    { kind: 'typein', id: 'rt-t8', tags: ['systems'], prompt: 'Which resistance training system alternates upper-body and lower-body exercises to distribute blood flow?', accept: ['peripheral heart action', 'peripheral heart action system'], hints: ['Named for its circulatory effect.', 'P__________ H____ A_____'], explanation: 'Peripheral heart action alternates upper and lower body exercises throughout a circuit.' },
    { kind: 'typein', id: 'rt-t9', tags: ['systems'], prompt: 'Which resistance training system pairs a heavy strength exercise with a biomechanically similar explosive exercise?', accept: ['complex training', 'complex'], hints: ['Defines Phase 5 programming.', 'C______ training'], explanation: 'Complex training pairs a heavy lift with a similar explosive movement — the Phase 5 structure.' },
    { kind: 'typein', id: 'rt-t10', tags: ['systems'], prompt: 'What loading system performs all sets of one exercise before moving to the next (as opposed to rotating through exercises)?', accept: ['horizontal loading', 'horizontal'], hints: ['Think of reading across a row.', 'H________ loading'], explanation: 'Horizontal loading completes all sets of one exercise before moving on; vertical loading rotates through exercises.' },
    { kind: 'typein', id: 'rt-t11', tags: ['systems'], prompt: 'What loading system moves down a list of exercises one set at a time, then repeats?', accept: ['vertical loading', 'vertical'], hints: ['Think of reading down a column.', 'V_______ loading'], explanation: 'Vertical loading moves down the exercise list one set each, then cycles back to the top.' },
    { kind: 'typein', id: 'rt-t12', tags: ['technique'], prompt: 'Which muscle action produces the highest energy cost at a fixed resistance?', accept: ['concentric'], hints: ['The lifting portion.', 'C________'], explanation: 'Concentric (shortening) actions cost the most metabolic energy at a given fixed load.' },
    {
      kind: 'scenario', id: 'rt-s1', tags: ['exercise-selection'],
      story: 'A trainer needs to select a chest exercise for a client in Phase 1 (Stabilization Endurance).',
      question: 'Which is the most phase-appropriate choice?',
      options: [
        'Heavy barbell bench press at 90% 1RM',
        'Stability ball push-up',
        'Explosive medicine ball chest pass',
        'Machine chest press at 85% 1RM',
      ],
      answer: 1,
      explanation: 'Phase 1 emphasizes stabilization, so an unstable-surface bodyweight exercise like a stability ball push-up fits the phase intent.',
      whyWrong: ['90% 1RM is Phase 4 maximal-strength loading, far beyond Phase 1.', '', 'Explosive throws are Phase 5 power work.', '85% 1RM is Phase 3–4 loading, not Phase 1.'],
    },
    {
      kind: 'scenario', id: 'rt-s2', tags: ['technique'],
      story: 'During a floor bridge, a client lifts their hips as high as possible and reports low back discomfort at the top.',
      question: 'What is the most likely cause and correction?',
      options: [
        'Lumbar hyperextension from over-elevating the hips; cue a neutral spine in a straight shoulder-to-knee line',
        'Lumbar hyperflexion from not lifting high enough; cue a higher lift',
        'Cervical strain; cue a chin tuck',
        'Hamstring cramping; cue more hip flexion',
      ],
      answer: 0,
      explanation: 'Lifting the hips too high arches (hyperextends) the lumbar spine. The correction is a neutral spine with a straight line from shoulders through knees.',
      whyWrong: ['', 'The problem is too much extension, not flexion, and lifting higher would worsen it.', 'The discomfort described is lumbar, not cervical.', 'Hamstring cramping is a different issue and would not be corrected by more hip flexion.'],
    },
    {
      kind: 'scenario', id: 'rt-s3', tags: ['exercise-selection'],
      story: 'A client is in Phase 5 (Power). The trainer programs a barbell squat at 90% 1RM supersetted with a squat jump at approximately 30% 1RM, resting 4 minutes between pairs.',
      question: 'Is this programming correct?',
      options: [
        'No — the rest is too long for Phase 5',
        'No — the power exercise load is too light',
        'Yes — this matches Phase 5 acute variables exactly',
        'No — Phase 5 does not use supersets',
      ],
      answer: 2,
      explanation: 'Phase 5 pairs a heavy strength lift (85–100% 1RM) with a similar explosive movement (30–45% 1RM), resting 3–5 minutes between pairs. This is textbook.',
      whyWrong: ['3–5 minutes is exactly the prescribed Phase 5 rest.', '30% falls within the 30–45% power-load range.', '', 'Phase 5 is specifically built on supersetted strength/power pairs.'],
    },
    {
      kind: 'mcq', id: 'rt-m3', tags: ['systems'], source: 'original',
      prompt: 'Which system involves performing a set, reducing the load, and immediately continuing without rest?',
      options: ['Drop set', 'Pyramid system', 'Circuit training', 'Split routine'],
      answer: 0,
      explanation: 'A drop set reduces load mid-set and continues immediately to extend the set past initial fatigue.',
      whyWrong: ['', 'A pyramid steps load across separate sets with rest between them, not within a single continuous set.', 'Circuit training moves between different exercises, not reduced loads of the same exercise.', 'A split routine organizes which body parts are trained on which days.'],
    },
    {
      kind: 'mcq', id: 'rt-m4', tags: ['exercise-selection'], source: 'original',
      prompt: 'Which exercise is a common POWER-focused resistance exercise?',
      options: ['Machine leg press', 'Medicine ball soccer throw', 'Dumbbell lateral raise', 'Seated cable row'],
      answer: 1,
      explanation: 'A medicine ball throw is released explosively with no eccentric deceleration — a hallmark power exercise.',
      whyWrong: ['A machine leg press is a controlled strength exercise.', '', 'A lateral raise is an isolation strength exercise.', 'A cable row is a controlled strength/stabilization exercise.'],
    },
    {
      kind: 'mcq', id: 'rt-m5', tags: ['technique'], source: 'original',
      prompt: 'Why does a medicine ball throw demand more explosive power than a dumbbell press of comparable load?',
      options: [
        'Medicine balls are always heavier',
        'The ball is released, so no eccentric deceleration is required, allowing full acceleration through the movement',
        'Medicine balls activate more motor units by design',
        'Dumbbells cannot be moved quickly',
      ],
      answer: 1,
      explanation: 'Because the implement leaves the hands, the client never has to decelerate it — allowing maximal acceleration all the way through, unlike a dumbbell that must be slowed and controlled.',
      whyWrong: ['Medicine balls are typically lighter, not heavier.', '', 'Motor unit recruitment is driven by force/velocity demand, not the implement itself.', 'Dumbbells can be moved quickly, but must still be decelerated at the end of range.'],
    },
    {
      kind: 'match', id: 'rt-match1', tags: ['systems'],
      prompt: 'Match each resistance training system to its description.',
      pairs: [
        ['Pyramid system', 'Steps weight up or down with each successive set'],
        ['Superset', 'Two exercises back-to-back with no rest'],
        ['Complex training', 'Heavy strength lift paired with a similar explosive movement'],
        ['Peripheral heart action', 'Alternates upper- and lower-body exercises through a circuit'],
      ],
      explanation: 'These four systems are commonly confused on the exam — each has a distinct defining structure.',
    },
    {
      kind: 'match', id: 'rt-match2', tags: ['exercise-selection'],
      prompt: 'Match each exercise to its most appropriate OPT phase.',
      pairs: [
        ['Stability ball push-up', 'Phase 1 – Stabilization'],
        ['Shoulder/military press at 90% 1RM', 'Phase 4 – Maximal Strength'],
        ['Squat jump', 'Phase 5 – Power'],
      ],
      explanation: 'Exercise selection should match the phase intent: instability for Phase 1, heavy loadable compounds for Phase 4, explosive movements for Phase 5.',
    },
    { kind: 'typein', id: 'rt-t13', tags: ['systems'], prompt: 'Which training system performs one set of an exercise with minimal rest before moving to a different exercise, cycling through many?', accept: ['circuit training', 'circuit'], hints: ['Move station to station.', 'C______ training'], explanation: 'Circuit training moves through multiple exercises with minimal rest between them.' },
    { kind: 'typein', id: 'rt-t14', tags: ['systems'], prompt: 'Which training system performs only one set per exercise?', accept: ['single-set', 'single set system', 'single-set system'], hints: ['The simplest system.', 'S_____-___ system'], explanation: 'The single-set system performs one set per exercise.' },
    { kind: 'typein', id: 'rt-t15', tags: ['systems'], prompt: 'Which training system organizes training by body region across different days?', accept: ['split routine', 'split'], hints: ['Divide the body up.', 'S____ routine'], explanation: 'A split routine divides training across days by body region or movement pattern.' },
    { kind: 'typein', id: 'rt-t16', tags: ['technique'], prompt: 'Which muscle action involves the muscle lengthening under load?', accept: ['eccentric'], hints: ['The lowering phase.', 'E_________'], explanation: 'An eccentric action is the muscle lengthening while producing force.' },
  ],
}
