import type { Module } from '../../types/content'

export const communication: Module = {
  id: 'd5-communication',
  domainId: 'd5',
  title: 'Communication & Motivational Interviewing',
  estMinutes: 30,
  lessons: [
    {
      id: 'comm-l1',
      title: 'Questions that promote change vs. questions that shut it down',
      plain: `How you ask a question matters as much as what you ask. Open, curious, non-judgmental questions ("What might you want to change?") invite the client to talk themselves into motivation. Confrontational or "why" questions that challenge the client ("Why can't you make this change?" or "Why don't you just do this?") tend to trigger defensiveness instead of progress, even when well-intentioned.`,
      nasm: `Questions that promote change are open, non-judgmental, and invite client reflection (e.g., "What might you want to change?"). Confrontational or directive phrasing (e.g., "Why can't you...", "Why don't you just...") tends to elicit defensiveness ("sustain talk") rather than client-driven change talk, and should be avoided in motivational interviewing.`,
      mustMemorise: ['Change-promoting questions are open and non-judgmental, not confrontational "why can\'t you" phrasing'],
    },
    {
      id: 'comm-l2',
      title: 'Closed vs. open-ended questions',
      plain: `A **closed-ended** question can be answered with a single word (often yes/no) — "Did you drink enough water today?" An **open-ended** question requires the client to explain, elaborate, reflect — "Why do you want to lose weight?" is technically phrased with "why," but functionally it's still open-ended because it requires an explanatory answer, not a yes/no.`,
      nasm: `Closed-ended questions can be answered with a brief, often binary response. Open-ended questions require elaboration and cannot be answered with a simple yes or no, even when phrased starting with "why," "what," or "how" — the defining feature is whether the response requires explanation.`,
      mustMemorise: ['Open-ended questions require explanation; closed-ended questions can be answered in one word'],
    },
    {
      id: 'comm-l3',
      title: 'Reflections vs. reflective listening vs. active listening',
      plain: `These three terms are related but distinct, and exam questions love testing the difference. **Active listening** is the overall skill/practice of fully attending to what someone says. **Reflective listening** is specifically restating the client's goals/words back to confirm understanding ("So it sounds like you want to feel stronger for your kids"). A **reflection** is a statement that helps the listener express the supposed underlying meaning of what was just said (going a layer deeper than just repeating words — naming the feeling or meaning behind them).`,
      nasm: `Active listening is the general practice of fully attending to and processing what a client communicates. Reflective listening is the specific technique of restating a client's stated content back to them to confirm understanding. A reflection is a statement that articulates the supposed underlying meaning or feeling behind what the client has expressed, going beyond simple restatement.`,
      mustMemorise: [
        'Active listening = the general skill of attentive listening',
        'Reflective listening = restating the client\'s words back to confirm understanding',
        'Reflections = expressing the underlying meaning behind what was said',
      ],
    },
    {
      id: 'comm-l4',
      title: 'Leadership qualities',
      plain: `NASM frames good trainer leadership around a specific set of traits — being optimistic, empathetic, knowledgeable, and a genuine role model for a healthy, balanced life. This bundle of traits is referred to specifically as the leader's qualities (distinct from "leadership style," which is about how a leader manages/interacts, not the underlying character traits themselves).`,
      nasm: `Leader's qualities refer to the personal characteristics that make a trainer an effective role model and leader, including optimism, empathy, and knowledge, exemplified by living a healthy and balanced life. This is distinct from leadership style, which describes behavioral approach rather than underlying character traits.`,
      mustMemorise: ['Leader\'s qualities = optimistic, empathetic, knowledgeable, role model for a healthy/balanced life'],
    },
  ],
  items: [
    { kind: 'typein', id: 'comm-t1', tags: ['questions'], prompt: 'What kind of question can be answered with a single word, often yes/no?', accept: ['closed-ended', 'closed ended', 'closed'], hints: ['The opposite of open-ended.', 'C_____-E____'], explanation: 'A closed-ended question can be answered briefly, often yes/no.' },
    { kind: 'typein', id: 'comm-t2', tags: ['questions'], prompt: 'What kind of question requires the client to explain or elaborate?', accept: ['open-ended', 'open ended', 'open'], hints: ['Can\'t be answered with one word.', 'O___-E____'], explanation: 'Open-ended questions require elaboration.' },
    { kind: 'typein', id: 'comm-t3', tags: ['listening'], prompt: 'What is it called when a trainer restates the client\'s words back to confirm understanding?', accept: ['reflective listening'], hints: ['Involves "reflective."', 'R__________ L________'], explanation: 'Reflective listening is restating a client\'s words back to confirm understanding.' },
    { kind: 'typein', id: 'comm-t4', tags: ['listening'], prompt: 'What term describes a statement expressing the underlying meaning behind what a client said?', accept: ['reflection', 'reflections'], hints: ['Singular, not "reflective listening."', 'R_________'], explanation: 'A reflection expresses the underlying meaning behind what was said.' },
    { kind: 'typein', id: 'comm-t5', tags: ['leadership'], prompt: 'What term describes a trainer\'s optimism, empathy, knowledge, and role-modeling of a healthy life?', accept: ['leaders qualities', 'leader\'s qualities'], hints: ['Two words.', 'L______\'s Q________'], explanation: 'These traits are called the leader\'s qualities.' },
    {
      kind: 'mcq', id: 'comm-m1', tags: ['questions'], source: 'original',
      prompt: 'Which of the following is a question that may promote change?',
      options: ['What might you want to change?', 'Why can\'t you make this change to your schedule?', 'What makes you think that you\'re not at risk?', 'Why don\'t you just do this?'],
      answer: 0,
      explanation: 'Open, non-judgmental questions that invite the client to reflect promote change talk.',
      whyWrong: ['', 'A "why can\'t you" framing is confrontational and tends to trigger defensiveness.', 'This is a challenging, judgmental framing.', 'This is a directive framing that pushes the trainer\'s agenda rather than eliciting the client\'s own motivation.'],
    },
    {
      kind: 'mcq', id: 'comm-m2', tags: ['listening'], source: 'original',
      prompt: 'A trainer listens to a client\'s goals, then restates those goals back to the client. What is this an example of?',
      options: ['Reflective listening', 'Motivational interviewing', 'Nonverbal communication', 'A reflection'],
      answer: 0,
      explanation: 'Restating what the client said back to them, to confirm understanding, is reflective listening.',
      whyWrong: ['', 'Motivational interviewing is the broader counseling style, of which reflective listening is one technique.', 'Restating the client\'s words is verbal, not nonverbal.', 'A reflection would articulate the underlying meaning/feeling, not just restate the content.'],
    },
    {
      kind: 'match', id: 'comm-match1', tags: ['listening'],
      prompt: 'Match each communication term to its definition.',
      pairs: [
        ['Active listening', 'The general skill of fully attending to what a client says'],
        ['Reflective listening', 'Restating the client\'s stated content back to confirm understanding'],
        ['Reflection', 'A statement expressing the underlying meaning behind what was said'],
      ],
      explanation: 'Active listening is the general skill; reflective listening restates content; a reflection goes deeper to name the underlying meaning.',
    },
    { kind: 'typein', id: 'comm-t6', tags: ['motivational-interviewing'], prompt: 'What is the counseling style built on OARS techniques, designed to elicit the client\'s own motivation?', accept: ['motivational interviewing'], hints: ['Two words.', 'M___________ I___________'], explanation: 'Motivational interviewing is the broader counseling style; OARS are its core techniques.' },
    { kind: 'typein', id: 'comm-t7', tags: ['motivational-interviewing'], prompt: 'What term describes client statements expressing a desire, reason, or commitment to change?', accept: ['change talk'], hints: ['Two words.', 'C_____ T___'], explanation: 'Change talk is client language favoring change — the target of motivational interviewing.' },
    { kind: 'typein', id: 'comm-t8', tags: ['communication'], prompt: 'Body language, tone, and facial expression fall under what category of communication?', accept: ['nonverbal', 'non-verbal', 'nonverbal communication'], hints: ['Not spoken.', 'N________ communication'], explanation: 'Nonverbal communication includes body language, tone, and facial expression.' },
    { kind: 'typein', id: 'comm-t9', tags: ['communication'], prompt: 'A statement recognizing a client\'s genuine strength or effort is called what (the "A" in OARS)?', accept: ['affirmation', 'affirmations'], hints: ['Recognizing something real and positive.', 'A___________'], explanation: 'An affirmation recognizes the client\'s genuine strengths and efforts.' },
    { kind: 'typein', id: 'comm-t10', tags: ['communication'], prompt: 'Pulling together several things a client said into one recap is which OARS technique?', accept: ['summary', 'summaries'], hints: ['The "S".', 'S_______'], explanation: 'A summary consolidates what the client has expressed across a conversation.' },
    {
      kind: 'scenario', id: 'comm-s1', tags: ['communication'],
      story: 'A client says: "I\'ve been trying so hard but the scale hasn\'t moved in three weeks." The trainer replies: "It sounds like you\'re feeling discouraged that your effort isn\'t showing up the way you expected."',
      question: 'Which technique is the trainer using?',
      options: ['A closed-ended question', 'A reflection', 'An affirmation', 'A summary'],
      answer: 1,
      explanation: 'The trainer named the underlying feeling/meaning behind what the client said — that is a reflection, going deeper than simply restating the words.',
      whyWrong: ['No question was asked at all.', '', 'An affirmation would recognize a strength or effort, e.g. "You\'ve shown real persistence."', 'A summary would consolidate several points across the conversation, not name one underlying feeling.'],
    },
    {
      kind: 'scenario', id: 'comm-s2', tags: ['communication'],
      story: 'A trainer wants to encourage a hesitant client to talk about their own reasons for wanting to get healthier.',
      question: 'Which question is most likely to promote change talk?',
      options: [
        '"Why haven\'t you started already?"',
        '"What matters most to you about getting healthier?"',
        '"Do you want to lose weight?"',
        '"Don\'t you think you should start soon?"',
      ],
      answer: 1,
      explanation: 'An open, non-judgmental question invites the client to voice their own motivation — the core of eliciting change talk.',
      whyWrong: ['This is confrontational and tends to produce defensiveness.', '', 'This is closed-ended and can be answered with a single word.', 'This is leading and pushes the trainer\'s agenda rather than eliciting the client\'s.'],
    },
    {
      kind: 'scenario', id: 'comm-s3', tags: ['communication'],
      story: 'At the end of a session, a trainer says: "So this week you trained twice, started meal prepping on Sundays, and got to bed earlier three nights. That\'s real progress across several areas."',
      question: 'Which OARS technique is this?',
      options: ['Open-ended question', 'Reflection', 'Summary', 'Closed question'],
      answer: 2,
      explanation: 'Consolidating multiple things the client accomplished into one recap is a summary.',
      whyWrong: ['No question was asked.', 'A reflection names an underlying feeling or meaning from a single statement.', '', 'No question was asked.'],
    },
    {
      kind: 'mcq', id: 'comm-m3', tags: ['communication'], source: 'original',
      prompt: 'Which is an example of a CLOSED-ended question?',
      options: [
        '"What made you decide to start training?"',
        '"How do you feel about your progress?"',
        '"Did you get your workouts in this week?"',
        '"What\'s the hardest part of staying consistent?"',
      ],
      answer: 2,
      explanation: 'A closed-ended question can be answered with a single word, typically yes or no.',
      whyWrong: ['This invites elaboration — open-ended.', 'This invites elaboration — open-ended.', '', 'This invites elaboration — open-ended.'],
    },
    {
      kind: 'mcq', id: 'comm-m4', tags: ['leadership'], source: 'original',
      prompt: 'Being optimistic, empathetic, knowledgeable, and modeling a healthy balanced life describes which leadership component?',
      options: ['Leader\'s style', 'Leader\'s qualities', 'The requirements of the leader', 'Leader\'s personality type'],
      answer: 1,
      explanation: 'This trait bundle is specifically termed the leader\'s qualities.',
      whyWrong: ['Style describes the behavioral approach to leading, not the underlying traits.', '', 'This is not the NASM term for this trait list.', 'This is not the NASM term for this trait list.'],
    },
    {
      kind: 'mcq', id: 'comm-m5', tags: ['communication'], source: 'original',
      prompt: 'What is the key difference between reflective listening and a reflection?',
      options: [
        'They are identical terms',
        'Reflective listening restates the stated content; a reflection expresses the supposed underlying meaning',
        'Reflective listening is nonverbal; a reflection is verbal',
        'A reflection is a type of question',
      ],
      answer: 1,
      explanation: 'Reflective listening restates what was said to confirm understanding; a reflection goes a layer deeper, naming the meaning or feeling behind it.',
      whyWrong: ['They are related but distinct, and the exam tests the distinction.', '', 'Both are verbal techniques.', 'A reflection is a statement, not a question.'],
    },
    {
      kind: 'match', id: 'comm-match2', tags: ['communication'],
      prompt: 'Match each OARS letter to its technique and an example.',
      pairs: [
        ['O – Open-ended question', '"What matters most to you about getting healthier?"'],
        ['A – Affirmation', '"You showed real discipline sticking to this all month."'],
        ['R – Reflective listening', '"So you\'re saying you want to feel stronger for your kids."'],
        ['S – Summary', '"This month you trained 12 times, improved sleep, and cut soda."'],
      ],
      explanation: 'OARS is the core toolkit of motivational interviewing — expect example-matching questions on the exam.',
    },
    { kind: 'typein', id: 'comm-t11', tags: ['communication'], prompt: 'What is the general skill of fully attending to what a client is saying called?', accept: ['active listening'], hints: ['Two words.', 'A_____ L________'], explanation: 'Active listening is the overall practice of attentive, engaged listening.' },
    { kind: 'typein', id: 'comm-t12', tags: ['communication'], prompt: 'What does the "R" in OARS stand for?', accept: ['reflective listening', 'reflecting'], hints: ['Mirroring content back.', 'R_________ L________'], explanation: 'R = Reflective listening.' },
    { kind: 'typein', id: 'comm-t13', tags: ['communication'], prompt: 'What does the "O" in OARS stand for?', accept: ['open-ended questions', 'open ended questions'], hints: ['Cannot be answered yes/no.', 'O___-E____ Q________'], explanation: 'O = Open-ended questions.' },
    { kind: 'typein', id: 'comm-t14', tags: ['communication'], prompt: 'Establishing trust and a comfortable working relationship with a client is called building what?', accept: ['rapport'], hints: ['A French-origin word.', 'R______'], explanation: 'Rapport is the trusting, comfortable relationship between trainer and client.' },
    { kind: 'typein', id: 'comm-t15', tags: ['communication'], prompt: 'Which question type should be minimized when trying to elicit change talk?', accept: ['closed-ended', 'closed ended', 'closed'], hints: ['Yes/no answers.', 'C_____-E____'], explanation: 'Closed-ended questions limit elaboration and are less effective for eliciting change talk.' },
  ],
}
