import type { Module } from '../../types/content'

export const business: Module = {
  id: 'd6-business',
  domainId: 'd6',
  title: 'Business Fundamentals',
  estMinutes: 25,
  lessons: [
    {
      id: 'biz-l1',
      title: 'Employee vs. independent contractor',
      plain: `This distinction shows up on the exam a lot. An **employee** has taxes withheld automatically by their employer and typically works a set schedule set by the employer. An **independent contractor** is responsible for handling and paying their own taxes, and generally has more control/flexibility over their own schedule. Neither role is inherently "better pay" — the key difference tested is tax handling and schedule control, not income level.`,
      nasm: `An employee has income taxes withheld automatically by the employer and generally works a schedule set by the employer. An independent contractor is responsible for paying their own self-employment taxes and typically has greater control over their own working hours and schedule. Pay rate itself is not a defining structural difference between the two classifications.`,
      mustMemorise: ['Independent contractor pays their own taxes; employee has taxes withheld by the employer'],
    },
    {
      id: 'biz-l2',
      title: 'Unique selling proposition and marketing',
      plain: `A **unique selling proposition (USP)** is what makes a trainer's services stand out from every other trainer offering similar services — the specific angle, expertise, or approach that differentiates them in a crowded market. Building extra income often means leveraging skills a trainer already has from a previous career (e.g. a former copywriter marketing fitness content/blogs, rather than starting from zero in an unrelated field).`,
      nasm: `A unique selling proposition (USP) differentiates a fitness professional's services from competitors in the marketplace. Trainers are encouraged to develop additional income streams by leveraging existing skills and prior professional experience, rather than pursuing entirely unrelated opportunities.`,
      mustMemorise: ['USP = what differentiates a trainer\'s services from competitors', 'Additional income streams should leverage the trainer\'s existing skills, not unrelated opportunities'],
    },
    {
      id: 'biz-l3',
      title: 'Client retention basics',
      plain: `Retaining clients long-term comes down to a few fundamentals: delivering real results, communicating well (see the D5 communication module), showing genuine care for the client as a person (not just a paying customer), and being a reliable, professional presence session after session. Business success as a trainer is built on retention as much as new client acquisition.`,
      nasm: `Client retention is driven by consistent results delivery, effective communication, genuine rapport, and professional reliability. Long-term business success depends on retention strategies as much as new client acquisition.`,
      mustMemorise: [],
    },
  ],
  items: [
    { kind: 'typein', id: 'biz-t1', tags: ['employment'], prompt: 'Who is responsible for paying their own taxes: an employee or an independent contractor?', accept: ['independent contractor'], hints: ['Not the one with taxes withheld automatically.', 'I___________ C__________'], explanation: 'An independent contractor is responsible for paying their own taxes.' },
    { kind: 'typein', id: 'biz-t2', tags: ['marketing'], prompt: 'What abbreviation describes what makes a trainer\'s services stand out from competitors?', accept: ['usp', 'unique selling proposition'], hints: ['3 letters.', 'U__'], explanation: 'USP = unique selling proposition.' },
    { kind: 'typein', id: 'biz-t3', tags: ['income'], prompt: 'When looking for additional income streams, what should a trainer prioritize leveraging?', accept: ['their existing skills', 'existing skills', 'skills they already have'], hints: ['Not something totally unrelated.', 'E________ skills'], explanation: 'Trainers should leverage existing skills/experience for additional income streams.' },
    {
      kind: 'mcq', id: 'biz-m1', tags: ['employment'], source: 'original',
      prompt: 'Which of the following indicates a primary difference between working as an independent contractor and working as an employee?',
      options: [
        'An employee can earn more per hour than an independent contractor.',
        'An independent contractor is responsible for paying their own taxes, while an employee has taxes withheld by the employer.',
        'An employee can establish their own hours, while an independent contractor must adhere to a set schedule.',
        'An independent contractor can expect client referrals from a facility, while an employee finds clients on the gym floor.',
      ],
      answer: 1,
      explanation: 'A defining tax distinction: independent contractors handle their own tax withholding, employees have taxes withheld automatically.',
      whyWrong: ['Pay rate is not a defining structural difference between the two classifications.', '', 'This is backwards — independent contractors typically have more schedule flexibility.', 'This is backwards from the typical referral/prospecting dynamic between the two roles.'],
    },
    {
      kind: 'mcq', id: 'biz-m2', tags: ['income'], source: 'original',
      prompt: 'Kim was previously a copywriter and is now an NASM CPT. What is the best way for her to increase her earning potential?',
      options: [
        'Become a college football conditioning coach',
        'Market her writing services to create blogs/social content for her studio and other trainers',
        'Become an NASM Master Instructor',
        'Take an unrelated part-time retail job',
      ],
      answer: 1,
      explanation: 'This directly leverages her existing copywriting skill set alongside her fitness credential.',
      whyWrong: ['This does not leverage her copywriting background and is a large career shift.', '', 'Becoming a Master Instructor is a significant separate undertaking, unrelated to her writing skill.', 'An unrelated job does not leverage her specific professional skill set.'],
    },
    { kind: 'typein', id: 'biz-t4', tags: ['employment'], prompt: 'Which worker classification typically has MORE control over their own schedule?', accept: ['independent contractor'], hints: ['Not the employee.', 'I___________ C__________'], explanation: 'Independent contractors generally have greater control over their own hours and schedule.' },
    { kind: 'typein', id: 'biz-t5', tags: ['employment'], prompt: 'Which worker classification has taxes withheld automatically by the employer?', accept: ['employee'], hints: ['Not the contractor.', 'E________'], explanation: 'Employees have taxes withheld by their employer; contractors pay their own.' },
    { kind: 'typein', id: 'biz-t6', tags: ['marketing'], prompt: 'What does USP stand for?', accept: ['unique selling proposition'], hints: ['Three words.', 'U_____ S______ P___________'], explanation: 'USP = unique selling proposition — what differentiates your services from competitors.' },
    { kind: 'typein', id: 'biz-t7', tags: ['retention'], prompt: 'Keeping existing clients long-term rather than constantly finding new ones is called what?', accept: ['client retention', 'retention'], hints: ['Two words.', 'C_____ R________'], explanation: 'Client retention is central to long-term business success as a trainer.' },
    {
      kind: 'scenario', id: 'biz-s1', tags: ['employment'],
      story: 'A trainer works at a gym that sets their schedule, provides all equipment and clients, and withholds taxes from their paycheck.',
      question: 'How is this trainer most likely classified?',
      options: ['Independent contractor', 'Employee', 'Business owner', 'Franchisee'],
      answer: 1,
      explanation: 'Employer-set schedule, employer-provided clients/equipment, and withheld taxes are all hallmarks of employee classification.',
      whyWrong: ['An independent contractor pays their own taxes and generally sets their own schedule.', '', 'A business owner would not have taxes withheld by another party.', 'A franchisee operates their own licensed business unit.'],
    },
    {
      kind: 'scenario', id: 'biz-s2', tags: ['marketing'],
      story: 'A trainer is a former physical therapy assistant now certified as a CPT, working in a market crowded with general trainers.',
      question: 'What would make the strongest unique selling proposition?',
      options: [
        'Advertising the lowest prices in the area',
        'Positioning around their movement-quality background and work with clients returning from injury (within scope)',
        'Offering the same services as everyone else',
        'Claiming to treat injuries',
      ],
      answer: 1,
      explanation: 'A strong USP leverages a genuine differentiator — here, a relevant clinical background applied within CPT scope.',
      whyWrong: ['Competing purely on price is not a durable differentiator and erodes margins.', '', 'Offering identical services is the opposite of a USP.', 'Claiming to treat injuries would be outside scope of practice and unlawful.'],
    },
    {
      kind: 'scenario', id: 'biz-s3', tags: ['retention'],
      story: 'A trainer notices several clients drop off after about 8 weeks, right when initial visible progress slows.',
      question: 'What is the most appropriate retention strategy?',
      options: [
        'Increase prices to filter for committed clients',
        'Reset expectations, highlight non-scale progress, and re-goal-set with process goals',
        'Stop tracking progress entirely to avoid disappointment',
        'Recommend they take a long break',
      ],
      answer: 1,
      explanation: 'Retention improves when clients can see progress beyond the scale and have behavior-based (process) goals that stay achievable once rapid early results slow.',
      whyWrong: ['Raising prices does not address the underlying motivation drop-off.', '', 'Removing progress tracking removes the feedback that sustains motivation.', 'Recommending a break accelerates the drop-off rather than preventing it.'],
    },
    {
      kind: 'mcq', id: 'biz-m3', tags: ['employment'], source: 'original',
      prompt: 'Which is the clearest structural difference between an employee and an independent contractor?',
      options: [
        'Employees always earn more per hour',
        'Independent contractors are responsible for their own taxes; employees have taxes withheld',
        'Only employees can train clients',
        'Independent contractors cannot carry insurance',
      ],
      answer: 1,
      explanation: 'Tax responsibility is the defining structural distinction: contractors handle their own, employees have taxes withheld by the employer.',
      whyWrong: ['Pay rate is not a defining classification difference.', '', 'Both classifications train clients.', 'Independent contractors can and should carry liability insurance.'],
    },
    {
      kind: 'mcq', id: 'biz-m4', tags: ['income'], source: 'original',
      prompt: 'What is the recommended approach when a trainer seeks additional income streams?',
      options: [
        'Pursue whichever field pays the most, regardless of background',
        'Leverage existing skills and professional experience alongside the fitness credential',
        'Take on as many unrelated part-time jobs as possible',
        'Avoid additional income streams entirely',
      ],
      answer: 1,
      explanation: 'Building on skills and experience the trainer already has produces the highest-leverage additional income, rather than starting from zero in an unrelated field.',
      whyWrong: ['Highest pay in an unfamiliar field ignores the leverage of existing expertise.', '', 'Spreading across unrelated jobs dilutes focus and leverages nothing.', 'Additional income streams are actively encouraged where they fit the trainer\'s skills.'],
    },
    {
      kind: 'match', id: 'biz-match1', tags: ['employment'],
      prompt: 'Match each characteristic to the correct worker classification.',
      pairs: [
        ['Pays their own self-employment taxes', 'Independent contractor'],
        ['Has taxes withheld by the employer', 'Employee'],
        ['Generally sets their own schedule', 'Independent contractor'],
        ['Generally works an employer-set schedule', 'Employee'],
      ],
      explanation: 'Tax handling and schedule control are the two defining axes the exam tests for this distinction.',
    },
    { kind: 'typein', id: 'biz-t8', tags: ['employment'], prompt: 'Which classification generally receives employee benefits such as paid time off?', accept: ['employee'], hints: ['Not the contractor.', 'E________'], explanation: 'Employees typically receive benefits; independent contractors generally do not.' },
    { kind: 'typein', id: 'biz-t9', tags: ['marketing'], prompt: 'What business term describes the specific group of clients a trainer aims to serve?', accept: ['target market', 'target audience', 'niche'], hints: ['Two words.', 'T_____ M_____'], explanation: 'A target market is the specific client group a trainer positions their services toward.' },
    { kind: 'typein', id: 'biz-t10', tags: ['retention'], prompt: 'Name one primary driver of long-term client retention.', accept: ['results', 'delivering results', 'communication', 'rapport', 'consistency'], hints: ['What clients came for in the first place.', 'R______'], explanation: 'Retention is driven by delivering real results, strong communication, rapport, and professional reliability.' },
    { kind: 'typein', id: 'biz-t11', tags: ['employment'], prompt: 'Which classification must handle their own self-employment tax filings?', accept: ['independent contractor'], hints: ['Not the employee.', 'I___________ C__________'], explanation: 'Independent contractors are responsible for their own tax filings and payments.' },
    { kind: 'typein', id: 'biz-t12', tags: ['marketing'], prompt: 'What is the term for income earned from sources beyond one-on-one training sessions?', accept: ['additional income streams', 'income streams', 'multiple income streams'], hints: ['Think of water flowing in.', 'Income s______'], explanation: 'Additional income streams supplement session-based earnings, ideally leveraging existing skills.' },
    { kind: 'typein', id: 'biz-t13', tags: ['marketing'], prompt: 'Differentiating your services from competitors in a crowded market requires a strong what?', accept: ['usp', 'unique selling proposition'], hints: ['Three-letter abbreviation.', 'U__'], explanation: 'A unique selling proposition differentiates a trainer in a competitive market.' },
    { kind: 'typein', id: 'biz-t14', tags: ['employment'], prompt: 'Which classification typically has their work schedule determined by the facility?', accept: ['employee'], hints: ['Less schedule freedom.', 'E________'], explanation: 'Employees typically work an employer-set schedule.' },
    {
      kind: 'mcq', id: 'biz-m5', tags: ['marketing'], source: 'original',
      prompt: 'What is the primary function of a unique selling proposition?',
      options: [
        'To set the lowest price in the market',
        'To differentiate a trainer\'s services from competitors offering similar services',
        'To determine tax classification',
        'To calculate client retention rate',
      ],
      answer: 1,
      explanation: 'A USP is what makes a trainer\'s offering stand out from the many others providing similar services.',
      whyWrong: ['Competing on price is not the purpose of a USP and is rarely durable.', '', 'Tax classification is an employment matter, unrelated to marketing differentiation.', 'Retention rate is a business metric, not a differentiator statement.'],
    },
    {
      kind: 'mcq', id: 'biz-m6', tags: ['retention'], source: 'original',
      prompt: 'Why does client retention matter as much as new client acquisition?',
      options: [
        'Retained clients require no further programming work',
        'Long-term business stability depends on keeping clients, not only continually replacing them',
        'Retention eliminates the need for liability insurance',
        'Retention is only relevant for independent contractors',
      ],
      answer: 1,
      explanation: 'Constantly replacing departing clients is far less sustainable than retaining them; long-term success depends on both.',
      whyWrong: ['Retained clients still require ongoing, evolving programming.', '', 'Insurance needs are unrelated to retention.', 'Retention matters for employees and contractors alike.'],
    },
    {
      kind: 'scenario', id: 'biz-s4', tags: ['employment'],
      story: 'A trainer rents space at a facility, sets their own hours, brings their own clients, supplies their own equipment, and receives no tax withholding.',
      question: 'How are they most likely classified?',
      options: ['Employee', 'Independent contractor', 'Intern', 'Volunteer'],
      answer: 1,
      explanation: 'Setting their own hours, sourcing their own clients, and receiving no tax withholding are all hallmarks of independent contractor status.',
      whyWrong: ['An employee would have taxes withheld and typically work an employer-set schedule.', '', 'An intern would work under supervision in a training capacity.', 'A volunteer would be unpaid.'],
    },
  ],
}
