import type { Module } from '../../types/content'

export const scopeEthics: Module = {
  id: 'd6-scope-ethics',
  domainId: 'd6',
  title: 'Scope of Practice & Professional Ethics',
  estMinutes: 30,
  lessons: [
    {
      id: 'se-l1',
      title: 'Scope of practice: what a trainer can and can\'t do',
      plain: `Scope of practice is the boundary of what a certified personal trainer is qualified and legally permitted to do. Inside scope: general fitness programming, general nutrition guidance, motivation and behavior-change coaching. Outside scope: diagnosing injuries or medical conditions, prescribing specific diets/supplements/medications, treating injuries (that's physical therapy), or advising on performance-enhancing drugs. When a client's need falls outside scope, the correct move is always to **refer** — to a doctor, registered dietitian, physical therapist, or other licensed professional — never to guess or improvise.`,
      nasm: `Scope of practice defines the boundaries of services a Certified Personal Trainer is qualified and legally authorized to provide, generally encompassing fitness assessment, program design, and general lifestyle/nutrition guidance, while excluding diagnosis, medical treatment, individualized medical nutrition therapy, and rehabilitation. When a client's needs exceed scope of practice, the trainer must refer the client to an appropriately licensed professional.`,
      mustMemorise: ['When a client\'s need is outside scope of practice, always refer to a licensed professional'],
    },
    {
      id: 'se-l2',
      title: 'Confidentiality, liability, and waivers',
      plain: `Client information (health history, goals, personal details) must be kept confidential — shared only with the client's consent or as legally required. Trainers carry **liability** risk (legal responsibility if a client is injured due to negligence), which is why **waivers** (documents where clients acknowledge and accept the risks of exercise) and **liability insurance** are standard business practice. **Negligence** specifically means failing to exercise the standard of care a reasonably prudent trainer would use in the same situation.`,
      nasm: `Client information must be kept confidential in accordance with professional and legal standards. Liability refers to legal responsibility for harm resulting from a trainer's actions or omissions. Negligence is the failure to exercise the standard of care that a reasonably prudent professional would exercise under similar circumstances. Waivers and liability insurance are standard risk-management practices used to document informed consent and mitigate financial risk.`,
      mustMemorise: ['Negligence = failing to use the standard of care a reasonably prudent trainer would use'],
    },
    {
      id: 'se-l3',
      title: 'CPR/AED and recertification',
      plain: `Every Certified Personal Trainer must maintain current CPR/AED certification — this is non-negotiable given the physical nature of the work. To keep an NASM certification active, trainers must recertify by earning **2.0 continuing education units (CEUs) every 2 years**.`,
      nasm: `Certified Personal Trainers are required to maintain current CPR/AED certification. NASM certification recertification requires earning 2.0 continuing education units (CEUs) every 2 years.`,
      mustMemorise: ['NASM recertification: 2.0 CEUs every 2 years'],
    },
  ],
  items: [
    { kind: 'typein', id: 'se-t1', tags: ['scope'], prompt: 'What should a trainer do when a client\'s need falls outside their scope of practice?', accept: ['refer them to a licensed professional', 'refer', 'refer to a licensed professional'], hints: ['Send them elsewhere.', 'R____'], explanation: 'The trainer should refer the client to an appropriately licensed professional.' },
    { kind: 'typein', id: 'se-t2', tags: ['ethics'], prompt: 'What term describes failing to use the standard of care a reasonably prudent trainer would use?', accept: ['negligence'], hints: ['A legal term.', 'N_________'], explanation: 'Negligence is failing to exercise the standard of care a reasonably prudent trainer would use.' },
    { kind: 'typein', id: 'se-t3', tags: ['ethics'], prompt: 'What document has a client acknowledge and accept the risks of exercise?', accept: ['waiver'], hints: ['Signed before training begins.', 'W______'], explanation: 'A waiver documents the client\'s acknowledgment and acceptance of exercise risk.' },
    { kind: 'typein', id: 'se-t4', tags: ['certification'], prompt: 'How many CEUs are required to recertify an NASM CPT credential, and over what period?', accept: ['2.0 ceus every 2 years', '2 ceus every 2 years', '2.0 every 2 years'], hints: ['Same number twice.', '_.0 CEUs / _ years'], explanation: 'NASM recertification requires 2.0 CEUs every 2 years.' },
    { kind: 'typein', id: 'se-t5', tags: ['certification'], prompt: 'What certification must every personal trainer maintain, related to emergency response?', accept: ['cpr/aed', 'cpr and aed', 'cpr aed'], hints: ['Two abbreviations.', 'CPR/A__'], explanation: 'Trainers must maintain current CPR/AED certification.' },
    {
      kind: 'mcq', id: 'se-m1', tags: ['scope'], source: 'original',
      prompt: 'A client asks their trainer to design a specific meal plan with exact macronutrient targets for a medical condition. What is the correct response?',
      options: [
        'Design the plan, since nutrition is within a trainer\'s scope of practice.',
        'Politely decline and refer the client to a registered dietitian or physician.',
        'Suggest general foods only, without any macronutrient detail.',
        'Ignore the request entirely.',
      ],
      answer: 1,
      explanation: 'Individualized medical nutrition therapy is outside a trainer\'s scope of practice and should be referred to a qualified professional.',
      whyWrong: ['General nutrition guidance is within scope, but individualized medical nutrition planning is not.', '', 'This avoids the issue rather than properly referring the client.', 'Ignoring the request is not an appropriate professional response.'],
    },
    {
      kind: 'mcq', id: 'se-m2', tags: ['certification'], source: 'original',
      prompt: 'How often must an NASM Certified Personal Trainer recertify, and with how many CEUs?',
      options: ['1.0 CEU every year', '2.0 CEUs every 2 years', '5.0 CEUs every 5 years', '0.5 CEUs every 6 months'],
      answer: 1,
      explanation: 'NASM recertification requires 2.0 CEUs every 2 years.',
      whyWrong: ['This does not match the NASM recertification cycle.', '', 'This does not match the NASM recertification cycle.', 'This does not match the NASM recertification cycle.'],
    },
    { kind: 'typein', id: 'se-t6', tags: ['scope'], prompt: 'To whom should a trainer refer a client needing an individualized medical meal plan?', accept: ['registered dietitian', 'dietitian', 'registered dietitian or physician'], hints: ['A licensed nutrition professional.', 'R________ D________'], explanation: 'Individualized medical nutrition therapy requires a registered dietitian or physician.' },
    { kind: 'typein', id: 'se-t7', tags: ['scope'], prompt: 'To whom should a trainer refer a client needing rehabilitation of a diagnosed injury?', accept: ['physical therapist', 'physiotherapist'], hints: ['A licensed rehab professional.', 'P_______ T________'], explanation: 'Injury rehabilitation is the domain of a licensed physical therapist, outside a CPT\'s scope.' },
    { kind: 'typein', id: 'se-t8', tags: ['ethics'], prompt: 'What legal concept refers to a trainer\'s responsibility for harm resulting from their actions or omissions?', accept: ['liability'], hints: ['Legal responsibility.', 'L________'], explanation: 'Liability is legal responsibility for harm resulting from a trainer\'s actions or omissions.' },
    { kind: 'typein', id: 'se-t9', tags: ['ethics'], prompt: 'What must a trainer maintain regarding a client\'s personal health information?', accept: ['confidentiality'], hints: ['Keep it private.', 'C______________'], explanation: 'Client information must be kept confidential, shared only with consent or as legally required.' },
    {
      kind: 'scenario', id: 'se-s1', tags: ['scope'],
      story: 'A client tells their trainer they have been having sharp chest pain during cardio sessions for the past week.',
      question: 'What is the appropriate action?',
      options: [
        'Reduce the intensity and continue training',
        'Stop exercise and refer the client to a physician immediately',
        'Suggest it is probably muscular and recommend stretching',
        'Continue but monitor heart rate closely',
      ],
      answer: 1,
      explanation: 'Chest pain during exercise is a red-flag symptom requiring immediate cessation and physician referral. Diagnosing or dismissing it is outside a trainer\'s scope.',
      whyWrong: ['Continuing to exercise with undiagnosed chest pain is dangerous.', '', 'Speculating on the cause is diagnosing — outside scope and potentially dangerous.', 'Monitoring does not address the underlying red-flag symptom.'],
    },
    {
      kind: 'scenario', id: 'se-s2', tags: ['scope'],
      story: 'A client asks their trainer to recommend a specific fat-burner supplement and dosage to accelerate results.',
      question: 'What is the appropriate response?',
      options: [
        'Recommend a product the trainer personally uses',
        'Decline to prescribe supplements and refer to a physician or registered dietitian',
        'Suggest doubling the label dose for faster results',
        'Sell them a product from the gym\'s shelf',
      ],
      answer: 1,
      explanation: 'Recommending specific supplements and dosages is outside a CPT\'s scope of practice; refer to an appropriately licensed professional.',
      whyWrong: ['Personal use does not make a supplement recommendation within scope.', '', 'Advising doses above label instructions is unsafe and far outside scope.', 'Selling does not change the scope-of-practice boundary on dosing advice.'],
    },
    {
      kind: 'scenario', id: 'se-s3', tags: ['ethics'],
      story: 'A trainer fails to check a cable machine\'s pin before a set. The weight stack slips and injures the client.',
      question: 'Which legal concept does this most directly illustrate?',
      options: ['Confidentiality breach', 'Negligence', 'Informed consent', 'Scope of practice violation'],
      answer: 1,
      explanation: 'Negligence is the failure to exercise the standard of care a reasonably prudent professional would exercise — such as checking equipment before a set.',
      whyWrong: ['Confidentiality concerns client information, not equipment safety.', '', 'Informed consent documents risk acknowledgement; it does not excuse a preventable safety failure.', 'The trainer stayed within scope; the failure was one of care, not scope.'],
    },
    {
      kind: 'mcq', id: 'se-m3', tags: ['scope'], source: 'original',
      prompt: 'Which activity is clearly WITHIN a CPT\'s scope of practice?',
      options: [
        'Diagnosing the cause of a client\'s knee pain',
        'Designing a progressive resistance program for a healthy client',
        'Prescribing a supplement regimen',
        'Providing rehabilitation exercises for a torn ligament',
      ],
      answer: 1,
      explanation: 'Fitness assessment and program design for apparently healthy clients is the core of a CPT\'s scope.',
      whyWrong: ['Diagnosis is a medical act, outside scope.', '', 'Prescribing supplements is outside scope.', 'Rehabilitation of a diagnosed injury is physical therapy, outside scope.'],
    },
    {
      kind: 'mcq', id: 'se-m4', tags: ['ethics'], source: 'original',
      prompt: 'What is the primary purpose of a waiver?',
      options: [
        'To transfer all legal responsibility away from the trainer permanently',
        'To document that the client acknowledges and accepts the inherent risks of exercise',
        'To replace the need for liability insurance',
        'To guarantee the client will see results',
      ],
      answer: 1,
      explanation: 'A waiver documents the client\'s informed acknowledgement and acceptance of the inherent risks of exercise participation.',
      whyWrong: ['A waiver does not eliminate liability for negligence.', '', 'Waivers and insurance serve different risk-management purposes; neither replaces the other.', 'Waivers make no guarantee about results.'],
    },
    {
      kind: 'mcq', id: 'se-m5', tags: ['certification'], source: 'original',
      prompt: 'Which certification must every practicing CPT maintain?',
      options: ['Nutrition coaching certification', 'CPR/AED certification', 'Physical therapy license', 'Group fitness certification'],
      answer: 1,
      explanation: 'Current CPR/AED certification is required for practicing Certified Personal Trainers given the physical nature of the work.',
      whyWrong: ['Nutrition certification is optional and does not extend scope into medical nutrition therapy.', '', 'A PT license is a separate profession, not a CPT requirement.', 'Group fitness certification is optional and specialty-specific.'],
    },
    {
      kind: 'match', id: 'se-match1', tags: ['scope'],
      prompt: 'Match each client need to the appropriate referral professional.',
      pairs: [
        ['Individualized medical meal plan', 'Registered dietitian'],
        ['Rehabilitation of a diagnosed injury', 'Physical therapist'],
        ['Chest pain during exercise', 'Physician'],
        ['Progressive resistance program (healthy client)', 'Stays with the CPT'],
      ],
      explanation: 'Knowing exactly where scope ends — and who to refer to — is heavily tested in this domain.',
    },
    {
      kind: 'match', id: 'se-match2', tags: ['ethics'],
      prompt: 'Match each legal/professional term to its meaning.',
      pairs: [
        ['Negligence', 'Failure to exercise the standard of care a prudent trainer would'],
        ['Liability', 'Legal responsibility for resulting harm'],
        ['Waiver', 'Client acknowledgement and acceptance of exercise risk'],
        ['Confidentiality', 'Keeping client information private'],
      ],
      explanation: 'These four terms are frequently used as interchangeable distractors — know the precise distinction.',
    },
    { kind: 'typein', id: 'se-t10', tags: ['scope'], prompt: 'Can a CPT legally diagnose an injury?', accept: ['no'], hints: ['One word.', 'N_'], explanation: 'Diagnosis is a medical act, strictly outside a CPT\'s scope of practice.' },
    { kind: 'typein', id: 'se-t11', tags: ['ethics'], prompt: 'What type of insurance protects a trainer financially against claims of harm?', accept: ['liability insurance', 'liability'], hints: ['Named after the legal concept.', 'L________ insurance'], explanation: 'Liability insurance is standard risk management for practicing trainers.' },
    { kind: 'typein', id: 'se-t12', tags: ['certification'], prompt: 'How many years is the NASM recertification cycle?', accept: ['2', '2 years', 'two'], hints: ['A single digit.', '_ years'], explanation: 'NASM certification is renewed every 2 years with 2.0 CEUs.' },
    { kind: 'typein', id: 'se-t13', tags: ['certification'], prompt: 'How many CEUs are required per NASM recertification cycle?', accept: ['2.0', '2', '2.0 ceus'], hints: ['Matches the number of years.', '_._ CEUs'], explanation: 'NASM requires 2.0 CEUs every 2 years.' },
    { kind: 'typein', id: 'se-t14', tags: ['scope'], prompt: 'Is providing general nutrition guidance (e.g. "eat more vegetables") within a CPT\'s scope?', accept: ['yes'], hints: ['One word.', 'Y__'], explanation: 'General nutrition guidance is within scope; individualized medical nutrition therapy is not.' },
    { kind: 'typein', id: 'se-t15', tags: ['ethics'], prompt: 'Who may a trainer share a client\'s health information with, absent legal requirement?', accept: ['no one without consent', 'nobody without consent', 'only with client consent'], hints: ['Depends on permission.', 'Only with client c______'], explanation: 'Client information is confidential and shared only with consent or where legally required.' },
  ],
}
