import type { Module } from '../../types/content'
import { COMPENSATIONS } from '../trainers/muscleImbalanceData'

export const muscleImbalances: Module = {
  id: 'd2-posture-movement',
  domainId: 'd2',
  title: 'Muscle Imbalances & Overhead Squat Assessment',
  estMinutes: 35,
  lessons: [
    {
      id: 'mi-l1',
      title: 'The one rule that explains every compensation',
      plain: `Here's the trick: **the side a joint collapses or moves toward is tight (overactive)**. **The opposite side, the one that should have stopped that movement, is weak (underactive).** Knees cave inward? The inside of the thigh (adductors) is tight, and the outside hip muscle (glute medius) that should hold the knee out is weak. Learn this one rule and you can reason out almost every compensation instead of memorizing 9 separate lists.`,
      nasm: `Altered reciprocal inhibition occurs when an overactive/shortened muscle causes decreased neural drive to its functional antagonist. Relative to the overhead squat assessment, the direction of a compensation typically identifies overactive (tight) musculature on the side toward which the segment deviates, and underactive (weak, inhibited) musculature on the opposing side.`,
      memoryHook: `"Where it goes, it's tight. The other side is weak."`,
      mustMemorise: ['Direction of compensation = overactive side. Opposite = underactive side.'],
    },
    {
      id: 'mi-l2',
      title: 'Why this happens: altered reciprocal inhibition',
      plain: `Muscles work in pairs — when one contracts, its opposite (antagonist) is supposed to relax a little to let the movement happen. If one muscle stays chronically tight (say, from sitting all day), it keeps telling its opposite muscle to "stay quiet," even during exercise. Over time the opposite muscle gets weaker just from disuse. This is called altered reciprocal inhibition, and it's the real mechanism behind every overactive/underactive pair.`,
      nasm: `Reciprocal inhibition is the simultaneous contraction of one muscle and relaxation of its functional antagonist to allow movement. Altered reciprocal inhibition occurs when a tight agonist decreases the neural drive of its antagonist, and synergistic dominance occurs when a synergist compensates for the weakened antagonist, further reinforcing the faulty movement pattern.`,
      mustMemorise: [
        'Altered reciprocal inhibition: a tight muscle decreases neural drive to its opposite (antagonist) muscle',
        'Synergistic dominance: a helper muscle takes over for a weak prime mover',
      ],
    },
    {
      id: 'mi-l3',
      title: 'The overhead squat assessment itself',
      plain: `The trainer watches the client squat with arms overhead from three angles (front, side, back) and looks for specific breakdowns: feet turning out or flattening, knees caving in, leaning too far forward, the low back arching or rounding, arms falling forward, shoulders creeping up, or the head jutting forward. Each one has a predictable overactive/underactive pair behind it.`,
      nasm: `The overhead squat assessment (OHSA) is a dynamic assessment used to identify muscle imbalances and movement dysfunction throughout the kinetic chain. The client is observed from the anterior, lateral, and posterior views while performing repeated squats with the arms overhead, and specific compensations are noted at the feet, knees, LPHC (lumbo-pelvic-hip complex), shoulders, and head.`,
      mustMemorise: ['OHSA is viewed from anterior, lateral, and posterior views'],
    },
  ],
  items: [
    ...COMPENSATIONS.map((c, i) => ({
      kind: 'multi-typein' as const,
      id: `mi-mt-${i}-over`,
      tags: ['muscle-imbalance', 'overactive'],
      prompt: `Overhead squat: "${c.compensation}." Name the OVERACTIVE (tight) muscles.`,
      expected: c.overactive.map((m) => ({ canonical: m, accept: [m] })),
      minToPass: Math.max(1, c.overactive.length - 1),
      explanation: `Overactive: ${c.overactive.join(', ')}. ${c.logic}`,
    })),
    ...COMPENSATIONS.map((c, i) => ({
      kind: 'multi-typein' as const,
      id: `mi-mt-${i}-under`,
      tags: ['muscle-imbalance', 'underactive'],
      prompt: `Overhead squat: "${c.compensation}." Name the UNDERACTIVE (weak) muscles.`,
      expected: c.underactive.map((m) => ({ canonical: m, accept: [m] })),
      minToPass: Math.max(1, c.underactive.length - 1),
      explanation: `Underactive: ${c.underactive.join(', ')}. ${c.logic}`,
    })),
    {
      kind: 'mcq', id: 'mi-m1', tags: ['muscle-imbalance'], source: 'original',
      prompt: 'During the overhead squat assessment, a client\'s knees consistently move inward. Which muscle is most likely underactive?',
      options: ['Gluteus medius', 'Adductor longus', 'Tensor fascia latae', 'Vastus lateralis'],
      answer: 0,
      explanation: 'Gluteus medius abducts and externally rotates the hip, resisting knee valgus. When it is weak, the knees cave inward.',
      whyWrong: ['', 'Adductor longus is typically overactive in this compensation, not underactive.', 'TFL is typically overactive, contributing to the inward pull.', 'Vastus lateralis is typically overactive in this pattern.'],
    },
    {
      kind: 'mcq', id: 'mi-m2', tags: ['muscle-imbalance'], source: 'original',
      prompt: 'A client\'s arms fall forward during the overhead squat. Which pair of muscles is most likely tight (overactive)?',
      options: ['Mid trapezius and rhomboids', 'Latissimus dorsi and pectoralis major', 'Gluteus maximus and hamstrings', 'Anterior tibialis and posterior tibialis'],
      answer: 1,
      explanation: 'Tight lats and pec major pull the shoulders into internal rotation and the arms forward, out of an overhead position.',
      whyWrong: ['Mid trapezius and rhomboids are the underactive muscles in this compensation, not the overactive ones.', '', 'These are lower-body muscles unrelated to arm position.', 'These are foot/ankle muscles unrelated to arm position.'],
    },
    {
      kind: 'typein', id: 'mi-t1', tags: ['muscle-imbalance', 'mechanism'],
      prompt: 'What is the term for a tight muscle decreasing neural drive to its opposite muscle?',
      accept: ['altered reciprocal inhibition'],
      hints: ['It is a variation of "reciprocal inhibition."', 'A_______ R__________ I________'],
      explanation: 'Altered reciprocal inhibition: a chronically tight muscle suppresses activation of its functional antagonist.',
    },
    {
      kind: 'typein', id: 'mi-t2', tags: ['muscle-imbalance', 'mechanism'],
      prompt: 'What is it called when a synergist muscle takes over for a weak prime mover?',
      accept: ['synergistic dominance'],
      hints: ['"Synergist" + a word meaning "taking charge."', 'S__________ D_________'],
      explanation: 'Synergistic dominance occurs when a synergist compensates for an inhibited prime mover.',
    },
    { kind: 'typein', id: 'mi-t3', tags: ['muscle-imbalance', 'rule'], prompt: 'State the general rule: the side a joint moves TOWARD is (tight/weak)?', accept: ['tight', 'overactive', 'tight/overactive'], hints: ['It pulled the joint that direction.', 'T____ (overactive)'], explanation: 'The side the segment deviates toward is the overactive/tight side; the opposite side is underactive/weak.' },
    { kind: 'typein', id: 'mi-t4', tags: ['muscle-imbalance', 'ohsa'], prompt: 'From which view would you observe "knees move inward" during the overhead squat?', accept: ['anterior', 'anterior view', 'front'], hints: ['Looking at the client head on.', 'A________ view'], explanation: 'Knee valgus is observed from the anterior (front) view.' },
    { kind: 'typein', id: 'mi-t5', tags: ['muscle-imbalance', 'ohsa'], prompt: 'From which view would you observe "excessive forward lean" during the overhead squat?', accept: ['lateral', 'lateral view', 'side'], hints: ['Looking from the side.', 'L______ view'], explanation: 'Forward lean, low back arch/round, and arms falling forward are observed from the lateral view.' },
    {
      kind: 'scenario', id: 'mi-s1', tags: ['muscle-imbalance'],
      story: 'During an overhead squat, a client\'s knees cave inward. The trainer wants to design a corrective strategy.',
      question: 'Which combination is correct?',
      options: [
        'Stretch the gluteus medius; strengthen the adductors',
        'Stretch the adductors and TFL; strengthen the gluteus medius and maximus',
        'Stretch both the adductors and the glutes',
        'Strengthen both the adductors and the glutes',
      ],
      answer: 1,
      explanation: 'Knee valgus means overactive adductors/TFL/biceps femoris (short head)/vastus lateralis and underactive gluteus medius/maximus, VMO, and tibialis pair. Lengthen the overactive, strengthen the underactive.',
      whyWrong: ['This is backwards — glute medius is the weak muscle, adductors are the tight one.', '', 'Stretching an already-underactive glute would worsen the imbalance.', 'The overactive adductors need lengthening, not strengthening.'],
    },
    {
      kind: 'scenario', id: 'mi-s2', tags: ['muscle-imbalance'],
      story: 'A client\'s arms fall forward during the overhead squat assessment.',
      question: 'Which muscles should be strengthened?',
      options: [
        'Latissimus dorsi and pectoralis major',
        'Mid/lower trapezius, rhomboids, and rotator cuff',
        'Teres major and coracobrachialis',
        'Upper trapezius and levator scapulae',
      ],
      answer: 1,
      explanation: 'Arms falling forward means overactive lats/pecs/teres major and underactive mid and lower trapezius, rhomboids, rotator cuff, and posterior deltoid — strengthen the underactive group.',
      whyWrong: ['These are the overactive muscles in this compensation; they need lengthening, not strengthening.', '', 'These are also overactive in this pattern.', 'These are associated with shoulder elevation, and are overactive in that pattern.'],
    },
    {
      kind: 'scenario', id: 'mi-s3', tags: ['muscle-imbalance'],
      story: 'A client\'s low back arches excessively during the overhead squat.',
      question: 'Which muscle is most likely OVERACTIVE?',
      options: ['Gluteus maximus', 'Hip flexor complex', 'Hamstrings', 'Intrinsic core stabilizers'],
      answer: 1,
      explanation: 'A tight hip flexor complex tilts the pelvis anteriorly, arching the low back. The glutes, hamstrings, and deep core stabilizers are the underactive group here.',
      whyWrong: ['Gluteus maximus is underactive in this compensation.', '', 'Hamstrings are underactive in this compensation.', 'The intrinsic core stabilizers are underactive here.'],
    },
    {
      kind: 'mcq', id: 'mi-m3', tags: ['muscle-imbalance'], source: 'original',
      prompt: 'A client\'s feet flatten (arches collapse) during the overhead squat. Which muscles are most likely UNDERACTIVE?',
      options: [
        'Peroneals and lateral gastrocnemius',
        'Anterior and posterior tibialis, gluteus medius and maximus',
        'Tensor fascia latae and biceps femoris',
        'Soleus and adductor complex',
      ],
      answer: 1,
      explanation: 'Feet flattening involves overactive peroneals, lateral gastrocnemius, biceps femoris (short head), and TFL; the underactive group is the anterior/posterior tibialis plus gluteus medius and maximus.',
      whyWrong: ['These are overactive in this compensation.', '', 'These are overactive in this compensation.', 'These are not the underactive group for this pattern.'],
    },
    {
      kind: 'mcq', id: 'mi-m4', tags: ['muscle-imbalance'], source: 'original',
      prompt: 'A client\'s shoulders elevate toward their ears during the overhead squat. Which muscles are underactive?',
      options: [
        'Upper trapezius and levator scapulae',
        'Mid trapezius, lower trapezius, and serratus anterior',
        'Sternocleidomastoid and scalenes',
        'Deep cervical flexors only',
      ],
      answer: 1,
      explanation: 'Shoulder elevation involves overactive upper trapezius, levator scapulae, SCM and scalenes, with underactive mid/lower trapezius and serratus anterior.',
      whyWrong: ['These are the overactive muscles driving the elevation.', '', 'These are also overactive in this pattern.', 'Deep cervical flexors are underactive in the forward-head compensation, not shoulder elevation.'],
    },
    {
      kind: 'mcq', id: 'mi-m5', tags: ['muscle-imbalance'], source: 'original',
      prompt: 'A client\'s low back ROUNDS (rather than arches) during the overhead squat. Which muscles are likely overactive?',
      options: [
        'Hip flexor complex and erector spinae',
        'Hamstrings, adductor magnus, rectus abdominis, and external obliques',
        'Gluteus maximus and erector spinae',
        'Anterior tibialis and gluteus medius',
      ],
      answer: 1,
      explanation: 'Low back rounding involves overactive hamstrings and adductor magnus (posterior pelvic tilt) plus overactive rectus abdominis/external obliques; the glutes, erector spinae, hip flexors, and deep core are underactive.',
      whyWrong: ['These are overactive in low back ARCHING, the opposite compensation.', '', 'These are underactive in the rounding pattern.', 'These are not associated with this compensation.'],
    },
    {
      kind: 'match', id: 'mi-match1', tags: ['muscle-imbalance'],
      prompt: 'Match each compensation to its signature OVERACTIVE muscle.',
      pairs: [
        ['Knees move inward', 'Adductor complex / TFL'],
        ['Low back arches', 'Hip flexor complex'],
        ['Arms fall forward', 'Latissimus dorsi / pectorals'],
        ['Head migrates forward', 'Upper trapezius / SCM'],
      ],
      explanation: 'Learn the direction rule and these signature pairs cover most overhead-squat questions.',
    },
    {
      kind: 'match', id: 'mi-match2', tags: ['muscle-imbalance'],
      prompt: 'Match each compensation to the view it is observed from.',
      pairs: [
        ['Feet turn out / flatten', 'Anterior view'],
        ['Excessive forward lean', 'Lateral view'],
        ['Shoulders elevate', 'Posterior view'],
      ],
      explanation: 'The OHSA is observed from anterior, lateral, and posterior views, each revealing different compensations.',
    },
  ],
}
