import type { Module } from '../../types/content'

export const optModel: Module = {
  id: 'd3-opt-model',
  domainId: 'd3',
  title: 'OPT Model & Periodization',
  estMinutes: 25,
  lessons: [
    {
      id: 'opt-l1',
      title: 'What the OPT Model actually is',
      plain: `Think of the OPT Model as a staircase for a client's fitness, not a ladder you climb once and leave behind. There are **5 steps (phases)**, grouped into **3 buildings**: Stabilization, Strength, and Power. A total beginner starts on step 1 no matter how "fit" they look, because step 1 is about teaching the body to control itself before it tries to move heavy or fast.

Every phase changes the same 5 knobs: how many reps, how many sets, how heavy, how fast/slow each rep is (tempo), and how long you rest. Turn those knobs together and you get a different training effect — endurance, size, max strength, or power.`,
      nasm: `The Optimum Performance Training (OPT™) model is a systematic, periodized training strategy comprising three building blocks — Stabilization, Strength, and Power — divided into five phases of training. Each phase manipulates the acute variables (repetitions, sets, intensity, tempo, rest) to produce a specific physiological adaptation, progressing from stabilization endurance through strength endurance, muscular development, maximal strength, to power.`,
      memoryHook: `"Stabilize, then get Strong, then get Powerful." Phases 1→5 = Stabilization Endurance, Strength Endurance, Muscular Development, Maximal Strength, Power.`,
      mustMemorise: [
        'OPT model has 3 building blocks: Stabilization, Strength, Power',
        'OPT model has 5 phases total',
        'Phase 1 = Stabilization Endurance',
        'Phase 2 = Strength Endurance',
        'Phase 3 = Muscular Development (hypertrophy)',
        'Phase 4 = Maximal Strength',
        'Phase 5 = Power',
      ],
      table: {
        headers: ['Building block', 'Phase(s)', 'Primary goal'],
        rows: [
          ['Stabilization', 'Phase 1', 'Muscular endurance + joint stability'],
          ['Strength', 'Phases 2–4', 'Strength endurance → hypertrophy → maximal strength'],
          ['Power', 'Phase 5', 'Force production at speed'],
        ],
      },
    },
    {
      id: 'opt-l2',
      title: 'Periodization: planning training over time',
      plain: `Periodization is just "planning ahead" so training doesn't stay random forever. A **macrocycle** is the big picture (often a year). Cut that into **mesocycles** (chunks of weeks/months, like a training block for a season). Cut those into **microcycles** (usually a single week). The point is to plan variety on purpose instead of doing the same workout until it stops working.`,
      nasm: `Periodization is the division of a training program into smaller, progressive stages. A macrocycle is typically one year, mesocycles are smaller training blocks within the macrocycle (weeks to months), and microcycles are the smallest unit, typically one week. Periodization applies the General Adaptation Syndrome (GAS) and the principle of variation to avoid overtraining and plateaus.`,
      memoryHook: `Macro → Meso → Micro, biggest to smallest, like a calendar: year → block → week.`,
      mustMemorise: [
        'Macrocycle = typically 1 year',
        'Mesocycle = weeks to months (a training block)',
        'Microcycle = typically 1 week',
        'GAS = General Adaptation Syndrome: alarm → resistance (adaptation) → exhaustion (if overtrained/under-recovered)',
      ],
    },
    {
      id: 'opt-l3',
      title: 'SAID principle and overload',
      plain: `SAID means the body adapts *specifically* to the demand you place on it. Train slow and steady → you get better at slow and steady. Train heavy and low-rep → you get stronger, not more "toned." Overload just means you have to keep asking the body to do a little more than it's used to, or it has no reason to change.`,
      nasm: `The SAID principle (Specific Adaptation to Imposed Demands) states the body adapts to the specific demands placed upon it. The principle of overload states that a program must continually place increased demands on the body for continual improvements to occur.`,
      mustMemorise: ['SAID = Specific Adaptation to Imposed Demands'],
    },
  ],
  items: [
    {
      kind: 'typein', id: 'opt-t1', tags: ['opt', 'phases'],
      prompt: 'What are the 3 building blocks of the OPT model, in order?',
      accept: ['stabilization strength power', 'stabilization, strength, power'],
      hints: ['Each block is a group of phases.', 'S___________ , S________, P_____'],
      explanation: 'The OPT model progresses through Stabilization → Strength → Power.',
    },
    {
      kind: 'typein', id: 'opt-t2', tags: ['opt', 'phases'],
      prompt: 'Name Phase 1 of the OPT model.',
      accept: ['stabilization endurance'],
      hints: ['It focuses on muscular endurance and joint stability.', 'S___________ E________'],
      explanation: 'Phase 1 is Stabilization Endurance — the foundation phase for every client.',
    },
    {
      kind: 'typein', id: 'opt-t3', tags: ['opt', 'phases'],
      prompt: 'Name Phase 3 of the OPT model.',
      accept: ['muscular development', 'hypertrophy'],
      hints: ['This is the classic "bodybuilding" phase.', 'M________ D___________'],
      explanation: 'Phase 3 is Muscular Development, also called hypertrophy training.',
    },
    {
      kind: 'typein', id: 'opt-t4', tags: ['opt', 'phases'],
      prompt: 'Name Phase 4 of the OPT model.',
      accept: ['maximal strength'],
      hints: ['Very heavy loads, very low reps.', 'M______ S________'],
      explanation: 'Phase 4 is Maximal Strength — the heaviest, lowest-rep phase.',
    },
    {
      kind: 'typein', id: 'opt-t5', tags: ['opt', 'periodization'],
      prompt: 'What is the smallest unit of periodization, typically covering one week?',
      accept: ['microcycle'],
      hints: ['It is nested inside a mesocycle.', 'M_________'],
      explanation: 'A microcycle is the smallest training block, typically one week.',
    },
    {
      kind: 'typein', id: 'opt-t6', tags: ['opt', 'periodization'],
      prompt: 'What term describes a macrocycle, typically covering one year of training?',
      accept: ['macrocycle'],
      hints: ['It is the biggest planning unit.', 'M_________'],
      explanation: 'A macrocycle is the largest periodization unit, typically one year.',
    },
    {
      kind: 'typein', id: 'opt-t7', tags: ['opt', 'said'],
      prompt: 'Give the full name of the SAID principle.',
      accept: ['specific adaptation to imposed demands'],
      hints: ['Each letter stands for a word describing how the body adapts.', 'S______ A________ to I______ D______'],
      explanation: 'SAID = Specific Adaptation to Imposed Demands.',
    },
    {
      kind: 'mcq', id: 'opt-m1', tags: ['opt', 'phases'], source: 'original',
      prompt: 'A brand-new client with no training history and mild low-back discomfort should begin in which OPT phase?',
      options: ['Phase 1 – Stabilization Endurance', 'Phase 3 – Muscular Development', 'Phase 4 – Maximal Strength', 'Phase 5 – Power'],
      answer: 0,
      explanation: 'All clients, regardless of goal, begin in Phase 1 to build stabilization and joint control first, especially with existing discomfort.',
      whyWrong: [
        '',
        'Phase 3 assumes the client already has stabilization and strength endurance in place.',
        'Phase 4 uses very heavy loads that require a stable, prepared kinetic chain first.',
        'Phase 5 (Power) requires a strength base and excellent stabilization to be safe.',
      ],
    },
    {
      kind: 'mcq', id: 'opt-m2', tags: ['opt', 'periodization'], source: 'original',
      prompt: 'Which best describes a mesocycle?',
      options: [
        'A single training session',
        'A smaller training block of weeks to months within the macrocycle',
        'The entire one-year training plan',
        'A single set of an exercise',
      ],
      answer: 1,
      explanation: 'A mesocycle is a training block of weeks to months that sits between the macrocycle (year) and microcycle (week).',
      whyWrong: [
        'That is closer to a training session, not a mesocycle.',
        '',
        'That describes a macrocycle, not a mesocycle.',
        'That is far smaller than a mesocycle.',
      ],
    },
    {
      kind: 'order', id: 'opt-o1', tags: ['opt', 'phases'],
      prompt: 'Put the 5 OPT phases in the correct progressive order.',
      correctOrder: [
        'Stabilization Endurance',
        'Strength Endurance',
        'Muscular Development',
        'Maximal Strength',
        'Power',
      ],
      explanation: 'The OPT model always progresses Stabilization Endurance → Strength Endurance → Muscular Development → Maximal Strength → Power.',
    },
    {
      kind: 'match', id: 'opt-match1', tags: ['opt', 'periodization'],
      prompt: 'Match each periodization term to its typical timeframe.',
      pairs: [
        ['Macrocycle', 'Typically 1 year'],
        ['Mesocycle', 'Weeks to months'],
        ['Microcycle', 'Typically 1 week'],
      ],
      explanation: 'Macro (year) > Meso (weeks-months) > Micro (week) — biggest to smallest planning unit.',
    },
    { kind: 'typein', id: 'opt-t8', tags: ['opt', 'phases'], prompt: 'Name Phase 2 of the OPT model.', accept: ['strength endurance'], hints: ['Bridges stabilization and hypertrophy, uses supersets.', 'S________ E________'], explanation: 'Phase 2 is Strength Endurance.' },
    { kind: 'typein', id: 'opt-t9', tags: ['opt', 'phases'], prompt: 'Name Phase 5 of the OPT model.', accept: ['power'], hints: ['Force at speed.', 'P____'], explanation: 'Phase 5 is Power.' },
    { kind: 'typein', id: 'opt-t10', tags: ['opt', 'gas'], prompt: 'What does GAS stand for?', accept: ['general adaptation syndrome'], hints: ['Describes how the body responds to a training stressor.', 'G______ A________ S_______'], explanation: 'GAS = General Adaptation Syndrome.' },
    { kind: 'typein', id: 'opt-t11', tags: ['opt', 'gas'], prompt: 'Name the three stages of the General Adaptation Syndrome, in order.', accept: ['alarm resistance exhaustion', 'alarm, resistance, exhaustion'], hints: ['Starts with a shock response.', 'A____, R________, E________'], explanation: 'GAS stages: alarm reaction → resistance development → exhaustion.' },
    { kind: 'typein', id: 'opt-t12', tags: ['opt', 'principles'], prompt: 'Which training principle states you must continually increase demand for continued adaptation?', accept: ['overload', 'principle of overload'], hints: ['You must keep asking for more.', 'O________'], explanation: 'The principle of overload: continued progress requires progressively increased demand.' },
    { kind: 'typein', id: 'opt-t13', tags: ['opt', 'periodization'], prompt: 'Which periodization style alternates intensity and volume frequently (e.g. daily or weekly) rather than in fixed blocks?', accept: ['undulating', 'undulating periodization'], hints: ['The opposite of linear.', 'U_________'], explanation: 'Undulating (nonlinear) periodization varies volume/intensity frequently instead of in a single fixed progression.' },
    {
      kind: 'scenario', id: 'opt-s1', tags: ['opt', 'phases'],
      story: 'A client has trained consistently for 6 months and now moves comfortably through Phase 1 work. Their goal is to add visible muscle size.',
      question: 'What is the correct phase progression from here?',
      options: [
        'Jump straight to Phase 3 (Muscular Development), since that is the hypertrophy phase',
        'Progress to Phase 2 (Strength Endurance) before Phase 3',
        'Move to Phase 5 (Power) to stimulate growth',
        'Stay in Phase 1 indefinitely',
      ],
      answer: 1,
      explanation: 'The OPT model progresses sequentially. Even with a hypertrophy goal, the client moves Phase 1 → Phase 2 → Phase 3 to build strength endurance before muscular development.',
      whyWrong: ['Skipping Phase 2 bypasses the strength-endurance base the OPT model builds sequentially.', '', 'Phase 5 requires a strength base and does not primarily drive hypertrophy.', 'Remaining in Phase 1 would stall progress toward the stated hypertrophy goal.'],
    },
    {
      kind: 'scenario', id: 'opt-s2', tags: ['opt', 'gas'],
      story: 'A client has been training hard with no deload for 14 weeks. They report declining performance, poor sleep, persistent fatigue, and elevated resting heart rate.',
      question: 'Which stage of the General Adaptation Syndrome does this best describe?',
      options: ['Alarm reaction', 'Resistance development', 'Exhaustion', 'Supercompensation'],
      answer: 2,
      explanation: 'Sustained stress without adequate recovery drives the body into the exhaustion stage, where performance declines and overtraining symptoms appear.',
      whyWrong: ['Alarm reaction is the initial short-term shock response to a new stressor.', 'Resistance development is the productive adaptation stage, where performance improves.', '', 'Supercompensation describes the rebound above baseline after recovery, not this decline.'],
    },
    {
      kind: 'mcq', id: 'opt-m3', tags: ['opt', 'periodization'], source: 'original',
      prompt: 'A program runs 4 weeks of Phase 1, then 4 weeks of Phase 2, then 4 weeks of Phase 3, each block progressing in one direction. What periodization model is this?',
      options: ['Undulating periodization', 'Linear periodization', 'Random periodization', 'Reverse periodization'],
      answer: 1,
      explanation: 'Progressing block by block in a single direction over time is the definition of linear periodization.',
      whyWrong: ['Undulating periodization would vary intensity/volume frequently within and across weeks, not in one fixed direction.', '', '"Random periodization" is not a recognized NASM model.', 'Reverse periodization starts with high intensity/low volume and moves the other way; that is not what is described.'],
    },
    {
      kind: 'mcq', id: 'opt-m4', tags: ['opt', 'phases'], source: 'original',
      prompt: 'Which OPT phase is described as "mastering basic movement patterns"?',
      options: ['Phase 1 – Stabilization Endurance', 'Phase 2 – Strength Endurance', 'Phase 3 – Muscular Development', 'Phase 5 – Power'],
      answer: 0,
      explanation: 'Phase 1 builds foundational movement control and joint stability before load, speed, or size are pursued.',
      whyWrong: ['', 'Phase 2 introduces supersetted strength work on top of an existing stabilization base.', 'Phase 3 focuses on muscular growth, not basic pattern mastery.', 'Phase 5 focuses on rate of force production.'],
    },
    {
      kind: 'mcq', id: 'opt-m5', tags: ['opt', 'building-blocks'], source: 'original',
      prompt: 'Which phases belong to the Strength building block of the OPT model?',
      options: ['Phase 1 only', 'Phases 2, 3, and 4', 'Phases 3 and 5', 'Phases 4 and 5'],
      answer: 1,
      explanation: 'The Strength building block contains Phases 2 (Strength Endurance), 3 (Muscular Development), and 4 (Maximal Strength).',
      whyWrong: ['Phase 1 alone is the Stabilization building block.', '', 'Phase 5 belongs to the Power building block, not Strength.', 'Phase 5 is Power, so this pairing is incorrect.'],
    },
    {
      kind: 'mcq', id: 'opt-m6', tags: ['opt', 'said'], source: 'original',
      prompt: 'A client trains exclusively with slow, heavy, low-rep lifts, then complains they have not improved their 5K time. Which principle explains this?',
      options: ['Principle of overload', 'SAID principle', 'Davis\'s law', 'Reciprocal inhibition'],
      answer: 1,
      explanation: 'SAID (Specific Adaptation to Imposed Demands): the body adapts specifically to the demand placed on it, so heavy low-rep training produces strength, not endurance adaptations.',
      whyWrong: ['Overload concerns increasing demand over time, not the specificity of the adaptation.', '', 'Davis\'s law concerns soft tissue remodeling along lines of stress.', 'Reciprocal inhibition concerns muscle-pair neural relationships, not training specificity.'],
    },
    {
      kind: 'match', id: 'opt-match2', tags: ['opt', 'phases'],
      prompt: 'Match each OPT phase to its primary adaptation.',
      pairs: [
        ['Phase 1', 'Muscular endurance and joint stability'],
        ['Phase 2', 'Strength endurance (strength + stabilization superset)'],
        ['Phase 3', 'Muscular hypertrophy'],
        ['Phase 4', 'Maximal strength / motor unit recruitment'],
        ['Phase 5', 'Rate of force production (power)'],
      ],
      explanation: 'Each phase targets a distinct adaptation, progressing from stability through size and strength to speed of force production.',
    },
    { kind: 'typein', id: 'opt-t14', tags: ['opt', 'periodization'], prompt: 'Which periodization term describes a training block of weeks to months?', accept: ['mesocycle'], hints: ['Between macro and micro.', 'M________'], explanation: 'A mesocycle is a training block of weeks to months.' },
    { kind: 'typein', id: 'opt-t15', tags: ['opt', 'principles'], prompt: 'Which training principle states that programs must be varied to avoid plateaus and overtraining?', accept: ['variation', 'principle of variation'], hints: ['Keep changing it.', 'V________'], explanation: 'The principle of variation calls for planned changes in programming to avoid plateaus and overtraining.' },
  ],
}
