import type { Module } from '../../types/content'

export const vtZoneLab: Module = {
  id: 'd3-cardio-programming',
  domainId: 'd3',
  title: 'VT & Zone Lab: Cardiorespiratory Training',
  estMinutes: 30,
  lessons: [
    {
      id: 'vt-l1',
      title: 'Finding max heart rate',
      plain: `The quick-and-dirty way to estimate someone's max heart rate is "220 minus their age." A 40-year-old's estimated max is 180 bpm. It's not perfect, but it's the number NASM wants you to know cold.`,
      nasm: `Maximum heart rate (HRmax) is commonly estimated using the age-predicted formula: 220 − age. An alternative formula, 208 − (0.7 × age), may provide a more accurate estimate for some populations.`,
      mustMemorise: ['HRmax = 220 − age', 'Alternate: HRmax = 208 − (0.7 × age)'],
    },
    {
      id: 'vt-l2',
      title: 'Karvonen formula: using resting heart rate too',
      plain: `Straight percentage of max heart rate ignores how fit someone already is. The Karvonen formula fixes that by first finding "heart rate reserve" (max minus resting), taking a percentage of THAT, then adding resting heart rate back. It personalizes the target to the individual, not just their age.`,
      nasm: `The Karvonen formula calculates target heart rate using heart rate reserve (HRR): Target HR = ((HRmax − HRrest) × intensity%) + HRrest. This method accounts for individual differences in resting heart rate and cardiorespiratory fitness.`,
      mustMemorise: ['Karvonen: Target HR = ((HRmax − HRrest) × %) + HRrest'],
    },
    {
      id: 'vt-l3',
      title: 'The three training zones',
      plain: `Zone 1 is easy — you can hold a full conversation, this is where fat burns best and where beginners live. Zone 2 is the gray zone where talking gets hard; it sits between two invisible thresholds called VT1 and VT2. Zone 3 is hard effort where you can't talk at all, mostly fueled by carbs.`,
      nasm: `Zone 1 training occurs below the first ventilatory threshold (VT1) at approximately 65–75% HRmax, with the talk test indicating comfortable conversation. Zone 2 occurs between VT1 and VT2 (76–85% HRmax), where conversation becomes difficult. Zone 3 occurs above VT2 (86–95% HRmax), where talking is not possible.`,
      table: {
        headers: ['Zone', '% HRmax', 'Talk test', 'Fuel'],
        rows: [
          ['1', '65–75%', 'Comfortable conversation', 'Mostly fat'],
          ['2', '76–85%', 'Difficult to talk', 'Mixed fat + carb'],
          ['3', '86–95%', 'Cannot talk', 'Mostly carbohydrate'],
        ],
      },
      mustMemorise: [
        'Zone 1 = 65–75% HRmax, below VT1',
        'Zone 2 = 76–85% HRmax, VT1 to VT2',
        'Zone 3 = 86–95% HRmax, above VT2',
      ],
    },
    {
      id: 'vt-l4',
      title: 'VT2 and the three training stages',
      plain: `VT2 is the hardest pace someone can hold for a real amount of time without completely blowing up — think of it as "comfortably hard becomes just hard." NASM also groups clients into 3 stages: Stage I clients only do Zone 1 until they can sustain it for 30 minutes, 3 times a week. Stage II adds Zone 2 intervals. Stage III (advanced clients) uses all three zones.`,
      nasm: `The second ventilatory threshold (VT2) represents the highest exercise intensity that can be sustained aerobically for more than a few minutes before a rapid shift toward anaerobic metabolism. Training is organized into three stages: Stage I (Zone 1 only, progressing to Stage II once 30 minutes can be sustained 3x/week), Stage II (Zone 1–2 interval training), and Stage III (Zone 1–3, for advanced clients).`,
      mustMemorise: [
        'VT2 = highest sustainable steady-state intensity for more than a few minutes',
        'Stage I = Zone 1 only; progress once 30 min sustained, 3x/week',
        'Stage II = Zones 1–2 intervals',
        'Stage III = Zones 1–3 (advanced)',
      ],
    },
  ],
  items: [
    {
      kind: 'typein', id: 'vt-t1', tags: ['cardio', 'hrmax'],
      prompt: 'Formula for estimated maximum heart rate (the classic one)?',
      accept: ['220-age', '220 minus age', '220 - age'],
      hints: ['One number minus their age.', '2__ − age'],
      explanation: 'HRmax = 220 − age.',
    },
    {
      kind: 'typein', id: 'vt-t2', tags: ['cardio', 'karvonen'],
      prompt: 'What is the name of the formula that uses heart rate reserve (HRmax − HRrest) to set a target heart rate?',
      accept: ['karvonen', 'karvonen formula'],
      hints: ['Named after its creator.', 'K_______'],
      explanation: 'The Karvonen formula: Target HR = ((HRmax − HRrest) × %) + HRrest.',
    },
    {
      kind: 'typein', id: 'vt-t3', tags: ['cardio', 'zones'],
      prompt: '% HRmax range for Zone 1?',
      accept: ['65-75%', '65-75 percent', '65 to 75%'],
      hints: ['The easiest, most conversational zone.', '__-__%'],
      explanation: 'Zone 1 = 65–75% HRmax.',
    },
    {
      kind: 'typein', id: 'vt-t4', tags: ['cardio', 'zones'],
      prompt: '% HRmax range for Zone 3?',
      accept: ['86-95%', '86-95 percent', '86 to 95%'],
      hints: ['The hardest zone, cannot talk.', '__-__%'],
      explanation: 'Zone 3 = 86–95% HRmax.',
    },
    {
      kind: 'typein', id: 'vt-t5', tags: ['cardio', 'stages'],
      prompt: 'Which training stage uses Zone 1 only?',
      accept: ['stage 1', 'stage i'],
      hints: ['The beginner stage.', 'Stage _'],
      explanation: 'Stage I uses Zone 1 only, until 30 minutes can be sustained 3x/week.',
    },
    {
      kind: 'mcq', id: 'vt-m1', tags: ['cardio', 'karvonen'], source: 'original',
      prompt: 'A 35-year-old client has a resting HR of 60 bpm. Using Karvonen at 70% intensity, what is the target heart rate? (HRmax = 220 − age)',
      options: ['148 bpm', '130 bpm', '185 bpm', '166 bpm'],
      answer: 0,
      explanation: 'HRmax = 220−35 = 185. HRR = 185−60 = 125. 125×0.70 = 87.5 ≈ 88. Target = 88+60 = 148 bpm.',
      whyWrong: ['', 'This is straight 70% of HRmax (185×0.7≈130), which ignores resting heart rate — not the Karvonen method.', 'This is HRmax itself, not a 70% target.', 'This overshoots the correct Karvonen target.'],
    },
    {
      kind: 'mcq', id: 'vt-m2', tags: ['cardio', 'zones'], source: 'original',
      prompt: 'A client says talking has become difficult but they are not gasping for air. Which zone are they most likely in?',
      options: ['Zone 1', 'Zone 2', 'Zone 3', 'They are resting'],
      answer: 1,
      explanation: 'Difficulty talking (but not complete inability) is the hallmark talk-test description of Zone 2, between VT1 and VT2.',
      whyWrong: ['Zone 1 allows comfortable conversation.', '', 'Zone 3 means the client cannot talk at all.', 'This describes active cardio effort, not rest.'],
    },
    { kind: 'typein', id: 'vt-t6', tags: ['cardio', 'zones'], prompt: '% HRmax range for Zone 2?', accept: ['76-85%', '76-85'], hints: ['Between Zone 1 and Zone 3.', '__-__%'], explanation: 'Zone 2 = 76–85% HRmax, sitting between VT1 and VT2.' },
    { kind: 'typein', id: 'vt-t7', tags: ['cardio', 'thresholds'], prompt: 'Which ventilatory threshold marks the point where talking first becomes difficult (the Zone 1 / Zone 2 border)?', accept: ['vt1', 'first ventilatory threshold'], hints: ['The lower of the two thresholds.', 'VT_'], explanation: 'VT1 marks the transition from Zone 1 to Zone 2, where conversation starts to break down.' },
    { kind: 'typein', id: 'vt-t8', tags: ['cardio', 'stages'], prompt: 'Which training stage uses Zone 1 and Zone 2 interval work?', accept: ['stage 2', 'stage ii'], hints: ['The middle stage.', 'Stage _'], explanation: 'Stage II introduces Zone 1–2 intervals once a client can sustain Zone 1 for 30 minutes, 3x/week.' },
    { kind: 'typein', id: 'vt-t9', tags: ['cardio', 'stages'], prompt: 'Which training stage uses all three zones and is reserved for advanced clients?', accept: ['stage 3', 'stage iii'], hints: ['The most advanced stage.', 'Stage _'], explanation: 'Stage III uses Zones 1–3 and is appropriate only for advanced clients.' },
    { kind: 'typein', id: 'vt-t10', tags: ['cardio', 'guidelines'], prompt: 'How many minutes of MODERATE-intensity cardio per week do general guidelines recommend?', accept: ['150', '150 minutes', '150 min'], hints: ['A three-digit number.', '___ minutes'], explanation: '150 minutes of moderate-intensity activity per week (or 75 minutes vigorous).' },
    { kind: 'typein', id: 'vt-t11', tags: ['cardio', 'guidelines'], prompt: 'How many minutes of VIGOROUS-intensity cardio per week do general guidelines recommend?', accept: ['75', '75 minutes', '75 min'], hints: ['Half the moderate recommendation.', '__ minutes'], explanation: '75 minutes of vigorous-intensity activity per week.' },
    { kind: 'typein', id: 'vt-t12', tags: ['cardio', 'fuel'], prompt: 'Which fuel source dominates in Zone 1 training?', accept: ['fat', 'mostly fat'], hints: ['The slower-burning fuel.', 'F__'], explanation: 'Zone 1 relies predominantly on fat oxidation.' },
    { kind: 'typein', id: 'vt-t13', tags: ['cardio', 'phases'], prompt: 'Name the three traditional components (phases) of a cardiorespiratory training session.', accept: ['warm-up conditioning cool-down', 'warm up, conditioning, cool down'], hints: ['Beginning, middle, end.', 'W___-__, C__________, C___-____'], explanation: 'A cardio session is structured as warm-up, conditioning, and cool-down.' },
    { kind: 'typein', id: 'vt-t14', tags: ['cardio', 'hrmax'], prompt: 'What is the alternate HRmax formula (not 220 − age)?', accept: ['208 - 0.7 x age', '208 minus 0.7 times age', '208-0.7 x age'], hints: ['Starts with 208.', '208 − (0._ × age)'], explanation: 'The alternate formula is 208 − (0.7 × age).' },
    {
      kind: 'scenario', id: 'vt-s1', tags: ['cardio', 'stages'],
      story: 'A new, deconditioned client can only sustain Zone 1 effort for about 12 minutes before needing to stop, and trains twice a week.',
      question: 'Which stage should they train in, and what must happen before progressing?',
      options: [
        'Stage I; progress once they can sustain Zone 1 for 30 minutes, 3 times per week',
        'Stage II; progress once they can complete 20 intervals',
        'Stage III; progress once heart rate recovery improves',
        'Stage II; progress once they can sustain Zone 2 for 30 minutes',
      ],
      answer: 0,
      explanation: 'Stage I is Zone 1 only. The progression criterion to Stage II is sustaining Zone 1 for at least 30 minutes, 3 times per week.',
      whyWrong: ['', 'Stage II is premature for a client who cannot yet sustain 30 minutes in Zone 1.', 'Stage III is for advanced clients using all three zones.', 'The criterion is based on Zone 1 duration/frequency, not Zone 2.'],
    },
    {
      kind: 'scenario', id: 'vt-s2', tags: ['cardio', 'karvonen'],
      story: 'A 50-year-old client has a resting heart rate of 70 bpm. The trainer wants them working at 60% intensity using the Karvonen method.',
      question: 'What is the target heart rate?',
      options: ['112 bpm', '102 bpm', '130 bpm', '95 bpm'],
      answer: 2,
      explanation: 'HRmax = 220 − 50 = 170. Heart rate reserve = 170 − 70 = 100. 100 × 0.60 = 60. Target = 60 + 70 = 130 bpm.',
      whyWrong: [
        'This would result from subtracting rather than adding resting HR back, or from an incorrect HRR.',
        'This is 60% of HRmax (170 × 0.60 = 102), which ignores resting heart rate — that is the straight %HRmax method, not Karvonen.',
        '',
        'This undershoots the target; it does not follow from the Karvonen calculation.',
      ],
    },
    {
      kind: 'mcq', id: 'vt-m3', tags: ['cardio', 'thresholds'], source: 'original',
      prompt: 'What does VT2 represent?',
      options: [
        'The highest intensity that can be sustained for only a few seconds',
        'The highest sustainable steady-state intensity that can be held for more than a few minutes',
        'The point where fat and carbohydrate are used equally',
        'The intensity at which a client can speak in full sentences comfortably',
      ],
      answer: 1,
      explanation: 'VT2 is the highest steady-state intensity sustainable for more than a few minutes before anaerobic metabolism dominates.',
      whyWrong: ['VT2 is sustainable for minutes, not seconds.', '', 'That describes a fuel crossover point, not VT2.', 'Comfortable full-sentence conversation describes Zone 1, below VT1.'],
    },
    {
      kind: 'mcq', id: 'vt-m4', tags: ['cardio', 'hiit'], source: 'original',
      prompt: 'Which statement about true Tabata protocol is accurate?',
      options: [
        '8 rounds of 20s work / 10s rest — 4 minutes total at roughly 170% VO2max',
        '10 rounds of 30s work / 30s rest — 10 minutes total',
        '20 minutes continuous at 85% HRmax',
        '4 rounds of 60s work / 60s rest at moderate intensity',
      ],
      answer: 0,
      explanation: 'The original Tabata protocol is 8 × (20s work / 10s rest) = 4 minutes total, at an intensity around 170% of VO2max.',
      whyWrong: ['', 'This does not match the original Tabata work/rest structure or duration.', 'Tabata is interval-based, not continuous steady state.', 'This work/rest ratio and intensity do not match the Tabata protocol.'],
    },
    {
      kind: 'mcq', id: 'vt-m5', tags: ['cardio', 'talk-test'], source: 'original',
      prompt: 'A client on a treadmill can no longer speak at all and is breathing very hard. Which zone are they in?',
      options: ['Zone 1', 'Zone 2', 'Zone 3', 'Below VT1'],
      answer: 2,
      explanation: 'Inability to talk at all indicates working above VT2, which is Zone 3 (86–95% HRmax).',
      whyWrong: ['Zone 1 allows comfortable conversation.', 'Zone 2 makes talking difficult but not impossible.', '', 'Below VT1 is Zone 1, the easiest zone.'],
    },
    {
      kind: 'mcq', id: 'vt-m6', tags: ['cardio', 'fittevp'], source: 'original',
      prompt: 'In the FITTE-VP acronym used for cardio program design, what does the first "T" stand for?',
      options: ['Tempo', 'Time', 'Threshold', 'Type'],
      answer: 1,
      explanation: 'FITTE-VP = Frequency, Intensity, Time, Type, Enjoyment, Volume, Progression. The first T is Time; the second is Type.',
      whyWrong: ['Tempo is a resistance-training acute variable, not part of FITTE-VP.', '', 'Threshold is not part of the acronym.', 'Type is the second T, not the first.'],
    },
    {
      kind: 'match', id: 'vt-match1', tags: ['cardio', 'zones'],
      prompt: 'Match each zone to its talk-test description.',
      pairs: [
        ['Zone 1 (65–75% HRmax)', 'Can hold a comfortable conversation'],
        ['Zone 2 (76–85% HRmax)', 'Talking becomes difficult'],
        ['Zone 3 (86–95% HRmax)', 'Cannot talk'],
      ],
      explanation: 'The talk test maps cleanly onto the three zones and the VT1/VT2 thresholds that separate them.',
    },
    {
      kind: 'match', id: 'vt-match2', tags: ['cardio', 'stages'],
      prompt: 'Match each training stage to the zones it uses.',
      pairs: [
        ['Stage I', 'Zone 1 only'],
        ['Stage II', 'Zones 1–2 (intervals)'],
        ['Stage III', 'Zones 1–3 (advanced)'],
      ],
      explanation: 'Stages add zones progressively: Zone 1 only, then Zone 1–2 intervals, then all three zones for advanced clients.',
    },
    { kind: 'typein', id: 'vt-t15', tags: ['cardio', 'zones'], prompt: 'Which zone sits BELOW VT1?', accept: ['zone 1', '1'], hints: ['The easiest zone.', 'Zone _'], explanation: 'Zone 1 is below VT1 — comfortable conversation is still possible.' },
    { kind: 'typein', id: 'vt-t16', tags: ['cardio', 'zones'], prompt: 'Which zone sits ABOVE VT2?', accept: ['zone 3', '3'], hints: ['The hardest zone.', 'Zone _'], explanation: 'Zone 3 is above VT2 — talking is not possible at this intensity.' },
  ],
}
