import type { McqItem } from '../types/content'

// Parsed from source/Questions_of_NASM_CPT.pdf (100 questions + answer key).
// Explanations and "why wrong" notes are original writing built around the
// supplied answer key, per NASM-Portal-SPEC.md §6 rule 5 (the sample-PDF
// questions are the user's own study material and may be used as-is; the
// surrounding teaching text is original). Domain tag (d1-d6) is a rough
// classification for future coverage tracking, not authoritative.
export const SAMPLE_PAPER: McqItem[] = [
  {
    kind: 'mcq', id: 'sp-1', source: 'sample-pdf', tags: ['sample-paper', 'd3'],
    prompt: 'What resistance training system involves a progressive or regressive step approach that either increases or decreases weight with each set?',
    options: ['Multiple-set system', 'Superset system', 'Complex training', 'Pyramid system'],
    answer: 3,
    explanation: 'A pyramid system steps weight up (or down) with each successive set, pairing a rep decrease with a load increase (or the reverse).',
    whyWrong: ['Multiple-set system uses the same load across several sets, not a step change.', 'A superset pairs two exercises back-to-back with no rest, not a weight-stepping pattern.', 'Complex training pairs a heavy strength exercise with a similar explosive exercise, not a step-load pattern.', ''],
  },
  {
    kind: 'mcq', id: 'sp-2', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'Which of the following benefits may occur as a result of exercises that comprise only eccentric muscle actions that are appropriately loaded?',
    options: ['Decreased catabolic hormone stimulation', 'Increased catabolic hormone stimulation', 'Decreased anabolic hormone stimulation', 'Increased anabolic hormone stimulation'],
    answer: 3,
    explanation: 'Appropriately loaded eccentric training has been shown to increase anabolic hormone stimulation, supporting muscle-building adaptations.',
    whyWrong: ['This is the opposite of the documented effect.', 'Catabolic hormone stimulation is not the highlighted effect of eccentric loading in this context.', 'This is the opposite of the documented effect.', ''],
  },
  {
    kind: 'mcq', id: 'sp-3', source: 'sample-pdf', tags: ['sample-paper', 'd4'],
    prompt: 'When performing a floor bridge exercise, why should you not raise the hips too far off the floor?',
    options: [
      'It may place too much stress on the lumbar spine through hyperflexion.',
      'It may place too much stress on the cervical spine through hyperflexion.',
      'It may place excessive stress on the thoracic spine through hyperflexion.',
      'It may place excessive stress on the lumbar spine through hyperextension.',
    ],
    answer: 3,
    explanation: 'Raising the hips too high arches (hyperextends) the low back, loading the lumbar spine in extension rather than keeping it neutral.',
    whyWrong: ['The floor bridge risk is hyperextension, not hyperflexion, and it is the lumbar spine, not another region.', 'The cervical spine is not the primary concern in a floor bridge.', 'The thoracic spine is not the primary concern in a floor bridge.', ''],
  },
  {
    kind: 'mcq', id: 'sp-4', source: 'sample-pdf', tags: ['sample-paper', 'd3'],
    prompt: 'Which benefit will positively affect the body through integrated training?',
    options: ['Improved sleep', 'Decreased fat loss', 'Decreased hormonal function', 'Increased rate of power decline'],
    answer: 0,
    explanation: 'Integrated, well-rounded training is associated with broad health benefits including improved sleep quality.',
    whyWrong: ['', 'Integrated training is associated with increased, not decreased, fat loss.', 'Integrated training supports, not decreases, hormonal function.', 'Integrated training slows, not increases, the rate of power decline.'],
  },
  {
    kind: 'mcq', id: 'sp-5', source: 'sample-pdf', tags: ['sample-paper', 'd4'],
    prompt: 'Which statement best describes the neurophysiological effect that occurs from myofascial rolling?',
    options: [
      'The direct roller compression leads to endocrine release of growth hormones, which leads to enhanced physical performance.',
      'The direct roller compression leads to delayed onset of muscle soreness 72 to 96 hours after rolling.',
      'The direct roller compression increases eccentric contraction to enhance muscle hypertrophy after the session.',
      'The direct roller compression may create tissue relaxation and pain reduction in tissues by stimulating nerve receptors.',
    ],
    answer: 3,
    explanation: 'Self-myofascial release (SMR) is thought to work by stimulating nerve receptors in the tissue, producing relaxation and reduced pain/tension, not by a hormonal or hypertrophy mechanism.',
    whyWrong: ['SMR is not described as triggering an endocrine growth-hormone release.', 'SMR is a recovery/preparation tool; it is not linked to causing DOMS.', 'SMR does not involve eccentric contraction — it is a passive compression technique.', ''],
  },
  {
    kind: 'mcq', id: 'sp-6', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'Which heart chamber gathers oxygenated blood coming to the heart from the lungs?',
    options: ['Left ventricle', 'Pulmonary veins', 'Right atrium', 'Left atrium'],
    answer: 3,
    explanation: 'The left atrium receives freshly oxygenated blood from the lungs via the pulmonary veins before passing it to the left ventricle.',
    whyWrong: ['The left ventricle pumps oxygenated blood out to the body, it does not receive it from the lungs.', 'The pulmonary veins are the vessels carrying the blood, not a heart chamber.', 'The right atrium receives deoxygenated blood returning from the body.', ''],
  },
  {
    kind: 'mcq', id: 'sp-7', source: 'sample-pdf', tags: ['sample-paper', 'd2'],
    prompt: 'Which muscle would be considered overactive, leading to the low back arching during the overhead squat assessment?',
    options: ['Gluteus maximus', 'Hip flexor complex', 'Gluteus medius', 'Hamstrings complex'],
    answer: 1,
    explanation: 'A tight hip flexor complex tilts the pelvis forward, arching the low back during the overhead squat.',
    whyWrong: ['Gluteus maximus is underactive in this compensation, not overactive.', '', 'Gluteus medius is associated with the knees-inward compensation, not low-back arching.', 'Hamstrings are underactive in this compensation, not overactive.'],
  },
  {
    kind: 'mcq', id: 'sp-8', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'How would age and overall health affect testosterone levels among men?',
    options: [
      'A reduction in testosterone levels occurs with age, and overall health may affect the degree of change.',
      'Age and overall health do not affect testosterone levels.',
      'A reduction in testosterone levels occurs with age, and overall health does not contribute to the change.',
      'Testosterone levels are not affected by age, as overall health is the primary reason for a decline.',
    ],
    answer: 0,
    explanation: 'Testosterone declines with age, and a person\'s overall health status can influence how much or how quickly that decline occurs.',
    whyWrong: ['', 'Both age and health status do influence testosterone.', 'Overall health does contribute to the degree of decline, it is not irrelevant.', 'Age is a well-established factor in testosterone decline, not merely overall health.'],
  },
  {
    kind: 'mcq', id: 'sp-9', source: 'sample-pdf', tags: ['sample-paper', 'd6'],
    prompt: 'What is the most appropriate response from a Certified Personal Trainer if a client insists on using a steroid or other harmful substance?',
    options: [
      'Tell them no, and refer them to a licensed medical professional for further advice.',
      'Tell them it could help with their training.',
      'Provide them with a plan and all the information they may need for use.',
      'Tell them no.',
    ],
    answer: 0,
    explanation: 'This is outside a trainer\'s scope of practice — the correct response is to decline and refer the client to a licensed medical professional.',
    whyWrong: ['', 'Endorsing use is unsafe and outside scope of practice.', 'Advising on substance use is far outside a trainer\'s scope of practice.', 'A flat "no" alone is incomplete — a proper referral is also required.'],
  },
  {
    kind: 'mcq', id: 'sp-10', source: 'sample-pdf', tags: ['sample-paper', 'd3'],
    prompt: 'Performing 4 weeks of stabilization training before moving on to strength endurance training for another 4 weeks would be an example of what kind of periodization?',
    options: ['Undulating periodization', 'Linear periodization', 'Nonlinear periodization', 'Localized periodization'],
    answer: 1,
    explanation: 'Progressing through one phase for a fixed block before moving to the next, in a single fixed direction, is the classic definition of linear periodization.',
    whyWrong: ['Undulating periodization varies intensity/volume more frequently (e.g. daily or weekly), not in one fixed 4-week block per phase.', '', 'Nonlinear periodization is the broader category that includes undulating models, not this simple block-to-block pattern.', '"Localized periodization" is not a standard NASM periodization term.'],
  },
  {
    kind: 'mcq', id: 'sp-11', source: 'sample-pdf', tags: ['sample-paper', 'd2'],
    prompt: 'When sequencing physiological assessments, which of the following would produce a better result if measured immediately after exercise rather than before exercise?',
    options: ['Resting heart rate', 'Blood pressure', 'Body composition', 'Flexibility'],
    answer: 3,
    explanation: 'Muscles and connective tissue are more pliable after the body is warmed up, so flexibility assessments are better performed after some activity.',
    whyWrong: ['Resting heart rate must, by definition, be measured at rest, not after exercise.', 'Blood pressure is typically measured at rest for a baseline reading, not immediately post-exercise.', 'Body composition should be measured at rest/baseline conditions, not post-exercise.', ''],
  },
  {
    kind: 'mcq', id: 'sp-12', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'Which of the following would make a person better at oxidizing fat?',
    options: ['Having more glycogen stored in their muscle', 'Having more mitochondria in their muscle', 'Having more fat stored on their body', 'Having less oxygen delivery to the muscle'],
    answer: 1,
    explanation: 'Fat oxidation happens in the mitochondria; more mitochondria means a greater capacity to burn fat for fuel.',
    whyWrong: ['Glycogen storage relates to carbohydrate fuel use, not fat-oxidizing capacity.', '', 'Having more stored body fat does not by itself improve the ability to oxidize fat.', 'Fat oxidation is an oxidative (aerobic) process — less oxygen delivery would impair it, not help it.'],
  },
  {
    kind: 'mcq', id: 'sp-13', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'What type of health concern is the leading cause of death in the world today?',
    options: ['Alcohol', 'Acute diseases', 'Chronic diseases and conditions', 'Injuries'],
    answer: 2,
    explanation: 'Chronic diseases and conditions (heart disease, diabetes, etc.) are the leading cause of death worldwide, which is a core reason NASM frames the trainer\'s role as preventive care.',
    whyWrong: ['Alcohol use is a risk factor, not itself classified as the leading cause of death.', 'Acute diseases are short-term illnesses and are not the leading cause of death.', '', 'Injuries are a significant cause of death but not the leading one.'],
  },
  {
    kind: 'mcq', id: 'sp-14', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'Which individual is suffering from an acute disease?',
    options: ['Jorge, who is sick with the flu', 'Roger, who has type 2 diabetes', 'Tricia, who has type 1 diabetes', 'Perry, who suffers from a congenital heart condition'],
    answer: 0,
    explanation: 'The flu is a short-term, acute illness. The other three are chronic, ongoing conditions.',
    whyWrong: ['', 'Type 2 diabetes is a chronic condition, not acute.', 'Type 1 diabetes is a chronic condition, not acute.', 'A congenital heart condition is a chronic, lifelong condition, not acute.'],
  },
  {
    kind: 'mcq', id: 'sp-15', source: 'sample-pdf', tags: ['sample-paper', 'd4'],
    prompt: 'Which of the following would be the appropriate progression for a core training program to optimize function?',
    options: [
      'Movement efficiency, intervertebral stability, lumbopelvic stability',
      'Lumbopelvic stability, intervertebral stability, movement efficiency',
      'Lumbopelvic stability, movement efficiency, intervertebral stability',
      'Intervertebral stability, lumbopelvic stability, movement efficiency',
    ],
    answer: 3,
    explanation: 'Core training progresses from the deepest, smallest stabilizers outward: intervertebral stability first, then lumbopelvic stability, then whole-body movement efficiency.',
    whyWrong: ['This order is reversed — movement efficiency is the last stage, not the first.', 'This starts one step too late in the progression.', 'This order skips ahead before returning, which is not the correct sequence.', ''],
  },
  {
    kind: 'mcq', id: 'sp-16', source: 'sample-pdf', tags: ['sample-paper', 'd3'],
    prompt: 'Which of the following does not meet the criteria for exercise or activity to be considered aerobic?',
    options: ['The exercise is continuous in nature.', 'The exercise targets large muscle groups.', 'The exercise is intense.', 'The exercise is rhythmic.'],
    answer: 2,
    explanation: 'Aerobic activity is defined by being continuous, rhythmic, and using large muscle groups — "intense" is not part of that definition (aerobic work is typically submaximal, sustained effort).',
    whyWrong: ['Continuous is one of the defining criteria for aerobic exercise.', 'Using large muscle groups is one of the defining criteria for aerobic exercise.', '', 'Rhythmic is one of the defining criteria for aerobic exercise.'],
  },
  {
    kind: 'mcq', id: 'sp-17', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'What are the two components of the central nervous system?',
    options: ['The brain and spinal cord', 'The sympathetic and parasympathetic nervous systems', 'The somatic and autonomic nervous systems', 'The nerves and sensory receptors'],
    answer: 0,
    explanation: 'The central nervous system (CNS) consists of the brain and spinal cord.',
    whyWrong: ['', 'Sympathetic/parasympathetic are subdivisions of the autonomic (peripheral) nervous system, not the CNS.', 'Somatic/autonomic are subdivisions of the peripheral nervous system, not the CNS.', 'Nerves and sensory receptors are part of the peripheral, not central, nervous system.'],
  },
  {
    kind: 'mcq', id: 'sp-18', source: 'sample-pdf', tags: ['sample-paper', 'd4'],
    prompt: 'What is the general recommended rest between SAQ reps for beginner clients?',
    options: ['60 to 90 seconds', '90 to 120 seconds', '0 to 15 seconds', '15 to 60 seconds'],
    answer: 3,
    explanation: 'Beginner clients performing SAQ (speed, agility, quickness) drills generally rest 15–60 seconds between reps to allow adequate recovery for quality movement.',
    whyWrong: ['This range is longer than the general beginner recommendation.', 'This range is longer than the general beginner recommendation.', 'This range is shorter than the general beginner recommendation.', ''],
  },
  {
    kind: 'mcq', id: 'sp-19', source: 'sample-pdf', tags: ['sample-paper', 'd4'],
    prompt: 'When observing sprint mechanics, which joint action should you see occurring in the rear leg if proper form is used?',
    options: ['Knee flexion', 'Ankle plantar flexion', 'Ankle dorsiflexion', 'Hip abduction'],
    answer: 1,
    explanation: 'In good sprint mechanics, the rear (back-side) leg drives through ankle plantarflexion as it pushes off the ground.',
    whyWrong: ['Knee flexion in the rear leg is part of recovery, not the defining push-off action being tested here.', '', 'Ankle dorsiflexion is characteristic of the lead (front-side) leg preparing to strike the ground.', 'Hip abduction is not a defining rear-leg sprint mechanic.'],
  },
  {
    kind: 'mcq', id: 'sp-20', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'The deep longitudinal subsystem includes which of the following muscle groups?',
    options: [
      'Hamstrings and erector spinae',
      'Adductors (inner thigh) and contralateral quadratus lumborum',
      'Thoracolumbar fascia and contralateral gluteus maximus',
      'Adductors (inner thigh) and hip external rotators',
    ],
    answer: 0,
    explanation: 'The deep longitudinal subsystem includes the erector spinae, thoracolumbar fascia, sacrotuberous ligament, biceps femoris (hamstrings), and peroneals — hamstrings and erector spinae are both core members.',
    whyWrong: ['', 'This combination describes the lateral subsystem, not the deep longitudinal subsystem.', 'Gluteus maximus paired contralaterally with the lat is part of the posterior oblique subsystem, not the deep longitudinal subsystem.', 'This combination is not part of the deep longitudinal subsystem.'],
  },
  {
    kind: 'mcq', id: 'sp-21', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'Movement represents the integrated functioning of which three main body systems?',
    options: ['Nervous, skeletal, and vascular', 'Muscular, ligamentous, and skeletal', 'Nervous, ligamentous, and vascular', 'Muscular, nervous, and skeletal'],
    answer: 3,
    explanation: 'Human movement is produced by the integrated function of the muscular, nervous, and skeletal systems (sometimes called the "kinetic chain").',
    whyWrong: ['The vascular system is not one of the three core movement systems in this model.', 'Ligamentous tissue is not one of the three core movement systems in this model.', 'The vascular system is not one of the three core movement systems in this model.', ''],
  },
  {
    kind: 'mcq', id: 'sp-22', source: 'sample-pdf', tags: ['sample-paper', 'd5'],
    prompt: 'A Certified Personal Trainer has been listening to a client\'s goals. After the client is done speaking, the trainer restates the goals back to the client. What best describes the approach the trainer is using?',
    options: ['Reflective listening', 'Motivational interviewing', 'Active listening', 'Nonverbal communication'],
    answer: 0,
    explanation: 'Restating what the client said back to them, to confirm understanding, is reflective listening — one of the OARS techniques.',
    whyWrong: ['', 'Motivational interviewing is the broader counseling style, of which reflective listening is one specific technique.', 'Active listening is the general skill of attentive listening; the specific act of restating content is reflective listening.', 'Restating the client\'s words is a verbal technique, not nonverbal communication.'],
  },
  {
    kind: 'mcq', id: 'sp-23', source: 'sample-pdf', tags: ['sample-paper', 'd5'],
    prompt: 'Which of the following is a question that may promote change?',
    options: ['What might you want to change?', 'Why can’t you make this change to your schedule?', 'What makes you think that you’re not at risk?', 'Why don’t you just do this?'],
    answer: 0,
    explanation: 'Open, non-judgmental questions that invite the client to articulate their own motivation ("What might you want to change?") promote change talk.',
    whyWrong: ['', 'This is a confrontational, "why can\'t you" framing that tends to trigger defensiveness rather than change talk.', 'This is a challenging, judgmental framing rather than an open, change-promoting question.', 'This is a directive, "why don\'t you" framing that pushes the trainer\'s agenda rather than eliciting the client\'s own motivation.'],
  },
  {
    kind: 'mcq', id: 'sp-24', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'Which of the following global muscles\' primary action is hip flexion?',
    options: ['Latissimus dorsi', 'Iliopsoas', 'Erector spinae', 'Rectus abdominis'],
    answer: 1,
    explanation: 'The iliopsoas is the primary global hip flexor, part of the hip flexor complex.',
    whyWrong: ['Latissimus dorsi primarily extends/adducts/internally rotates the shoulder, it does not flex the hip.', '', 'Erector spinae primarily extends the spine, it does not flex the hip.', 'Rectus abdominis primarily flexes the spine/trunk, it is not the primary hip flexor.'],
  },
  {
    kind: 'mcq', id: 'sp-25', source: 'sample-pdf', tags: ['sample-paper', 'd2'],
    prompt: 'What BMI score is considered overweight?',
    options: ['30 to 34.9', '25 to 29.9', '35 to 39.9', '18.5 to 24.9'],
    answer: 1,
    explanation: 'A BMI of 25–29.9 is classified as overweight.',
    whyWrong: ['This range is classified as obese, not overweight.', '', 'This range is classified as obese, not overweight.', 'This range is classified as normal weight, not overweight.'],
  },
  {
    kind: 'mcq', id: 'sp-26', source: 'sample-pdf', tags: ['sample-paper', 'd3'],
    prompt: 'For an individual training in stage 1, what training volume and frequency would qualify that person to progress to stage 2?',
    options: [
      'Ability to maintain zone 1 intensity for at least 60 minutes, 2 times per week',
      'Ability to maintain zone 1 intensity for at least 45 minutes, 4 times per week',
      'Ability to maintain zone 1 intensity for at least 30 minutes, 5 times per week',
      'Ability to maintain zone 1 intensity for at least 30 minutes, 3 times per week',
    ],
    answer: 3,
    explanation: 'A client progresses from Stage I to Stage II once they can sustain Zone 1 intensity for at least 30 minutes, 3 times per week.',
    whyWrong: ['This exceeds the required duration and understates the required frequency.', 'This does not match the standard 30-minute, 3x/week progression criterion.', 'This overstates the required frequency.', ''],
  },
  {
    kind: 'mcq', id: 'sp-27', source: 'sample-pdf', tags: ['sample-paper', 'd5'],
    prompt: 'Research has demonstrated that moderate-intensity exercise is best for which of the following?',
    options: ['Winning a triathlon', 'Providing psychological benefits', 'Developing intrinsic motivation', 'Reducing burnout'],
    answer: 1,
    explanation: 'Moderate-intensity exercise is specifically associated with the greatest psychological benefits (mood, stress relief) compared to very low or very high intensities.',
    whyWrong: ['Winning a competitive event depends on sport-specific training, not simply "moderate intensity" as a general prescription.', '', 'Intrinsic motivation is influenced by many factors beyond exercise intensity alone.', 'Burnout reduction is not the specific, research-documented benefit tied to moderate intensity in this context.'],
  },
  {
    kind: 'mcq', id: 'sp-28', source: 'sample-pdf', tags: ['sample-paper', 'd2'],
    prompt: 'Which test would you select as the most appropriate when attempting to measure the overall fitness level of a fit college-aged athlete who competes on the school’s rugby team?',
    options: ['YMCA 3-minute step test', 'The talk test', 'Rockport 1-mile walk test', 'The 1.5-mile (2.4-km) run test'],
    answer: 3,
    explanation: 'The 1.5-mile run test is a higher-intensity assessment appropriate for already-fit, athletic populations, unlike the sub-maximal tests designed for general or deconditioned clients.',
    whyWrong: ['The YMCA step test is a sub-maximal test better suited to general/deconditioned populations.', 'The talk test is a subjective intensity check, not a fitness-level test for an athlete.', 'The Rockport walk test is designed for lower-fitness populations, not competitive athletes.', ''],
  },
  {
    kind: 'mcq', id: 'sp-29', source: 'sample-pdf', tags: ['sample-paper', 'd4'],
    prompt: 'With SAQ training, what is the recommended number of sets of each drill for young athletes to perform?',
    options: ['7 to 9 sets', '0 sets', '5 or 6 sets', '1 to 4 sets'],
    answer: 3,
    explanation: 'Young athletes performing SAQ drills are generally programmed for 1–4 sets per drill.',
    whyWrong: ['This is well above the recommended range for young athletes.', 'Zero sets means no SAQ training is performed, which is not the recommendation.', 'This is above the recommended range for young athletes.', ''],
  },
  {
    kind: 'mcq', id: 'sp-30', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'What is cardiac output?',
    options: [
      'The amount of blood remaining in the ventricle after contraction',
      'The volume of blood pumped by the heart per beat or contraction',
      'The volume of blood pumped by the heart per minute',
      'The amount of blood in the ventricle before contraction',
    ],
    answer: 2,
    explanation: 'Cardiac output is the total volume of blood the heart pumps per minute (heart rate × stroke volume).',
    whyWrong: ['This describes end-systolic volume, not cardiac output.', 'This describes stroke volume (per beat), not cardiac output (per minute).', '', 'This describes end-diastolic volume, not cardiac output.'],
  },
  {
    kind: 'mcq', id: 'sp-31', source: 'sample-pdf', tags: ['sample-paper', 'd2'],
    prompt: 'Which movement assessment utilizes weighted pullies to assess a pushing movement?',
    options: ['Standing overhead press', 'Standing pull assessment', 'Standing push assessment', 'Davies test'],
    answer: 2,
    explanation: 'The standing push assessment uses a cable/pulley setup to observe compensations during a pushing pattern.',
    whyWrong: ['This is not a standard NASM cable-based movement assessment.', 'The standing pull assessment evaluates a pulling motion, not a pushing motion.', '', 'The Davies test is an upper-body agility/stability performance test, not a cable push assessment.'],
  },
  {
    kind: 'mcq', id: 'sp-32', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'What is defined as the enlargement of skeletal muscle fibers in response to being recruited to develop increased levels of tension, as seen in resistance training?',
    options: ['Sarcopenia', 'Muscular atrophy', 'Osteopenia', 'Muscular hypertrophy'],
    answer: 3,
    explanation: 'Muscular hypertrophy is the enlargement of muscle fibers in response to tension/training stimulus.',
    whyWrong: ['Sarcopenia is the age-related loss of muscle mass, the opposite of this definition.', 'Muscular atrophy is a decrease in muscle size, the opposite of this definition.', 'Osteopenia relates to reduced bone density, not muscle fiber size.', ''],
  },
  {
    kind: 'mcq', id: 'sp-33', source: 'sample-pdf', tags: ['sample-paper', 'd2'],
    prompt: 'Which of the following is a recommendation when assessing skinfold measurements?',
    options: [
      'Do not give clients prior instructions about measurement protocol, as this can skew results.',
      'Take skinfold measurements immediately after exercise.',
      'Take a minimum of two measurements at each site; each measurement must be within 1 to 2 mm to take an average at each site.',
      'Do not open the jaw of the caliper before removing it from the site.',
    ],
    answer: 2,
    explanation: 'For accuracy, at least two skinfold measurements should be taken at each site, and they should agree within 1–2 mm before being averaged.',
    whyWrong: ['Clients should be informed about the protocol; withholding instructions is not a recommended practice.', 'Measurements should not be taken immediately after exercise, since fluid shifts can skew results.', '', 'The caliper jaw should be opened before removing it from the site, to avoid pinching and inaccurate readings.'],
  },
  {
    kind: 'mcq', id: 'sp-34', source: 'sample-pdf', tags: ['sample-paper', 'd3'],
    prompt: 'What is the recommended frequency for cardiorespiratory training if participating in moderate-intensity exercise like brisk walking?',
    options: ['4 times a week', '6 times a week', '3 times a week', '5 times a week'],
    answer: 3,
    explanation: 'General guidelines call for moderate-intensity cardio roughly 5 days per week (consistent with the 150 min/week moderate-intensity guideline).',
    whyWrong: ['This is below the general moderate-intensity frequency guideline.', 'This exceeds the general moderate-intensity frequency guideline.', 'This is below the general moderate-intensity frequency guideline.', ''],
  },
  {
    kind: 'mcq', id: 'sp-35', source: 'sample-pdf', tags: ['sample-paper', 'd5'],
    prompt: 'Which leadership component refers to the leader being a great example for how to live a healthy and balanced life, which includes being optimistic, empathetic, and knowledgeable?',
    options: ['Leader\'s qualities', 'The personality of the leader', 'Leader\'s style', 'The requirements of the leader'],
    answer: 0,
    explanation: 'These traits (optimistic, empathetic, knowledgeable, leading by example) are described as the leader\'s qualities.',
    whyWrong: ['', '"Personality" is not the specific NASM leadership term for this component.', 'Leadership "style" describes how a leader interacts/manages, not the specific trait list described here.', '"Requirements of the leader" is not the term used for this list of traits.'],
  },
  {
    kind: 'mcq', id: 'sp-36', source: 'sample-pdf', tags: ['sample-paper', 'd4'],
    prompt: 'If a client is having trouble maintaining form during a tuck jump exercise, what type of regression should be applied?',
    options: ['Being more explosive', 'Switch to single-leg power step-ups', 'Adding a stabilization pause between reps', 'Increasing speed'],
    answer: 2,
    explanation: 'When form breaks down on a plyometric exercise, the standard regression is to add a stabilization pause (hold the landing) to rebuild control before continuing.',
    whyWrong: ['Adding more explosiveness would make the exercise harder, not easier — the opposite of a regression.', 'Switching to a different, unrelated exercise is not the standard plyometric regression technique.', '', 'Increasing speed would make the exercise harder, not easier — the opposite of a regression.'],
  },
  {
    kind: 'mcq', id: 'sp-37', source: 'sample-pdf', tags: ['sample-paper', 'd4'],
    prompt: 'Why is it important for clients to learn how to accelerate, decelerate, and stabilize in all planes of motion?',
    options: ['Injuries often occur when rotating or moving laterally.', 'Athletic performance is a universal goal.', 'Multiplanar training eliminates the risk for injury.', 'Most injuries occur in the sagittal plane.'],
    answer: 0,
    explanation: 'Many real-world and sport injuries happen during rotational or lateral movements, so training control in the frontal and transverse planes (not just straight-ahead) reduces that risk.',
    whyWrong: ['', 'Not every client\'s goal is athletic performance, so this is not the core rationale.', 'Multiplanar training reduces risk, it does not eliminate it entirely.', 'Most non-sagittal-plane injuries are actually the concern being addressed, not sagittal-plane ones.'],
  },
  {
    kind: 'mcq', id: 'sp-38', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'What type of muscle action would expend the highest amount of energy at a fixed resistance level over a comparable duration?',
    options: ['Eccentric', 'Concentric', 'Isometric', 'Isotonic'],
    answer: 1,
    explanation: 'At a given fixed load, concentric (shortening) muscle actions cost the most metabolic energy compared to eccentric or isometric actions.',
    whyWrong: ['Eccentric actions are actually more metabolically efficient (lower energy cost) at a given load than concentric.', '', 'Isometric actions (no movement) typically cost less energy than concentric work at the same load.', 'Isotonic is a broader category (constant tension) that includes both concentric and eccentric, not a distinct higher-cost answer.'],
  },
  {
    kind: 'mcq', id: 'sp-39', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'What area of the chest contains the heart?',
    options: ['Myofibril', 'Ventricle', 'Mediastinum', 'Atrium'],
    answer: 2,
    explanation: 'The mediastinum is the central chest cavity that houses the heart, great vessels, and other structures.',
    whyWrong: ['A myofibril is a microscopic muscle-fiber structure, not a chest region.', 'A ventricle is a chamber within the heart, not the chest cavity containing it.', '', 'An atrium is a chamber within the heart, not the chest cavity containing it.'],
  },
  {
    kind: 'mcq', id: 'sp-40', source: 'sample-pdf', tags: ['sample-paper', 'd6'],
    prompt: 'What is something that allows a fitness professional to stand out from others in featuring their services?',
    options: ['Unique selling proposition (USP)', 'SWOT analysis', 'PERT estimate', 'Statement of work (SOW)'],
    answer: 0,
    explanation: 'A unique selling proposition (USP) is what differentiates a trainer\'s services from competitors.',
    whyWrong: ['', 'A SWOT analysis is a planning tool for evaluating strengths/weaknesses, not a marketing differentiator itself.', 'PERT estimation is a project-scheduling technique, unrelated to marketing differentiation.', 'A statement of work outlines project deliverables, it is not a marketing differentiator.'],
  },
  {
    kind: 'mcq', id: 'sp-41', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'What type of lever could be described as having a fulcrum in the middle like a seesaw?',
    options: ['Third class', 'Second class', 'Fourth class', 'First class'],
    answer: 3,
    explanation: 'A first-class lever has the fulcrum positioned between the effort and the load, like a seesaw.',
    whyWrong: ['A third-class lever has the effort between the fulcrum and the load (most common in the body), not a middle fulcrum.', 'A second-class lever has the load between the fulcrum and the effort, not a middle fulcrum.', 'There is no "fourth class" lever in standard classification.', ''],
  },
  {
    kind: 'mcq', id: 'sp-42', source: 'sample-pdf', tags: ['sample-paper', 'd3'],
    prompt: 'What is a physical benefit of resistance training?',
    options: ['Increased muscular hypertrophy', 'Increased resting heart rate', 'Decreased bone remodeling', 'Decreased muscular hypertrophy'],
    answer: 0,
    explanation: 'Resistance training stimulates increased muscular hypertrophy as a core physical adaptation.',
    whyWrong: ['', 'Resting heart rate typically decreases or stays stable with training, not increases, as a benefit.', 'Resistance training increases, not decreases, bone remodeling/density.', 'Resistance training increases, not decreases, hypertrophy.'],
  },
  {
    kind: 'mcq', id: 'sp-43', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'What is a kilocalorie (kcal)?',
    options: [
      'The amount of energy needed to raise 1 kilogram of water by 1 degree Celsius. It is equal to 1,000 food calories.',
      'Unlike 1 food calorie, this is the amount of energy needed to raise 1 kilogram of water by 1 degree Celsius.',
      'The amount of energy needed to raise 1 pound of water by 1 degree Celsius. It is also the same thing as 1 food calorie.',
      'The amount of energy needed to raise 1 kilogram of water by 1 degree Celsius. It is also the same thing as 1 food calorie.',
    ],
    answer: 3,
    explanation: 'A kilocalorie is the energy needed to raise 1 kg of water by 1°C, and it is the same unit commonly labeled "Calorie" (with a capital C) on food labels.',
    whyWrong: ['This incorrectly states a kilocalorie equals 1,000 food calories — a kilocalorie IS 1 food calorie.', 'This incorrectly claims a kilocalorie is unlike a food calorie — they are the same unit.', 'This uses the wrong mass unit (pound instead of kilogram) in the definition.', ''],
  },
  {
    kind: 'mcq', id: 'sp-44', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'Which part of a cell is responsible for using nutrients to create energy for the cell?',
    options: ['Electrolytes', 'Mitochondria', 'Organelles', 'Effector sites'],
    answer: 1,
    explanation: 'The mitochondria are the "powerhouse" organelles that convert nutrients into usable cellular energy (ATP).',
    whyWrong: ['Electrolytes are minerals involved in nerve/muscle signaling, not energy-producing structures.', '', '"Organelles" is a broad category that includes mitochondria but is not the specific energy-producing structure.', '"Effector sites" refers to target tissues acted on by the nervous system, not a cell energy structure.'],
  },
  {
    kind: 'mcq', id: 'sp-45', source: 'sample-pdf', tags: ['sample-paper', 'd6'],
    prompt: 'Before studying to become an NASM Certified Personal Trainer, Kim worked as a copywriter for a large ad agency. Now that she is working as a personal trainer at a fitness studio, she is looking for additional income opportunities. Which of the following would provide her with the best option for increasing her earning potential?',
    options: [
      'College instructor',
      'Marketing her services as a writer to create blogs and social media posts for her studio as well as other fitness professionals in her area',
      'Becoming an NASM Master Instructor',
      'College football conditioning coach',
    ],
    answer: 1,
    explanation: 'This directly leverages her existing copywriting skill set alongside her new fitness credential — a good example of using an existing skill for extra income streams, per NASM\'s business-development guidance.',
    whyWrong: ['This does not leverage her specific copywriting background.', 'Becoming a Master Instructor is a significant separate undertaking unrelated to her existing writing skill.', 'A college coaching role does not use her copywriting background and is a large career shift.', ''],
  },
  {
    kind: 'mcq', id: 'sp-46', source: 'sample-pdf', tags: ['sample-paper', 'd3'],
    prompt: 'Which of the following phases does not reflect the traditional components of cardiorespiratory training?',
    options: ['Interval phase', 'Cool-down phase', 'Warm-up phase', 'Conditioning phase'],
    answer: 0,
    explanation: 'The traditional structure of a cardio session is warm-up, conditioning, and cool-down — "interval phase" is not one of these three traditional components.',
    whyWrong: ['', 'Cool-down is one of the traditional three phases.', 'Warm-up is one of the traditional three phases.', 'Conditioning is one of the traditional three phases.'],
  },
  {
    kind: 'mcq', id: 'sp-47', source: 'sample-pdf', tags: ['sample-paper', 'd2'],
    prompt: 'Which of the following waist-to-hip ratios (WHRs) places Amy (a female) in the high-risk category for cardiovascular disease?',
    options: ['WHR of 0.88', 'WHR of 0.72', 'WHR of 0.78', 'WHR of 0.83'],
    answer: 0,
    explanation: 'For women, a WHR above 0.80 is considered high risk; 0.88 clearly exceeds that threshold.',
    whyWrong: ['', 'This is below the 0.80 high-risk threshold for women.', 'This is below the 0.80 high-risk threshold for women.', 'This also exceeds 0.80 and would technically be high-risk too — see VERIFY.md, since 0.83 is a plausible secondary answer.'],
  },
  {
    kind: 'mcq', id: 'sp-48', source: 'sample-pdf', tags: ['sample-paper', 'd4'],
    prompt: 'When progressing a client to more-dynamic plyometric exercises, what is the first element that should be increased?',
    options: ['Rate of force production', 'Explosiveness', 'Stabilization, form, and mechanics during landing', 'Speed'],
    answer: 2,
    explanation: 'Landing mechanics and stabilization must be mastered first before adding more dynamic, explosive plyometric demands — safety and control come before intensity.',
    whyWrong: ['Rate of force production is a later goal, not the first thing to build.', 'Explosiveness comes after a stable landing foundation is established.', '', 'Speed is progressed after stabilization and control are established.'],
  },
  {
    kind: 'mcq', id: 'sp-49', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'Which system puts the body into a relaxed state, termed rest and digest?',
    options: ['Parasympathetic nervous system', 'Sympathetic nervous system', 'Somatic nervous system', 'Central nervous system'],
    answer: 0,
    explanation: 'The parasympathetic nervous system produces the "rest and digest" relaxation response.',
    whyWrong: ['', 'The sympathetic nervous system produces the "fight or flight" response, the opposite state.', 'The somatic nervous system controls voluntary movement, not the rest/digest state.', 'The central nervous system (brain/spinal cord) is not itself the "rest and digest" system.'],
  },
  {
    kind: 'mcq', id: 'sp-50', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'What term best describes the amount of mineral content, such as calcium and phosphorous, in a segment of bone?',
    options: ['Osteopenia', 'Bone density', 'Osteoporosis', 'Sarcopenia'],
    answer: 1,
    explanation: 'Bone density refers to the mineral content (calcium, phosphorus) packed into a given segment of bone.',
    whyWrong: ['Osteopenia is a condition of low bone density, not the measurement term itself.', '', 'Osteoporosis is a more severe condition of very low bone density, not the general measurement term.', 'Sarcopenia refers to loss of muscle mass, not bone mineral content.'],
  },
  {
    kind: 'mcq', id: 'sp-51', source: 'sample-pdf', tags: ['sample-paper', 'd5'],
    prompt: 'This is a conversational technique that helps the listener express the supposed meaning of what was just heard.',
    options: ['Reflections', 'Closed-ended questions', 'Active listening', 'Open-ended questions'],
    answer: 0,
    explanation: 'A reflection is a statement that mirrors back the meaning behind what the client said, confirming understanding.',
    whyWrong: ['', 'Closed-ended questions elicit short yes/no answers, they are not a meaning-reflecting technique.', 'Active listening is the general skill; "reflections" is the specific technique described here.', 'Open-ended questions invite elaboration, they do not reflect meaning back to the speaker.'],
  },
  {
    kind: 'mcq', id: 'sp-52', source: 'sample-pdf', tags: ['sample-paper', 'd4'],
    prompt: 'You have a client seeking weight loss. What range of sets is most appropriate for SAQ drills?',
    options: ['3 or 4 sets', '7 to 8 sets', '5 or 6 sets', '1 or 2 sets'],
    answer: 0,
    explanation: 'For weight-loss-focused clients, SAQ drills are generally programmed at 3–4 sets per drill.',
    whyWrong: ['', 'This exceeds the recommended range for weight-loss clients.', 'This exceeds the recommended range for weight-loss clients.', 'This is below the recommended range for weight-loss clients.'],
  },
  {
    kind: 'mcq', id: 'sp-53', source: 'sample-pdf', tags: ['sample-paper', 'd3'],
    prompt: 'What is the minimum weekly goal of energy expenditure from combined physical activity and exercise for obese clients?',
    options: ['500 kcal', '1,200 kcal', '12,000 kcal', '5,000 kcal'],
    answer: 1,
    explanation: 'A minimum weekly energy-expenditure target of around 1,200 kcal from combined activity and exercise is a commonly cited goal for obese clients.',
    whyWrong: ['This is below the recommended minimum.', '', 'This figure is unrealistically high for a weekly target.', 'This is well above the commonly cited minimum target.'],
  },
  {
    kind: 'mcq', id: 'sp-54', source: 'sample-pdf', tags: ['sample-paper', 'd5'],
    prompt: 'A client is asked, "Why do you want to lose weight?" This is an example of what kind of question?',
    options: ['Directive', 'Closed-ended', 'Contemplation', 'Open-ended'],
    answer: 3,
    explanation: 'This question can\'t be answered with a simple yes/no — it invites the client to explain, making it open-ended.',
    whyWrong: ['This is not a directive/instructional statement, it is a question inviting reflection.', 'A closed-ended question would prompt a short yes/no answer; this one invites elaboration.', '"Contemplation" is a stage of change, not a question type.', ''],
  },
  {
    kind: 'mcq', id: 'sp-55', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'Which of the following parts of the body is not subject to increases in density through resistance training?',
    options: ['Bone', 'Heart', 'Soft tissue', 'Nerves'],
    answer: 3,
    explanation: 'Resistance training increases the density/strength of bone, connective (soft) tissue, and can influence the heart, but nerve tissue itself does not undergo this kind of density increase.',
    whyWrong: ['Bone density does increase with resistance training (Wolff\'s law).', 'The heart adapts to training as a muscle, so it is not the exception here.', 'Soft tissue (tendons/ligaments) does strengthen with resistance training.', ''],
  },
  {
    kind: 'mcq', id: 'sp-56', source: 'sample-pdf', tags: ['sample-paper', 'd3'],
    prompt: 'What activity is especially beneficial for combating the loss of muscle mass, power, and strength for aging adults?',
    options: ['Aerobics', 'Walking', 'Resistance training', 'Cardio'],
    answer: 2,
    explanation: 'Resistance training is the specific intervention shown to counter sarcopenia (age-related loss of muscle mass, power, and strength).',
    whyWrong: ['Aerobics primarily targets cardiorespiratory fitness, not muscle mass/strength preservation.', 'Walking is a low-intensity cardio activity, not the primary countermeasure for strength/power loss.', '', 'General cardio does not specifically target the muscle mass and strength losses described.'],
  },
  {
    kind: 'mcq', id: 'sp-57', source: 'sample-pdf', tags: ['sample-paper', 'd4'],
    prompt: 'According to the integrated performance paradigm, which of the following is a requirement for the safe control of movement during plyometrics?',
    options: ['Power', 'Neuromuscular stabilization', 'Speed', 'Strength'],
    answer: 1,
    explanation: 'The integrated performance paradigm requires neuromuscular stabilization before power/speed can be safely expressed.',
    whyWrong: ['Power is a later stage of the paradigm, not the foundational safety requirement.', '', 'Speed is a later stage of the paradigm, not the foundational safety requirement.', 'Strength alone is not sufficient — stabilization control is the specific safety requirement.'],
  },
  {
    kind: 'mcq', id: 'sp-58', source: 'sample-pdf', tags: ['sample-paper', 'd4'],
    prompt: 'Which exercise would be most appropriate for a maximal strength movement in Phase 4 (Maximal Strength Training)?',
    options: ['Single-leg dumbbell biceps curl to shoulder press', 'Stability ball push-up', 'Shoulder/military press', 'Squat jump'],
    answer: 2,
    explanation: 'A straightforward, heavily-loadable compound lift like the shoulder/military press fits Phase 4\'s heavy, low-rep maximal-strength focus.',
    whyWrong: ['This is a stabilization-focused, multi-step exercise better suited to Phase 1–2, not a heavy Phase 4 max-strength lift.', 'A stability ball push-up is a stabilization-emphasis exercise, not a max-strength loadable movement.', '', 'A squat jump is a power (Phase 5) exercise, not a maximal-strength one.'],
  },
  {
    kind: 'mcq', id: 'sp-59', source: 'sample-pdf', tags: ['sample-paper', 'd5'],
    prompt: 'Which of the following would be considered a process goal?',
    options: ['Run one mile', 'Run three times a week', 'Run a 10k race', 'Squat 100 pounds'],
    answer: 1,
    explanation: '"Run three times a week" describes a behavior/action to repeat — a process goal — rather than a specific measurable outcome.',
    whyWrong: ['This is a specific outcome to achieve, making it an outcome goal.', '', 'This is a specific outcome/event, making it an outcome goal.', 'This is a specific measurable outcome, making it an outcome goal.'],
  },
  {
    kind: 'mcq', id: 'sp-60', source: 'sample-pdf', tags: ['sample-paper', 'd4'],
    prompt: 'Which is involved in frontside mechanics?',
    options: ['Knee extension', 'Lead leg', 'Ankle plantar flexion', 'Rear leg'],
    answer: 1,
    explanation: 'Frontside mechanics describe the lead leg\'s action (hip/knee flexion, ankle dorsiflexion) as it drives forward during sprinting.',
    whyWrong: ['Knee extension is part of the rear-leg (backside) push-off, not frontside mechanics.', '', 'Ankle plantarflexion is a backside (rear-leg) mechanic, not frontside.', 'The rear leg is associated with backside mechanics, not frontside.'],
  },
  {
    kind: 'mcq', id: 'sp-61', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'What is a primary difference between a food label and a supplement label?',
    options: [
      'A supplement label is more detailed than a food label.',
      'A supplement label only needs to list what is present, not specific amounts.',
      'Supplement labels only list active ingredients.',
      'There is no difference.',
    ],
    answer: 1,
    explanation: 'Supplement labeling regulations are looser than food labeling — a supplement label can list an ingredient as present without disclosing its exact amount (e.g. inside a "proprietary blend").',
    whyWrong: ['Supplement labels are generally less detailed/regulated than food labels, not more.', '', 'Supplement labels list more than just "active" ingredients; the key issue is disclosure of specific amounts.', 'There is a meaningful regulatory difference between the two label types.'],
  },
  {
    kind: 'mcq', id: 'sp-62', source: 'sample-pdf', tags: ['sample-paper', 'd5'],
    prompt: 'Intentions are a good predictor of behavior, but what has been shown to help translate intentions into behavior?',
    options: ['Subjective norms', 'Action self-efficacy', 'Planning', 'Outcome expectations'],
    answer: 2,
    explanation: 'Concrete planning (implementation intentions — deciding when/where/how) is what has been shown to help bridge the gap between merely intending to act and actually acting.',
    whyWrong: ['Subjective norms influence whether an intention forms, not whether it converts to action.', 'Self-efficacy supports intention formation and persistence, but planning is the specific bridge to action highlighted here.', '', 'Outcome expectations influence motivation to intend, not the intention-to-action gap specifically.'],
  },
  {
    kind: 'mcq', id: 'sp-63', source: 'sample-pdf', tags: ['sample-paper', 'd3'],
    prompt: 'Which core exercise is most appropriate for an obese client to maximize comfort and to avoid potential hypotensive or hypertensive reactions to the exercise?',
    options: ['Incline plank', 'Supine reverse crunches', 'Stability ball Russian twist', 'Supine floor crunches'],
    answer: 0,
    explanation: 'An incline (rather than supine/flat) position avoids the blood-pressure swings and discomfort that lying flat can cause for obese clients, and avoids excess abdominal pressure.',
    whyWrong: ['', 'Supine (lying flat) positions carry more risk of hypotensive/hypertensive reactions for obese clients.', 'A stability ball twist is a balance-demanding exercise, not the comfort-focused option described.', 'Supine positions are the specific risk being avoided in this scenario.'],
  },
  {
    kind: 'mcq', id: 'sp-64', source: 'sample-pdf', tags: ['sample-paper', 'd3'],
    prompt: 'What is reached when a talk test during exercise reveals a client to be working at ventilatory threshold 2?',
    options: [
      'The ability to talk or hold a conversation during an activity at various intensity levels',
      'The level at which the body can work at its highest sustainable steady-state intensity for only few seconds',
      'The level at which the body can work at its highest sustainable steady-state intensity for more than a few minutes',
      'The point at which the body uses an equal mix of carbohydrate and fat as fuel sources',
    ],
    answer: 2,
    explanation: 'VT2 is defined as the highest exercise intensity that can be sustained steadily for more than a few minutes before anaerobic metabolism dominates.',
    whyWrong: ['This describes the talk test method generally, not the specific definition of VT2 itself.', 'VT2 is sustainable for "more than a few minutes," not just a few seconds.', '', 'This describes a fuel-mix crossover point, not the definition of VT2.'],
  },
  {
    kind: 'mcq', id: 'sp-65', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'You are working with a new client who recently started a low-carbohydrate diet for weight loss. However, she complains of being tired and lacking energy for her training sessions. What might be the reason for her low energy?',
    options: ['Inadequate carbohydrate intake', 'Inadequate protein intake', 'Excess fat intake', 'Inadequate fat intake'],
    answer: 0,
    explanation: 'Carbohydrates are the body\'s primary, most readily available fuel for training; cutting them too low is a well-documented cause of fatigue during exercise.',
    whyWrong: ['', 'Protein intake is not the primary driver of training energy/fatigue in this classic scenario.', 'Excess fat intake is not indicated by the low-carb diet described.', 'Fat intake is not the flagged issue in a specifically low-carbohydrate diet.'],
  },
  {
    kind: 'mcq', id: 'sp-66', source: 'sample-pdf', tags: ['sample-paper', 'd4'],
    prompt: 'Which modality allows for movements to occur as explosively as possible without the need for eccentric deceleration?',
    options: ['Medicine ball', 'Resistance band', 'Suspended bodyweight training', 'Kettlebell'],
    answer: 0,
    explanation: 'Because a medicine ball is released/thrown, there\'s no need to decelerate it eccentrically the way you would a barbell or dumbbell, allowing fully explosive output.',
    whyWrong: ['', 'A resistance band still requires eccentric control as it returns to start.', 'Suspended bodyweight training still requires eccentric control of the load.', 'A kettlebell must still be caught/decelerated eccentrically, unlike a thrown medicine ball.'],
  },
  {
    kind: 'mcq', id: 'sp-67', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'A client looking to add muscle and bulk over the next few months asks for advice on how to consume extra calories. Which of the following would be the most appropriate advice, while remaining within scope of practice?',
    options: [
      'Suggest she increase consumption of high-calorie foods such as ice cream, pizza, and cake.',
      'Recommend she eat high-calorie "cheat meals" more often.',
      'Suggest she increase meal frequency and portion sizes at meals.',
      'Recommend she increase only her protein intake at every meal.',
    ],
    answer: 2,
    explanation: 'General, safe, within-scope guidance is to increase overall meal frequency and portion sizes for a caloric surplus, rather than prescribing specific diet plans or macronutrient targets.',
    whyWrong: ['Recommending specific low-quality foods is not appropriate general nutrition guidance and risks poor nutrition quality.', 'Recommending frequent "cheat meals" is not sound, appropriate advice.', '', 'Recommending a specific macronutrient prescription (protein only) edges toward individualized diet planning, outside general scope.'],
  },
  {
    kind: 'mcq', id: 'sp-68', source: 'sample-pdf', tags: ['sample-paper', 'd4'],
    prompt: 'When using battle ropes as a modality, what diameter of rope would best be used for strength, power, and anaerobic adaptations in which exercises are performed for 30 seconds or less?',
    options: ['0.5 in.', '1 in.', '1.5 in.', '2 in.'],
    answer: 3,
    explanation: 'Thicker, 2-inch battle ropes are heavier and better suited to short (≤30 s), high-intensity strength/power/anaerobic work.',
    whyWrong: ['This is far too thin for strength/power work.', 'This is thinner than recommended for short, high-intensity strength/power sets.', 'This is closer to the thickness used for longer, endurance-oriented sets, not short strength/power sets.', ''],
  },
  {
    kind: 'mcq', id: 'sp-69', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'What are ground reaction forces?',
    options: ['Deceleration forces in the muscles', 'Forces imparted on the body when it contacts the ground after jumping', 'Forces used by the muscles during a jump', 'The force of gravity'],
    answer: 1,
    explanation: 'Ground reaction forces are the forces the ground exerts back on the body upon landing/contact, per Newton\'s third law.',
    whyWrong: ['This describes internal muscular deceleration, not the ground\'s reaction force.', '', 'This describes the muscular effort producing the jump, not the ground\'s reaction to landing.', 'Gravity is a constant force, not specifically the ground\'s reactive force upon impact.'],
  },
  {
    kind: 'mcq', id: 'sp-70', source: 'sample-pdf', tags: ['sample-paper', 'd4'],
    prompt: 'Which of the following is an example of an exercise that targets the local muscles of the core?',
    options: ['Cable rotation', 'Floor crunch', 'Side plank', 'Medicine ball soccer throw'],
    answer: 2,
    explanation: 'A side plank is a stabilization exercise that primarily recruits the local, deep stabilizing muscles of the core.',
    whyWrong: ['A cable rotation is a global-muscle, dynamic movement exercise, not a local-stabilizer exercise.', 'A floor crunch primarily targets global core muscles (rectus abdominis), not the deep local stabilizers.', '', 'A medicine ball throw is a global, power-focused movement, not a local-stabilizer exercise.'],
  },
  {
    kind: 'mcq', id: 'sp-71', source: 'sample-pdf', tags: ['sample-paper', 'd2'],
    prompt: 'Posture uses which anatomical landmark in comparison to other positions of the body?',
    options: ['Spine', 'Ankles', 'Shoulders', 'Knees'],
    answer: 0,
    explanation: 'Posture is generally assessed relative to the position of the spine, comparing other body segments to it.',
    whyWrong: ['', 'The ankles are one checkpoint within a posture assessment, not the central reference landmark.', 'The shoulders are one checkpoint within a posture assessment, not the central reference landmark.', 'The knees are one checkpoint within a posture assessment, not the central reference landmark.'],
  },
  {
    kind: 'mcq', id: 'sp-72', source: 'sample-pdf', tags: ['sample-paper', 'd4'],
    prompt: 'Loaded movement training is best achieved with which training modality?',
    options: ['Speed ladders', 'ViPR', 'Suspended bodyweight training', 'Strength machines'],
    answer: 1,
    explanation: 'ViPR (Vitality, Performance, Reconditioning) tools are specifically designed for "loaded movement training," combining load with dynamic, functional movement patterns.',
    whyWrong: ['Speed ladders are for footwork/agility, not loaded movement training.', '', 'Suspended bodyweight training uses bodyweight, not external load, as its primary resistance.', 'Strength machines fix the movement path, which is the opposite of the free, dynamic nature of loaded movement training.'],
  },
  {
    kind: 'mcq', id: 'sp-73', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'What are the two primary actions of the Golgi tendon organ?',
    options: [
      'Sense change in muscle-tendon tension and speed of tension change',
      'Sense the change in muscle contraction and the speed of the nerve impulse',
      'Sense the amount of eccentric tendon force and joint range of motion',
      'Sense the amount of isometric tendon force and speed of shortening',
    ],
    answer: 0,
    explanation: 'The GTO senses both the change in muscle-tendon tension and the rate (speed) at which that tension changes.',
    whyWrong: ['', 'The GTO does not sense nerve impulse speed.', 'The GTO is not specific to eccentric force or joint ROM.', 'The GTO is not specific to isometric force or shortening speed alone.'],
  },
  {
    kind: 'mcq', id: 'sp-74', source: 'sample-pdf', tags: ['sample-paper', 'd2'],
    prompt: 'What tests should be performed last in the overall assessment flow?',
    options: ['Body composition', 'Performance assessments', 'Biometric data', 'Movement assessments'],
    answer: 1,
    explanation: 'Performance assessments are the most physically demanding and are performed last, after intake, static, and movement assessments.',
    whyWrong: ['Body composition is typically taken earlier, at rest, before more demanding tests.', '', 'Biometric/vitals data is collected earlier in the assessment sequence.', 'Movement assessments come before performance assessments in the standard sequence.'],
  },
  {
    kind: 'mcq', id: 'sp-75', source: 'sample-pdf', tags: ['sample-paper', 'd6'],
    prompt: 'Which of the following answers indicates a primary difference between working as an independent contractor and working as an employee?',
    options: [
      'An employee can earn more per hour than an independent contractor.',
      'An independent contractor is responsible for paying their own taxes, while an employee has taxes withheld by the employer.',
      'An employee can establish their own hours, while an independent contractor must adhere to a specific work schedule.',
      'An independent contractor can expect client referrals from a facility, while an employee will have to find clients on the gym floor.',
    ],
    answer: 1,
    explanation: 'A defining legal/tax distinction is that independent contractors handle their own tax withholding, while employees have taxes withheld automatically by their employer.',
    whyWrong: ['Pay rate is not a defining structural difference between the two classifications.', '', 'This is backwards — independent contractors typically have more schedule flexibility than employees.', 'This is backwards from the typical referral/prospecting dynamic between the two roles.'],
  },
  {
    kind: 'mcq', id: 'sp-76', source: 'sample-pdf', tags: ['sample-paper', 'd2'],
    prompt: 'In most individuals, to what pressure is the blood pressure cuff inflated when measuring resting blood pressure?',
    options: [
      'The cuff is inflated to a value 45 to 55 mm Hg above the point at which the pulse can no longer be felt at the wrist.',
      'The cuff is inflated to a value of 20 to 30 mm Hg above the point at which the pulse can no longer be felt at the wrist.',
      'The cuff is inflated to a value 5 to 10 mm Hg above the point at which the pulse can no longer be felt at the wrist.',
      'The cuff is inflated to a value 70 to 80 mm Hg above the point at which the pulse can no longer be felt at the wrist.',
    ],
    answer: 1,
    explanation: 'The cuff is inflated to about 20–30 mmHg above the point the radial pulse disappears, to ensure it fully occludes the artery before slowly deflating.',
    whyWrong: ['This range is too high above the pulse-disappearance point.', '', 'This range is too small a margin to reliably occlude the artery.', 'This range is far too high above the pulse-disappearance point.'],
  },
  {
    kind: 'mcq', id: 'sp-77', source: 'sample-pdf', tags: ['sample-paper', 'd3'],
    prompt: 'What must older adults complete prior to initiating an exercise program with a Certified Personal Trainer?',
    options: ['PAR-Q+', 'Dietary assessment', 'An annual physical', 'Overhead squat assessment'],
    answer: 0,
    explanation: 'The PAR-Q+ health-screening questionnaire is required before starting an exercise program, especially for higher-risk populations like older adults.',
    whyWrong: ['', 'A dietary assessment is not the required pre-exercise screening tool.', 'An annual physical from a physician is not something a trainer administers or requires directly.', 'The overhead squat assessment is a movement screen performed after initial health screening, not the first required step.'],
  },
  {
    kind: 'mcq', id: 'sp-78', source: 'sample-pdf', tags: ['sample-paper', 'd3'],
    prompt: 'With type 1 diabetes, what hormone does the pancreas fall short in making?',
    options: ['Progesterone', 'Testosterone', 'Insulin', 'Estrogen'],
    answer: 2,
    explanation: 'Type 1 diabetes results from the pancreas producing little or no insulin.',
    whyWrong: ['Progesterone is not related to type 1 diabetes.', 'Testosterone is not related to type 1 diabetes.', '', 'Estrogen is not related to type 1 diabetes.'],
  },
  {
    kind: 'mcq', id: 'sp-79', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'Current sports nutrition guidelines from the International Society of Sports Nutrition recommend what range of protein for most exercising individuals?',
    options: ['1.5 to 2.5 g/kg of body weight', '1.0 to 2.0 g/kg of body weight', '1.6 to 2.2 g/kg of body weight', '1.4 to 2.0 g/kg of body weight'],
    answer: 3,
    explanation: 'The ISSN position stand cited by NASM recommends roughly 1.4–2.0 g/kg of body weight per day for exercising individuals.',
    whyWrong: ['This range does not match the cited ISSN guideline.', 'This range does not match the cited ISSN guideline.', 'This range does not match the cited ISSN guideline.', ''],
  },
  {
    kind: 'mcq', id: 'sp-80', source: 'sample-pdf', tags: ['sample-paper', 'd4'],
    prompt: 'Which option is a common power-focused resistance training exercise?',
    options: ['Medicine ball soccer throw', 'Bench press', 'Barbell squat', 'Single-leg cable row'],
    answer: 0,
    explanation: 'A medicine ball throw is an explosive, power-phase exercise, unlike the strength-focused lifts listed as distractors.',
    whyWrong: ['', 'A bench press is a strength-phase exercise, not specifically a power exercise as typically programmed.', 'A barbell squat is a strength-phase exercise unless performed explosively (e.g. as a jump squat).', 'A single-leg cable row is a strength/stabilization exercise, not a power exercise.'],
  },
  {
    kind: 'mcq', id: 'sp-81', source: 'sample-pdf', tags: ['sample-paper', 'd4'],
    prompt: 'Which of the following modality/exercise combinations provides the most demands on explosive power?',
    options: ['Barbell squat', 'Sandbag step-up', 'Medicine ball chest pass', 'Terra-Core push-up'],
    answer: 2,
    explanation: 'A medicine ball chest pass is thrown explosively with no eccentric deceleration required, placing the highest demand on explosive power among these options.',
    whyWrong: ['A barbell squat, as typically performed, is a controlled strength movement, not a maximally explosive throw.', 'A sandbag step-up is a strength/stability exercise, not primarily an explosive-power one.', '', 'A Terra-Core push-up is a stability-challenge exercise, not primarily an explosive-power one.'],
  },
  {
    kind: 'mcq', id: 'sp-82', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'The difference between the end-diastolic and end-systolic volumes is referred to as what?',
    options: ['Cardiac output', 'Venous return', 'Resting heart rate', 'Stroke volume'],
    answer: 3,
    explanation: 'Stroke volume is defined as end-diastolic volume minus end-systolic volume — the amount of blood ejected per beat.',
    whyWrong: ['Cardiac output is stroke volume × heart rate (per minute), not this difference itself.', 'Venous return is blood flowing back to the heart, not this specific volume difference.', 'Resting heart rate is a rate (beats/min), unrelated to this volume calculation.', ''],
  },
  {
    kind: 'mcq', id: 'sp-83', source: 'sample-pdf', tags: ['sample-paper', 'd4'],
    prompt: 'Which of the following core exercises best suits stabilization training?',
    options: ['Barbell chest press', 'Repeat step-ups', 'Deadlifts', 'Floor bridge'],
    answer: 3,
    explanation: 'The floor bridge is a classic Phase 1 stabilization-level core exercise.',
    whyWrong: ['A barbell chest press is an upper-body strength exercise, not a core stabilization exercise.', 'Step-ups are a lower-body/balance exercise, not a core-stabilization exercise.', 'Deadlifts are a strength-phase compound lift, not a stabilization-level core exercise.', ''],
  },
  {
    kind: 'mcq', id: 'sp-84', source: 'sample-pdf', tags: ['sample-paper', 'd4'],
    prompt: 'Proper extensibility of which of these global core muscles is important prior to performing the medicine ball pullover throw?',
    options: ['Multifidus', 'Latissimus dorsi', 'Diaphragm', 'Quadriceps'],
    answer: 1,
    explanation: 'The pullover throw moves the arms overhead and back, so the latissimus dorsi (a global core/shoulder muscle) needs adequate length/extensibility to allow the movement safely.',
    whyWrong: ['Multifidus is a deep, local core stabilizer, not the global muscle whose length matters here.', '', 'The diaphragm is a breathing muscle, not the limiting factor for this overhead throwing motion.', 'The quadriceps are lower-body muscles, unrelated to this upper-body throw.'],
  },
  {
    kind: 'mcq', id: 'sp-85', source: 'sample-pdf', tags: ['sample-paper', 'd4'],
    prompt: 'Which of the following exercises may increase inaccurate readings while utilizing a wrist-worn heart rate monitor?',
    options: ['Suspended bodyweight crunch', 'Barbell squats', 'Stability ball plank', 'Medicine ball catch and pass'],
    answer: 3,
    explanation: 'Rapid, repetitive wrist/arm motion (like catching and passing a medicine ball) disrupts the optical sensor contact and motion-tracking accuracy of wrist-worn HR monitors.',
    whyWrong: ['This exercise involves less rapid wrist motion than the correct answer.', 'The wrists are relatively stable during a squat, so this is less likely to disrupt the monitor.', 'The wrists are relatively stable during a plank, so this is less likely to disrupt the monitor.', ''],
  },
  {
    kind: 'mcq', id: 'sp-86', source: 'sample-pdf', tags: ['sample-paper', 'd3'],
    prompt: 'What can Phase 1 of the OPT model best be described as?',
    options: ['Utilizing supersets during training', 'Focusing on improving muscular growth', 'Mastering basic movement patterns', 'Improving the rate of force production'],
    answer: 2,
    explanation: 'Phase 1 (Stabilization Endurance) is about building foundational control and mastering basic movement patterns before adding load, speed, or power.',
    whyWrong: ['Supersets are a technique used in later strength phases, not the defining description of Phase 1.', 'Muscular growth (hypertrophy) is the focus of Phase 3, not Phase 1.', '', 'Rate of force production is a Phase 5 (Power) focus, not Phase 1.'],
  },
  {
    kind: 'mcq', id: 'sp-87', source: 'sample-pdf', tags: ['sample-paper', 'd4'],
    prompt: 'Which term best describes core training’s effect on decreasing the incidence of new injuries?',
    options: ['Rehabilitation', 'Performance', 'Improved posture', 'Injury resistance'],
    answer: 3,
    explanation: 'Reducing the likelihood of new injuries occurring is described as building injury resistance.',
    whyWrong: ['Rehabilitation refers to recovering from an existing injury, not preventing new ones.', '"Performance" is a broader outcome category, not the specific injury-prevention term.', 'Improved posture is a related benefit but is not the specific term for injury-prevention effect.', ''],
  },
  {
    kind: 'mcq', id: 'sp-88', source: 'sample-pdf', tags: ['sample-paper', 'd6'],
    prompt: 'Using the healthcare continuum, how would training with a fitness professional be classified?',
    options: ['Preventive care', 'Physical therapy', 'Alternative medicine', 'Behavioral health'],
    answer: 0,
    explanation: 'On the healthcare continuum, a fitness professional\'s services sit in the preventive care category — helping clients avoid future health problems.',
    whyWrong: ['', 'Physical therapy is a licensed medical/rehabilitative service, outside a trainer\'s scope.', 'Personal training is not classified as alternative medicine.', 'Behavioral health is a separate, licensed mental-health category, not personal training.'],
  },
  {
    kind: 'mcq', id: 'sp-89', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'Abnormal breathing may be associated with which of the following effects?',
    options: [
      'Slow inhalation through the nose with limited chest movement',
      'Slow inhalation with expansion of the stomach',
      'Deep breaths with use of the diaphragm',
      'Shallow rapid breaths with use of the sternocleidomastoid',
    ],
    answer: 3,
    explanation: 'Shallow, rapid chest breathing that recruits the sternocleidomastoid/scalenes (accessory breathing muscles) is a hallmark of dysfunctional, abnormal breathing.',
    whyWrong: ['This describes calm, controlled nasal breathing, not an abnormal pattern.', 'Stomach (diaphragmatic) expansion during slow inhalation is normal, healthy breathing.', 'Diaphragmatic breathing is the normal, healthy pattern, not the abnormal one.', ''],
  },
  {
    kind: 'mcq', id: 'sp-90', source: 'sample-pdf', tags: ['sample-paper', 'd4'],
    prompt: 'What is pertinent information for the fitness professional to consider before prescribing flexibility exercises?',
    options: [
      'Cardiovascular testing and overhead squat assessment results',
      'PAR-Q and overhead squat assessment results',
      'Any medical precautions or contraindications',
      'Client lifestyle and PAR-Q results',
    ],
    answer: 2,
    explanation: 'Before prescribing any exercise, including flexibility work, the trainer must consider any medical precautions or contraindications flagged during intake.',
    whyWrong: ['Cardiovascular testing is not the specific consideration for flexibility prescription.', 'This omits the broader, more critical medical-precautions consideration.', '', 'This omits the direct medical-precautions consideration in favor of more general lifestyle info.'],
  },
  {
    kind: 'mcq', id: 'sp-91', source: 'sample-pdf', tags: ['sample-paper', 'd3'],
    prompt: 'Which essential component of an OPT workout is beneficial for developing stability, muscular endurance, hypertrophy, strength, power, and athleticism?',
    options: ['Skill development', 'Activation', 'Resistance training', 'Warm-up'],
    answer: 2,
    explanation: 'Resistance training is the component that, across the 5 OPT phases, develops stability, endurance, hypertrophy, strength, power, and athleticism.',
    whyWrong: ['Skill development targets sport-specific technique, not this full range of adaptations.', 'Activation refers to warm-up/prep work, not the full range of adaptations listed.', '', 'Warm-up prepares the body but does not itself drive these training adaptations.'],
  },
  {
    kind: 'mcq', id: 'sp-92', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'How many B vitamins are there?',
    options: ['21', '8', '3', '12'],
    answer: 1,
    explanation: 'There are 8 B vitamins (the "B-complex").',
    whyWrong: ['This overstates the number of B vitamins.', '', 'This understates the number of B vitamins.', 'This overstates the number of B vitamins.'],
  },
  {
    kind: 'mcq', id: 'sp-93', source: 'sample-pdf', tags: ['sample-paper', 'd3'],
    prompt: 'Which of the following statements regarding true Tabata training is considered accurate?',
    options: [
      'The total duration of the workout is 20 minutes long and performed at near maximal effort.',
      'The total duration of the workout is 4 minutes long and performed at 170% of VO2max.',
      'The work-to-recovery intervals are 3:1 (30 sec work + 10 sec recovery) for a total of 12 intervals.',
      'The work-to-recovery intervals are 1:2 (20 sec work + 40 sec recovery) for a total of 10 intervals.',
    ],
    answer: 1,
    explanation: 'The original Tabata protocol is 8 rounds of 20 seconds work / 10 seconds rest — a total of 4 minutes — performed at an intensity around 170% of VO2max.',
    whyWrong: ['This overstates the total duration and does not match the original protocol.', '', 'This gets the work/rest ratio and total interval count wrong for the original protocol.', 'This gets the work/rest ratio backwards from the original protocol (which is high-intensity work with short rest).'],
  },
  {
    kind: 'mcq', id: 'sp-94', source: 'sample-pdf', tags: ['sample-paper', 'd1', 'VERIFY'],
    prompt: 'Which common cause of death is the most preventable?',
    options: ['Obesity', 'Cancer', 'Stroke', 'Dementia'],
    answer: 0,
    explanation: 'Per this answer key, obesity is treated as the most preventable common cause of death, driven largely by modifiable lifestyle factors — see VERIFY.md, since some public-health sources point to tobacco use as the single most preventable cause of death instead.',
    whyWrong: ['', 'Cancer has both preventable and non-preventable (e.g. genetic) causes.', 'Stroke risk is influenced by many factors, several non-modifiable.', 'Dementia has significant non-modifiable risk factors (e.g. genetics, age).'],
  },
  {
    kind: 'mcq', id: 'sp-95', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'Before carbohydrates, fat, or protein can enter the citric acid cycle (CAC), they need to be converted to what common molecule?',
    options: ['Amino acids', 'Acetyl CoA', 'ATP', 'Pyruvate'],
    answer: 1,
    explanation: 'All three macronutrients are converted into acetyl CoA before entering the citric acid cycle.',
    whyWrong: ['Amino acids are the breakdown product of protein specifically, not the shared entry molecule for all three.', '', 'ATP is the energy output of the cycle, not the entry molecule.', 'Pyruvate is an intermediate specific to carbohydrate breakdown, not the shared entry molecule for all three macronutrients.'],
  },
  {
    kind: 'mcq', id: 'sp-96', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'Which of the following hormones, if increased at baseline, may be indicative of overtraining?',
    options: ['Cortisol', 'Thyroxin', 'Testosterone', 'Growth hormone'],
    answer: 0,
    explanation: 'Chronically elevated baseline cortisol (a catabolic stress hormone) is a recognized marker of overtraining.',
    whyWrong: ['', 'Thyroxin is not the hormone typically flagged for overtraining monitoring in this context.', 'Testosterone (an anabolic hormone) would typically be suppressed, not elevated, with overtraining.', 'Growth hormone is not the marker associated with overtraining in this context.'],
  },
  {
    kind: 'mcq', id: 'sp-97', source: 'sample-pdf', tags: ['sample-paper', 'd3'],
    prompt: 'Starting at what percentage of bone density loss does the risk of hip fracture increase by 2.5 times?',
    options: ['20%', '10%', '30%', '5%'],
    answer: 1,
    explanation: 'A 10% loss in bone density is associated with a 2.5x increase in hip fracture risk.',
    whyWrong: ['This overstates the threshold percentage.', '', 'This overstates the threshold percentage.', 'This understates the threshold percentage.'],
  },
  {
    kind: 'mcq', id: 'sp-98', source: 'sample-pdf', tags: ['sample-paper', 'd1'],
    prompt: 'Which component contributes the most to total energy expenditure?',
    options: ['Resting metabolism', 'Exercise', 'Thermic effect of food', 'Thermic effect of activity'],
    answer: 0,
    explanation: 'Resting metabolic rate (RMR) is the largest single component of total daily energy expenditure for most people.',
    whyWrong: ['', 'Exercise is typically a smaller share of total daily energy expenditure than RMR for most people.', 'The thermic effect of food is a relatively small component of total energy expenditure.', 'Non-exercise activity thermogenesis is generally smaller than RMR\'s share of total expenditure.'],
  },
  {
    kind: 'mcq', id: 'sp-99', source: 'sample-pdf', tags: ['sample-paper', 'd5'],
    prompt: 'A client who has been training consistently for over a year has indicated that he wants to find more efficient ways to exercise at home. Which type of social support does he need?',
    options: ['Informational support', 'Emotional support', 'Companionship support', 'Instrumental support'],
    answer: 0,
    explanation: 'He is asking for knowledge/advice (efficient ways to exercise at home) — that is informational support.',
    whyWrong: ['', 'Emotional support involves encouragement/empathy, not the practical advice he is asking for.', 'Companionship support involves shared activity/company, not advice.', 'Instrumental support involves tangible/practical help (e.g. equipment, transportation), not information/advice.'],
  },
  {
    kind: 'mcq', id: 'sp-100', source: 'sample-pdf', tags: ['sample-paper', 'd4'],
    prompt: 'Which muscle would you be targeting for SMR if you placed the roller along the front and slightly lateral (outside) part of the upper thigh (just below the pelvis)?',
    options: ['Adductors', 'Piriformis', 'Tensor fascia latae', 'Thoracic spine'],
    answer: 2,
    explanation: 'The front-lateral upper thigh, just below the pelvis, is the TFL (tensor fascia latae) roller placement.',
    whyWrong: ['Adductors are rolled on the inner thigh, not the front-lateral upper thigh.', 'The piriformis is rolled at the glute/hip area, not the front-lateral thigh.', '', 'The thoracic spine is an upper-back roller placement, unrelated to the thigh.'],
  },
]
